### ISSUE TITLE
com.ring

### ISSUE THREAD

**Issue by denniedegroot** [athombv/homey-vectors-public#1]
If possible I would like a svg image of the Ring Doorbell Pro and Chime for my new application.

Doorbell image:
https://static.ring.com/assets/static/ring-doorbell-pro-b6b0ba44210856b81795e0f41ec611ab.png

Chime image:
https://support.ring.com/hc/en-us/article_attachments/202559194/RingChime.PNG

**Comment by IvoDerksen** [comment]
Hey Dennie,

Here you go!
Good luck on the app!

[com.ring.zip](https://github.com/athombv/homey-vectors-public/files/693970/com.ring.zip)

**Comment by denniedegroot** [comment]
The icons look great, thanks!

**Comment by IvoDerksen** [comment]
Dennie, I will make sure these are done before thursday!

**Comment by IvoDerksen** [comment]
Hey Dennie, here you go!
[com.ring_extra.zip](https://github.com/athombv/homey-vectors-public/files/714023/com.ring_extra.zip)

**Comment by denniedegroot** [comment]
Thanks again Ivo!
