### ISSUE TITLE
com.mcohome images

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#10]
Hi Ivo,

I do need some additional vector magic from you.

Could you create some new icons for my new MCO HOME app?
- MCO HOME ICON: http://www.mcohome.com/images/logo.png
- MH7 thermostat: http://www.vesternet.com/media/wysiwyg/MCO/Water_Heating_Thermostat_Display.JPG
- MH9 CO2 monitor: 
https://www.robbshop.nl/media/wysiwyg/Icons/description.jpg
http://store.zwavecenter.com/image/cache/catalog/products/MCO_Home_MH-9_CO2-500x500.jpg
- MH10 PM2.5 
http://i.ebayimg.com/images/g/8vMAAOSwFV9XxaT3/s-l500.jpg
- S412 switch
http://www.mcohome.com/upload/annex/14617479912.png
- S314 switch
- http://www.mcohome.com/upload/20160331/20160331172337.png

Much appreciated (as allways).

**Comment by IvoDerksen** [comment]
ETA tomorrow!

**Comment by IvoDerksen** [comment]
Hey Ted!
The icons are finished!
If you have any remarks, let me know!
As always, happy coding!
