### ISSUE TITLE
Sonoff

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/homey-vectors-public#100]
Hi, me again:)

Could you provide me some cool icons for the following devices?

- [basiczbr3](https://sonoff.tech/product/zigbee-diy-smart-switches/basiczbr3)
- [s31-lite-zb](https://sonoff.tech/product/zigbee-smart-plugs/sonoff-s31-lite-zb)
- [snzb-01](https://sonoff.tech/product/smart-home-security/snzb-01)
- [snzb-02](https://sonoff.tech/product/smart-home-security/snzb-02)
- [snzb-03](https://sonoff.tech/product/smart-home-security/snzb-03)
- [snzb-04](https://sonoff.tech/product/smart-home-security/snzb-04)

thx!

**Comment by IvoDerksen** [comment]
here you go!
