### ISSUE TITLE
[com.technisat.smarthome] App icon and driver icons

### ISSUE THREAD

**Issue by KyleTaylorParkins** [athombv/homey-vectors-public#102]
For yet another integration for a small smarthome brand, Technisat, I'm looking for some icons to release the app :)

I've started with the wall mount devices (https://www.technisat.com/en_XX/Flush-mounting-units/352-22701/), and since they're almost identical, two icons will be sufficient. One for the single button devices and one for the dual button devices.

Single button: https://www.technisat.com/en_XX/On-Off-switch-flush-mount,-BJ/352-22702-22935/
Dual buttons: https://www.technisat.com/en_XX/Series-switch-flush-mount,-BJ/352-22703-22936/

For the brand icon, I already found this vector: https://commons.wikimedia.org/wiki/File:TechniSat_Logo.svg. However, I think the viewbox is not correctly since Homey places it top left rather then centered.

Thanks in advance, our vector hero @IvoDerksen !

**Comment by IvoDerksen** [comment]
Hey Kyle!

I'd suppose the single button and dual button to represent the final outcome. So buttons!
I've attached the latest icon in SVG that scales as we want!.

**Comment by KyleTaylorParkins** [comment]
Thanks, looking good! Already integrated them in the app, looks way better now.
