### ISSUE TITLE
Bitron vector graphics

### ISSUE THREAD

**Issue by mveck** [athombv/homey-vectors-public#103]
Could you provide vector graphics for the following Bitron Video devices?

902010_24  (Smoke detector)
902010_22  (Movement Sensor)
902010_21 (Magnetic Door Sensor).

Rudimentary SVG's are pushed to Beta Branch.

All part of the Beta Branch of de.mhaid.bitron  ... drivers will be published for 5.0.0+ kernel

Thanks,
Menno van Eck

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by mveck** [comment]
Thanks for the quick response.
