### ISSUE TITLE
Amazon Echo v4

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#104]
Happy new year Ivo!

I am looking at adding the new echo devices to the alexa app : they consist of 

Echo Dot (4th Gen) : https://www.amazon.com.au/dp/B08F1LYDBR?ref=MarsFS_AUCC_be
Echo (4th Gen) : https://www.amazon.com.au/dp/B085G63QHT?ref=MarsFS_AUCC_lr
Echo Show 10 (3rd Gen) : https://www.amazon.com.au/dp/B084NTF5ZY?ref=MarsFS_AUCC_ta

I actually think that the dot is just a smaller version of the Echo. 

No need to rush :-)

**Comment by IvoDerksen** [comment]
Happy new year Jamie, here you go!

**Comment by hive** [comment]
Wow that was so quick, Thanks!
