### ISSUE TITLE
vector graphics for INNR Zigbee app

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-vectors-public#11]
Could you please help me out with some high quality vector graphics for my INNR signee app?

https://github.com/kasteleman/com.innr

Also the pairing picture for the remote would be nice.

Regards,

Martin

**Comment by IvoDerksen** [comment]
Hey Martin,

Of course I can, can you specify which devices? And maybe a link to the support page, for pairing.

Kind regards,
Ivo

**Comment by kasteleman** [comment]
Hi Ivo,

I already made the icons, and you can find them in the repo, but they are
of a bad quality. Captured from a pdf and converted online.

Have to lookup the device names and wil provide Some links in the morning.

Regards,

Martin

Op vr 1 sep. 2017 om 00:16 schreef Ivo Derksen <notifications@github.com>

**Comment by IvoDerksen** [comment]
Cheers! 
And I will start with what you've got already.

**Comment by kasteleman** [comment]
Morning Ivo,

I have a link with photo’s from INNR, but been asked not to share it in public, so my request: Can I contact you at a privat mailaccount?

Regards,

Martin

**Comment by IvoDerksen** [comment]
Hey Martin!

I've received the link from Stefan. I've managed to get the current devices in this update.
When you build support for the candle etc. I will add them too!

Good job on the App!

If you have any remarks, don't hesitate to contact me!

Best regards,

Ivo
