### ISSUE TITLE
heiman hs1rc-ef

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/homey-vectors-public#112]
Aaand another one:

![image](https://user-images.githubusercontent.com/29612400/115671454-d1efe780-a34a-11eb-814c-3536a8912e7f.png)

https://nl.aliexpress.com/item/32892074229.html
https://github.com/MadMonkey87/HomeyCONZ/issues/51

Thx in advance

**Comment by IvoDerksen** [comment]
Ofcourse! 
Here you go!
