### ISSUE TITLE
com.nvent.raychem

### ISSUE THREAD

**Issue by edwinvdpol** [athombv/homey-vectors-public#113]
Hi, can you please create a vector for the SENZ-WIFI from nVent? Much appreciated!

You can discard the 'glare' that starts at the top. :wink: The middle screen is important though.

![senz-wifi](https://user-images.githubusercontent.com/9265514/116078792-53bb7a00-a697-11eb-85bf-263bb7326e64.jpg)

**Comment by IvoDerksen** [comment]
Coming right up!

**Comment by IvoDerksen** [comment]
There you go!

**Comment by edwinvdpol** [comment]
You are amazing, thank you!
