### ISSUE TITLE
Ring Security devices

### ISSUE THREAD

**Issue by daneedk** [athombv/homey-vectors-public#114]
Hi Ivo,

I'm working on integration of the Ring Security (com.ring.security) devices and I need Device Icons. (I was able to create the pairing svgs myself as the manual had line drawings that were easily converted to svgs.)

Ring Keypad (V1)
![Ring Keypad 2000x2000](https://user-images.githubusercontent.com/16610696/116446588-6381bc80-a857-11eb-868b-3a49faa78cbd.png)

Ring Motion Detector (V1)
![Ring Motion Detector 2000x2000](https://user-images.githubusercontent.com/16610696/116446647-73010580-a857-11eb-86a3-17901f4132d3.png)

Ring Contact Sensor (V1)
(It would be ok to leave out the rightmost part, the 2 parts on the left are the actual sensor and magnet)
![Ring Contact Sensor 2000x2000](https://user-images.githubusercontent.com/16610696/116446698-7eecc780-a857-11eb-937e-ec64981b9357.png)

**Comment by IvoDerksen** [comment]
I'll get on it :)

**Comment by IvoDerksen** [comment]
Hey! I've created the icons. I don't know if you also use the doorbells, but I've updated those too, to keep the style consitent :)

**Comment by daneedk** [comment]
Great, thank you very much!
