### ISSUE TITLE
io.olae.meatercloud

### ISSUE THREAD

**Issue by olaeriksson** [athombv/homey-vectors-public#115]
I need some device Icons for Meater meat thermometers. (www.meater.com)

### The MEATER Probe
This is the actual probe used in all meater products and hence the most important one.
![image](https://user-images.githubusercontent.com/29456953/118484112-2488ad80-b717-11eb-88b6-73d881b8b943.png)
![image](https://user-images.githubusercontent.com/29456953/118484333-63b6fe80-b717-11eb-9e72-6a5f2fa658df.png)

### The Original MEATER
https://store-eu.meater.com/products/meater
![image](https://user-images.githubusercontent.com/29456953/118483789-be038f80-b716-11eb-9618-05578bf671e7.png)

### Meater Plus
https://store-eu.meater.com/products/meater-plus
![image](https://user-images.githubusercontent.com/29456953/118483856-d378b980-b716-11eb-9c3d-27287b3551cf.png)

### Meater Block
https://store-eu.meater.com/products/meater-block
![image](https://user-images.githubusercontent.com/29456953/118483915-e9867a00-b716-11eb-99d0-b20b088531f4.png)

Thanks in advance!

**Comment by IvoDerksen** [comment]
Damn, didn't know this existed! I like my job :)

**Comment by olaeriksson** [comment]
> Damn, didn't know this existed! I like my job :)

Pretty awesome product actually. But be prepared go gain quite some weight if you get one :-)

**Comment by IvoDerksen** [comment]
Ghehe, it looks really neat, great product for meat!

Happy coding!
