### ISSUE TITLE
Ring Security Devices, 2nd Generation

### ISSUE THREAD

**Issue by daneedk** [athombv/homey-vectors-public#116]
Hi Ivo,

Now that Homey V7 with S2 support is around the corner I will be adding Ring Security devices from the 2nd generation and I need some new device icons, I hope you can create them for me.

Thanks!

Ring Keypad 2nd Gen
![Ring Keypad V2 - 2000x2000](https://user-images.githubusercontent.com/16610696/120370895-6f104980-c315-11eb-922c-68d5a4d73f9d.png)

Ring Motion Detector 2nd Gen
![Ring Motion Detector V2 - 2000x2000](https://user-images.githubusercontent.com/16610696/120371139-ada60400-c315-11eb-98c8-f654068ea807.png)

Ring Contact Sensor 2nd Gen
![Ring Contact Sensor V2 - 2000x2000](https://user-images.githubusercontent.com/16610696/120371210-c3b3c480-c315-11eb-9538-18b94a8e9a6f.png)

**Comment by IvoDerksen** [comment]
Ofcourse!
