### ISSUE TITLE
Blueriiot Blue Connect

### ISSUE THREAD

**Issue by fpalsson** [athombv/homey-vectors-public#117]
App in development: Blueriiot Blue Connect. System for measuring pool water quality (temperature, pH, ORP and conductivity)

Blueriiot is the company/brand name and Blue Connect is the device.

Need app and driver icons.

![image](https://user-images.githubusercontent.com/60402000/121130935-61842380-c82f-11eb-8ef4-73de5216be40.png)
![image](https://user-images.githubusercontent.com/60402000/121131419-0ef73700-c830-11eb-9150-deb4a751b580.png)
![image](https://user-images.githubusercontent.com/60402000/121131006-78c31100-c82f-11eb-822f-76d736afe708.png)
![image](https://user-images.githubusercontent.com/60402000/121131234-c50e5100-c82f-11eb-843f-80ef4d884563.png)

**Comment by IvoDerksen** [comment]
On it!

**Comment by fpalsson** [comment]
> On it!

Thanks in advance!

**Comment by IvoDerksen** [comment]
Here you go!
Both the app icon and the driver icon. You can rename the app folder and driver folder or copy the folders in respectively as stated in the docs!
Happy coding!

**Comment by fpalsson** [comment]
> Here you go!
> Both the app icon and the driver icon. You can rename the app folder and driver folder or copy the folders in respectively as stated in the docs!
> Happy coding!

Thanks!
