### ISSUE TITLE
BMW ConnectedDrive

### ISSUE THREAD

**Issue by lsiddiquee** [athombv/homey-vectors-public#118]
appid: com.rexwel.bmwconnected

![xlarge](https://user-images.githubusercontent.com/15940466/123937492-84b97300-d996-11eb-859c-b3572b3aa049.png)

**Comment by IvoDerksen** [comment]
Here you go!
[icon-2.svg.zip](https://github.com/athombv/homey-vectors-public/files/6750897/icon-2.svg.zip)
It's the most recent version of the logo in SVG format!

**Comment by lsiddiquee** [comment]
@IvoDerksen  thanks a lot.
