### ISSUE TITLE
com.xiaomi-mi-zigbee vector images

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#12]
Hi Ivo,

Could you make the svg icons for the Xiaomi-mi app?

See this repository for the device images and names:
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/tree/SDK2

For some devices, I already made some initial icons based on a scanned image out of the manual... which is visible if you carefully look at them...

Much appreciated!

Ted

**Comment by BasKiers** [comment]
Quick links to make it more easy to find which icons need to be made:

Device Name | Current Icon | Image
------------ | ------------- | -------------
aqara_door_window_sensor | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_door_window_sensor/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_door_window_sensor/assets/images/large.png)
aqara_human_body_sensor | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_human_body_sensor/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_human_body_sensor/assets/images/large.png)
aqara_weather_sensor | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_weather_sensor/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_weather_sensor/assets/images/large.png)
aqara_wireless_switch | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_wireless_switch/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_wireless_switch/assets/images/large.png)
door_window_sensor | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/door_window_sensor/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/door_window_sensor/assets/images/large.png)
human_body_sensor | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/human_body_sensor/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/human_body_sensor/assets/images/large.png)
temperature_humidity_sensor | [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/temperature_humidity_sensor/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/temperature_humidity_sensor/assets/images/large.png)
wireless_switch| [current icon](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/wireless_switch/assets/icon.svg) | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/wireless_switch/assets/images/large.png)

**Comment by IvoDerksen** [comment]
It is done!
Good luck on completion!
I'll be looking forward to it!

**Comment by TedTolboom** [comment]
Hi Ivo,

Thanks for the icons.

I was ouf of office last week, so I did not check @BasKiers's table.... but he missed the devices without driver (and icons)... which I added already..

Could you create these icons as well?
Following Bas' example, in a nice table:

**Device Name | Current Icon | Image**
aqara_light_control_single | current icon | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_light_control_single/assets/images/large.png)
aqara_light_control_double | current icon | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_light_control_double/assets/images/large.png)
aqara_light_switch_single | current icon | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_light_switch_single/assets/images/large.png)
aqara_light_switch_double | current icon | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_light_switch_double/assets/images/large.png)
aqara_water_sensor | current icon | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/aqara_water_sensor/assets/images/large.png)
cube | current icon | [image](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/SDK2/drivers/cube/assets/images/large.png)

**Comment by IvoDerksen** [comment]
Hey Ted,
I'm sorry for not checking it manually. Thanks for the table, and I'll work on them!
