### ISSUE TITLE
Some Tp-Link Tapo devices please

### ISSUE THREAD

**Issue by slovak-cat** [athombv/homey-vectors-public#120]
App ID: `space.charliecat.tplinktapo`

Product Links
> https://www.tp-link.com/de/home-networking/smart-bulb/tapo-l510e/
> https://www.tp-link.com/de/home-networking/smart-plug/tapo-p100/

App is still in the making

Thank you

**Comment by IvoDerksen** [comment]
Sure! Will do!

**Comment by slovak-cat** [comment]
thank you

**Comment by IvoDerksen** [comment]
And here you go!
Happy coding!

**Comment by slovak-cat** [comment]
Thank you 😸
