### ISSUE TITLE
io.olae.aeratron

### ISSUE THREAD

**Issue by olaeriksson** [athombv/homey-vectors-public#121]
Hi, I need some icons for the Aeratron ceiling fans please. www.aeratron.com

AE3+ Series
![image](https://user-images.githubusercontent.com/29456953/127027229-a0f05333-970f-4b3b-bee4-d1f638fccedd.png)

AE2+ Series
![image](https://user-images.githubusercontent.com/29456953/127027266-368dbc02-def2-4086-ab93-9dfee74e38b3.png)

FR Series
![image](https://user-images.githubusercontent.com/29456953/127027332-82674ba5-cafa-4421-bc71-3358fbd5ac7a.png)

RF Remote Control (Device icon)
![image](https://user-images.githubusercontent.com/29456953/127027470-bbd35ade-7247-46e0-b19d-54a37d818bce.png)

RF Remote Control (Learn mode)
Would be great to have something similar to the one below for the RF Remote Control. To pair devices with Homey (both remote and the fans), the original remote is used. The user will be instructed to press the "ON/OFF" button in order for Homey to extract the data needed. Would be great if this could be displayed in some nice animation.
https://github.com/athombv/com.ikea.tradfri-example/blob/main/drivers/signal_repeater/assets/learnmode.svg

Thanks in advance!

**Comment by IvoDerksen** [comment]
Woaha! Good stuf! I will create them somewhere tomorrow!

**Comment by olaeriksson** [comment]
Thanks! No rush, I'm still figuring out the protocol, so no immediate need for the icons.

**Comment by IvoDerksen** [comment]
Here you go!
