### ISSUE TITLE
iblindsV3 icon

### ISSUE THREAD

**Issue by chancehiblinds** [athombv/homey-vectors-public#122]
Per https://apps.developer.homey.app/app-store/guidelines#1-5-icons 
I am requesting an icon for the iblindsV3 app / device driver

Device driver is currently awaiting certification com.myiblinds

Current motor picture
![large](https://user-images.githubusercontent.com/64560820/132079835-fdd7d3ef-eb42-4373-85d4-e569b4ab415d.png)

Icon / Company logo we would like to use

![Icon](https://user-images.githubusercontent.com/64560820/132079790-15c330c0-83d4-4c34-922a-8717824e0eb3.png)

**Comment by IvoDerksen** [comment]
Heya! Did you fix it or..?
Kind regards!

**Comment by chancehiblinds** [comment]
Got it working thanks
    	
    
  

 From: Ivo Derksen ***@***.***>Sent: Monday, September 6, 2021 14:31To: athombv/homey-vectors-publicCc: chancehiblinds; State changeSubject: Re: [athombv/homey-vectors-public] iblindsV3 icon (#122) 
Heya! Did you fix it or..?
Kind regards!

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/athombv/homey-vectors-public/issues/122#issuecomment-913824199",
"url": "https://github.com/athombv/homey-vectors-public/issues/122#issuecomment-913824199",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
