### ISSUE TITLE
IKEA  Multiple new lights

### ISSUE THREAD

**Issue by Christian-Athom** [athombv/homey-vectors-public#123]
https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e27-470-lumen-draadloos-dimbaar-wit-spectrum-buisvormig-wit-frosted-glas-90461916/

https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e27-470-lumen-draadloos-dimbaar-wit-spectrum-globe-wit-frosted-glas-20441333/

https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e14-250-lumen-draadloos-dimbaar-warm-wit-kaarslamp-helder-30441380/

https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e27-250-lumen-draadloos-dimbaar-warm-wit-globe-helder-40439254/

**Comment by IvoDerksen** [comment]
Closed!
