### ISSUE TITLE
Solar Panels: SolarEdge inverter

### ISSUE THREAD

**Issue by DiedB** [athombv/homey-vectors-public#127]
![image](https://user-images.githubusercontent.com/7628001/139598446-3c16ffc6-0fdd-470d-a8dd-04e535ff43d8.png)

Could you create an SVG that resembles this inverter? Thanks in advance!

**Comment by IvoDerksen** [comment]
Ofcourse!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by DiedB** [comment]
Great stuff! Thanks a lot!

**Comment by IvoDerksen** [comment]
You're welcome!
