### ISSUE TITLE
rs.muete.homey-qnect

### ISSUE THREAD

**Issue by ultimate-tester** [athombv/homey-vectors-public#128]
I am currently working on a new app for qnect (lower case intentional) devices. These are mainly found at places like Gamma, Praxis, etc.

The logo is as follows:
![image](https://user-images.githubusercontent.com/580758/140539461-74529c84-e3ab-4642-87f9-d0e3dbadfb27.png)

Then for the first product I'm going to add support for (QN-WP05/QN-WP06), they have an image for the sideview and frontview. Not sure which one looks better or is more clear when created as vector. Could you please assist me and use your professional opinion to choose the best looking one out of those?

![image](https://user-images.githubusercontent.com/580758/140539518-c2602d59-2531-4131-a22b-22fa1bbf1522.png)
![image](https://user-images.githubusercontent.com/580758/140539528-74740b17-24c1-4a80-914b-28117cdb77ab.png)

**Comment by IvoDerksen** [comment]
Hey! I've made the app icon and plug icon for you.
We go 3D and like to look 'into' the device.
here you go

**Comment by ultimate-tester** [comment]
Hi Ivo, thanks a lot but where are they :)
