### ISSUE TITLE
Request icons Meross for brand and devices

### ISSUE THREAD

**Issue by palatinb** [athombv/homey-vectors-public#129]
App ID: com.meross

Logo:
![image](https://user-images.githubusercontent.com/24275528/141323715-4950482a-92be-44c9-a70a-40b569c7cc77.png)

And request for device icon and brand icon

Devices:
https://www.meross.com/AllType/Smart
https://www.meross.com/AllType/Gadgets

App is still in the making

Thank you

**Comment by IvoDerksen** [comment]
Hey I will!
Are you planning on integrating all devices (at once)? Else I'd like to create them per batch :)

Let me know!

**Comment by palatinb** [comment]
I'm going to create it in batch. The first devices are MSS110,MSS210, MSS310, MSS425, MSL430.

Thanks in advance!

**Comment by palatinb** [comment]
Is there any date when will be the icons available? Only the icons are missing.

**Comment by palatinb** [comment]
Is there any date when will be the icons available? Only the icons are missing.

Also we rethought what devices would like to support.
The devices we would like to support:


| Smart Light  | Smart switch | Smart Plugs | Smart Thermostat  | Garage door | Smart Hub  | Air purifier  | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|  MSL100  | MSS510  | MSS110  | MTS150  | MSG100  | MSH300  | MAP100  |
|  MSL100D  | MSS550  | MSS120  | MTS100  | MSG200  | |  
|  MSL120  | MSS560  | MSS210  | MTS200  |   |   |  
|  MSL320  | MSS565  | MSS425  |   |   |   |  
|  MSL420  | MSS570  | MSS426  |   |   |   |  
|  MSL430  | MSS710  | MSS620  |   |   |   |   
|  MDL110  |   | MSS630  |   |   |   |  
|  MSL610 |    |   |   |   |   | 

In the first batch we would like to support the following devices:
**MSS210, MSS425, MSL430**

Thanks in advance!

**Comment by IvoDerksen** [comment]
Yes today in de afternoon!

**Comment by IvoDerksen** [comment]
Here are the first few!

**Comment by palatinb** [comment]
Thanks they look great!

The next batch is the following devices: MSS620, MSS710, MSL120, MSS510. Could zou please create the icons for those devices too?

**Comment by IvoDerksen** [comment]
Yes!

**Comment by palatinb** [comment]
Thanks! 

The next and the last batch is the following devices: 

- MSL420 
- MSL320 
- MDL110 
- MSL610 
- MSS620
- MSS110 
- MTS150 
- MTS200 
- MSG100
- MSG200
- MSH300
- MAP100

Could you please create the icons for those devices too?

**Comment by IvoDerksen** [comment]
Yes! 
I will give you a headsup once they're done!

**Comment by IvoDerksen** [comment]
[com.meross.zip](https://github.com/athombv/homey-vectors-public/files/7777142/com.meross.zip)
Here is the full pack!
Happy holidays!

**Comment by IvoDerksen** [comment]
Hi Bence,
I will make them in the coming week!
Kind regards!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
[com.meross.zip](https://github.com/athombv/homey-vectors-public/files/9173645/com.meross.zip)
