### ISSUE TITLE
App: belife device: smartplug

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [athombv/homey-vectors-public#130]
Hi
could you make icons for an app/brand called belife and the smart plug device?
their logo is printed in gray tone on their devices, so the logo could be a nice mono colored logo

![image](https://user-images.githubusercontent.com/1246691/142912524-a0ff4bb9-c0c4-432e-8bb9-6e0cc49a096d.png)
![image](https://user-images.githubusercontent.com/1246691/142912593-2e5d819e-ad12-4e5c-9ad0-681d31342b7c.png)

**Comment by IvoDerksen** [comment]
Ofcourse!

**Comment by IvoDerksen** [comment]
Here you go!
