### ISSUE TITLE
Request icons for Swegon Casa ventilation systems

### ISSUE THREAD

**Issue by azzlack** [athombv/homey-vectors-public#131]
App ID: com.eyecatch.swegoncasa

The devices:
https://www.swegon.com/products/air-handling/casa/

**Comment by IvoDerksen** [comment]
Hey!
On it!

**Comment by IvoDerksen** [comment]
Here you go, an app icon(original logo is possible too), the icons for the freeAir series are done with a lot of precision, since it is an indoor device. The others are boxes, but can be replaced with custom device icons for airco units in the app.
