### ISSUE TITLE
Request for icons for Yandex Alice

### ISSUE THREAD

**Issue by Kraineff** [athombv/homey-vectors-public#136]
Hello! I developing an app called Yandex Alice and I need some icons for speakers!

App is already done and ready to be pushed to store, so I need a better icons!

Here is the image reference:
![IMG_3445](https://user-images.githubusercontent.com/7906418/155834155-6514f52b-ca0b-460b-a327-74fb38f29b15.JPG)
![IMG_3444](https://user-images.githubusercontent.com/7906418/155834187-92703da0-e6a1-4b5e-b015-fb886737a00c.jpg)

One person has already made icons for HA, but in my opinion they are not detailed and the angle of perspective is not the one Homey uses. But anyway you can check this: https://github.com/iswitch/ha-yandex-icons/blob/master/docs/station-max.svg

I need 2 icons: speaker with screen, and without.

Thanks!

**Comment by Kraineff** [comment]
Good! Thank you!

**Comment by Kraineff** [comment]
Wrote information for creation a folder in the repository.

App Id: ru.yandex.alice

Driver - Speaker:
- General Driver Icon (same as yandexstation.svg)
- With screen (yandexstation_2.svg)
- Without screen (yandexstation.svg)

**Comment by IvoDerksen** [comment]
Hey! Here you g
[yandex.zip](https://github.com/athombv/homey-vectors-public/files/8164942/yandex.zip)
o

**Comment by Kraineff** [comment]
Actually this is not the whole list of icons that are supported, there are a few more, I would appreciate it if you make them in the future.
I'll just throw in a couple of pictures of what other speakers are supported and it would be nice to make them as beautiful in the spirit of Homey!

First, there are 3 official speakers from Yandex left:

Yandex Station Mini:
![yand3](https://user-images.githubusercontent.com/7906418/156383098-162741b4-3870-4ff7-aac6-53f655fe98c1.jpg)

Yandex Station Mini 2 (with screen, screen part can be same as on the big Station Max icon):
![10029476b](https://user-images.githubusercontent.com/7906418/156383287-08e10d6f-4dad-4507-8f54-f5aad2d2a6d5.jpg)

Yandex Station Lite:
![orig-2](https://user-images.githubusercontent.com/7906418/156383334-55ca4b36-a6d6-4756-9f58-6607de57748c.png)

**Comment by Kraineff** [comment]
The above are the official columns that most users will add. And now a list of supported speakers from third-party brands that also support our app! They are optional, but if you have time it would be nice to see them too :)

Irbis A:
![14hq](https://user-images.githubusercontent.com/7906418/156384096-9a28491b-1b55-4787-8355-77ff14224399.jpg)

Elari Smartbeat:
![orig](https://user-images.githubusercontent.com/7906418/156384337-fde5feba-9aee-4c62-bd13-6a548cbe9749.jpg)

DEXP Smartbox:
![dexp-smartbox-alisa-black-dns-cena](https://user-images.githubusercontent.com/7906418/156384588-730473c1-1bff-4ef7-8476-5000e872c0e3.jpg)

LG XBOOM AI ThinQ:
![10024819b](https://user-images.githubusercontent.com/7906418/156384847-c509592f-413d-4204-8ca5-635d088811f4.jpg)

Prestigio Smartmate:
![3c599818c90dec5a640eb114947e0dd58781510e7841421b7075293769950c3c](https://user-images.githubusercontent.com/7906418/156385050-288350dc-0ae6-48f1-8770-1af610f31bff.jpg)

JBL Link Music:
![orig-2](https://user-images.githubusercontent.com/7906418/156385325-8378e2fe-f962-4b02-b47d-a4918aa67d48.jpg)

JBL Link Portable:
![orig-3](https://user-images.githubusercontent.com/7906418/156385518-22584622-c070-475b-8d97-9645a1aeb16e.jpg)

**Comment by Kraineff** [comment]
<img width="843" alt="CleanShot 2022-03-03 at 04 06 49@2x" src="https://user-images.githubusercontent.com/7906418/156464851-a6a7cb36-14fd-4e77-9dcb-829426904013.png">

**Comment by Kraineff** [comment]
Station and Station Max (with display) you made looks amazing!

**Comment by IvoDerksen** [comment]
Thanks!
Let me see what I can do :)
Will take me atleast a week

**Comment by Kraineff** [comment]
Thank you so much! I look forward to it!

**Comment by Kraineff** [comment]
Hi!

I don't want to rush you, but I'd love to see progress. Maybe there are a couple of screenshots :)

Thank you!

**Comment by Kraineff** [comment]
Made all assets today for drivers and main image.
![2022-03-09 22 32 47](https://user-images.githubusercontent.com/7906418/157498097-850c607c-e8e5-4a42-93d7-01c272148e5d.jpg)

**Comment by IvoDerksen** [comment]
Thanks I'll have 'em ready on friday or saturday!

**Comment by Kraineff** [comment]
Very cool! I'll be looking forward to it! Thank you!

**Comment by Kraineff** [comment]
Current Driver Folders setup for icons! Also here is a repo where you can see folders - https://github.com/Kraineff/ru.yandex.alice

Drivers:
- elari_a98 (Elari SmartBeat)
- jbl_link_music (JBL Link Music)
- jbl_link_portable (JBL Link Portable)
- lightcomm (DEXP Smartbox)
- linkplay_a98 (IRBIS A)
- prestigio_smart_mate (Prestigio Smartmate)
- wk7y (LG XBOOM AI ThinQ)
- yandexmicro (Station Lite)
- yandexmini (Station Mini)
- yandexmini_2 (Station Mini 2)
- yandexstation (Station)
- yandexstation_2 (Station Max)

**Comment by Kraineff** [comment]
That's if you decide to create folders in the current repository in the same order :)

**Comment by IvoDerksen** [comment]
Yes I do, making it a simple drag and drop. I like your enthusiasm :)

**Comment by IvoDerksen** [comment]
[yandex.zip](https://github.com/athombv/homey-vectors-public/files/8234723/yandex.zip)

Here you go!

**Comment by Kraineff** [comment]
Hi!

All the icons look amazing!!!! Finishing up one new feature for the app, namely adding other devices like outlets, remotes, and straight to the store!
All of our app tester users are loving your icons!

Big thank you!

**Comment by Kraineff** [comment]
<img width="763" alt="CleanShot 2022-03-12 at 18 52 46@2x" src="https://user-images.githubusercontent.com/7906418/158020723-931737e3-f3d7-461e-aa58-90644d11f381.png">

**Comment by Kraineff** [comment]
Really cool icons! 🤘

**Comment by IvoDerksen** [comment]
You're welcome!
