### ISSUE TITLE
Need some nice icons for the new INNR remotes

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-vectors-public#137]
Hello,

i'm updating the INNR app with the new remotes RC210 and RC250. Could you please create some nice icons?

https://www.innr.com/en/product/smart-button/

![01-RC-210-Smart-Button-Composition-pffax17h0tgb8ya9lokhxu3cw42tin7nan2xbusg68](https://user-images.githubusercontent.com/5923368/157007575-2f730b95-6555-42af-b9eb-a435e824adf8.png)

https://www.innr.com/en/product/remote-control/

![Remote RC250](https://user-images.githubusercontent.com/5923368/157007613-b53bd46c-0f76-43dc-9957-480158649ae5.png)

**Comment by IvoDerksen** [comment]
Yes! They're coming up! Friday or the weekend!

**Comment by IvoDerksen** [comment]
Hey! I've fixed the icons for the remotes, I was already busy on remodeling some stuff for the new style so I've finished them. Also including the recessed spot :)
