### ISSUE TITLE
Aeotec devices

### ISSUE THREAD

**Issue by SPAeotec** [athombv/homey-vectors-public#138]
Hi,

I need icon for any new devices.

https://trello.com/c/SgM0Iqxk/202-smart-switch-7-us-type
https://trello.com/c/Hi8rswac/237-siren-7
https://trello.com/c/INRIg71J/214-illumino-wallmote-7
https://trello.com/c/OoPX4vmO/211-illumino-dimmer-switch
https://trello.com/c/2DM2V2Cf/235-outdoor-smart-plug

Smartthings Plug Type F
![Aeotec Outlet F-GP-AEOWPFEU-White-300dpi-UpFront](https://user-images.githubusercontent.com/62385464/158143122-929a2ddc-f61f-4d54-9cc8-d8df3508ede3.jpg)

thank you for help.

Sebastian

**Comment by IvoDerksen** [comment]
Yes I will!

**Comment by IvoDerksen** [comment]
[com.aeotec.zip](https://github.com/athombv/homey-vectors-public/files/8262178/com.aeotec.zip)

Here you go Sebastian! Happy coding!
