### ISSUE TITLE
Icons For Somfy Tahoma

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#139]
Hi,
Could you make a set of nice consistent icons for the com.somfy.tahoma app please.
Let me know if you need more information and I will do my best but a lot of the drivers cover a range of devices as they are aligned to the available commands for the device.

**Comment by IvoDerksen** [comment]
Hello!

Yes I can! 
Can you provide the current store app? So I have a list of devices and are you planning on adding a new device too, if so, let me know!

Thanks!

**Comment by AdyRock** [comment]
The store entry is https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/
During the review it was suggested I ask for all the icons to be redesign so they are consistent as they have been added over the last 4 years by different devs.
Thank you for your help, it's much appreciated.

**Comment by IvoDerksen** [comment]
Hey! Just a headsup! I've gone through a lot of them, but I've underestimated the amount of devices. I hope to finish them up next week!

**Comment by IvoDerksen** [comment]
Almost... ready... still.... underestimated.... work :)

**Comment by IvoDerksen** [comment]
Do you have a repo (only if it is public, but I can imagine it is not) or can you send me the driver names (folders in drivers) so I can help make it drag and droppable for you? Saves us both some work :)

**Comment by AdyRock** [comment]
I must admit I was surprised when Merel suggested to redo all the icons.
The repo is public https://github.com/AdyRock/com.somfy.tahoma

**Comment by IvoDerksen** [comment]
Ady Excuse the wait, here you go!
[com.somfy.tahoma.zip](https://github.com/athombv/homey-vectors-public/files/8589814/com.somfy.tahoma.zip)
.

**Comment by AdyRock** [comment]
I have been away so only just got to look at the zip file. Thank you for doing all those, but I see that there are a lot of png files instead of svg files. Can I use those in a driver as I thought they had to be svg?

**Comment by IvoDerksen** [comment]
No!
Sorry I exported in the default format! SVGs now
[com.somfy.tahoma.zip](https://github.com/athombv/homey-vectors-public/files/8598833/com.somfy.tahoma.zip)
!

**Comment by AdyRock** [comment]
Perfect, thank you for a lot of work. They look great!

**Comment by IvoDerksen** [comment]
You are welcome!
Thank you for the app :)
