### ISSUE TITLE
com.jilles.proliphix

### ISSUE THREAD

**Issue by nattlip** [athombv/homey-vectors-public#14]
![large](https://user-images.githubusercontent.com/7040452/31863874-31bcb3fa-b754-11e7-9a98-4dcf085ae685.jpg)

![large](https://user-images.githubusercontent.com/7040452/31863876-3aed4002-b754-11e7-8ea8-9c09e2372712.jpg)

**Comment by IvoDerksen** [comment]
Here you go! Good luck on completing the app!
