### ISSUE TITLE
nl.scanno.mqttbroker

### ISSUE THREAD

**Issue by scanno** [athombv/homey-vectors-public#141]
Hi,

Since Athom rejected an update of the mqtt broker app due to the icons not being occording yo updated store policy, I would like to ask you to create icons for me. Especially now that with the new firmware update the broker does not start anymore and the fixed version is in test for a long time now.

**Comment by IvoDerksen** [comment]
No problem!
Ill get to it asap!

**Comment by scanno** [comment]
> No problem! Ill get to it asap!

Thanks

**Comment by IvoDerksen** [comment]
Something like this?
The MQTT Logo
