### ISSUE TITLE
New device icon for com.somfy.tahoma

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#142]
Hi could you create an icon for a new Tahoma device please:
![large](https://user-images.githubusercontent.com/38184396/169912782-c4393504-253f-4200-bff6-18a5c4062a4b.png)
It's a thermostat for underfloor heating.

Thank you.

**Comment by AdyRock** [comment]
And could you create an icon for an EV charger for the same app please.

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
can you ellaborate on the EV charger? Is it generic or?

**Comment by AdyRock** [comment]
Yes it will be generic

**Comment by AdyRock** [comment]
Thank you for the thermostat icon, much appreciated
