### ISSUE TITLE
Icons for Dom.ru

### ISSUE THREAD

**Issue by Kraineff** [athombv/homey-vectors-public#143]
Hi!

It so happened that the integration Dom.ru released in the store (https://homey.app/ru-ru/app/ru.dom.smart) earlier than the integration of Yandex Alice with your beautiful icons, so I would like to ask you to draw 2 more cool icons for the new application!

I need an icon for Beware made Intercom:
![large](https://user-images.githubusercontent.com/7906418/169965182-b93b79d2-f405-4343-a9d2-dbf3e2ecf2eb.jpg)
![99be6b0c-4bfb-48bc-b72f-a5d74e846818_jpg_800x1000_q85](https://user-images.githubusercontent.com/7906418/169965452-36099ca1-44a2-44b2-8694-eb244955023e.jpg)

And one icon for camera device, Dom.ru don't have own camera so it can be any generic camera like this for example:
![1337842183_8756](https://user-images.githubusercontent.com/7906418/169965891-141a77a5-7eb4-453a-98cb-67f09d86f333.jpg)

Thank you!

**Comment by IvoDerksen** [comment]
Will do!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by Kraineff** [comment]
Thank you! There are just awesome! Looking forward to make the update tomorrow!
