### ISSUE TITLE
it.vimar

### ISSUE THREAD

**Issue by Abo89** [athombv/homey-vectors-public#146]
Hello Athom Teams,
I'm developing an app for administering the IoT zigbee device from Vimar
https://www.vimar.com/
Can you please help me to develop an Icon for the app?
for now it has only 2 devices
1 wall switch (i need an icon for that as well) https://www.vimar.com/en/int/catalog/product/index/code/20592.0
1 roller shutter (i need an icon for that as well) https://www.vimar.com/en/int/catalog/product/index/code/20594.0

Thanks for your help.

**Comment by IvoDerksen** [comment]
Yes! Let me have a look :)

**Comment by IvoDerksen** [comment]
Here you go, I've made the buttons as buttons instead of modules. and the icon of the company in a one color version, but it is unofficial. If they ask to change it let me know :)
