### ISSUE TITLE
com.toshiba logo+icon

### ISSUE THREAD

**Issue by mjilesen** [athombv/homey-vectors-public#148]
Hi Ivo,

Can you create logo icon for me and and airco image? I have included the logo. I guess you already have some picture of an airco unit somewhere (but I couldn't find it).

Thx,
Monique

<img width="1152" alt="Toshiba app logo" src="https://user-images.githubusercontent.com/56786010/178478528-4bb8b2c4-c321-4cdb-8de7-1b648bdcd938.png">

**Comment by IvoDerksen** [comment]
Hey! I will!
