### ISSUE TITLE
com.philio PAN16-1

### ISSUE THREAD

**Issue by jolny** [athombv/homey-vectors-public#15]
Hello!
PAN16-1 in the app com.philio needs svg files ('learnmode.svg' and 'icon.svg').
App link: https://apps.athom.com/app/com.philio
Image link: https://github.com/Inversion-NL/com.philio/blob/master/drivers/PAN16-1/assets/images/large.png

Thank you :)

**Comment by IvoDerksen** [comment]
Hi there! The icons are done already!
Good luck on completion. For completeness I've named them according to their device names, in the com.philip-tech folder, which can be found using my commit!

**Comment by jolny** [comment]
Wow! That was fast. Thank you! :smiley:
