### ISSUE TITLE
com.switchbot

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#150]
Hi,
Could you create an icon for the SwitchBot lock for me please:
![large](https://user-images.githubusercontent.com/38184396/180808079-751d2504-301d-46f8-a97a-ee950ea5698f.jpg)

https://github.com/AdyRock/com.switchbot/tree/master/drivers/lock_hub/assets

Many thanks for your support,
Adrian.

**Comment by IvoDerksen** [comment]
Ofcourse!

**Comment by IvoDerksen** [comment]
> Would it be OK if I steal the svg for the light strip for the SwitchBot app, as I used a stock image for that and I'm sure yours will look a lot nicer. Plus consistency in Homey ;-) 

You mean for this app?

**Comment by IvoDerksen** [comment]
[com.switchbot.zip](https://github.com/athombv/homey-vectors-public/files/9237437/com.switchbot.zip)
 
Here you go!

**Comment by AdyRock** [comment]
Perfect, thank you.
