### ISSUE TITLE
SMA device icons

### ISSUE THREAD

**Issue by ricott** [athombv/homey-vectors-public#153]
Hi,

May I request new device icons for the `sma.modbus` app.
* Energy meter
Typically P1 meter, but could also be placed to only measure input/output from energy system (inverter/battery). [Example](https://www.sma.de/en/products/monitoring-control/sunny-home-manager-20.html)

* Inverter
Solar inverter, lots of different models. [Example](https://www.sma.de/en/products/solarinverters/sunny-tripower-15000tl-20000tl-25000tl.html)

* Sunny Boy Storage
Battery inverter, [example](https://www.sma.de/en/products/battery-inverters/sunny-boy-storage-37-50-60.html)

* PVOutput.org
Virtual device to send energy statistics to [pvoutput.org](https://pvoutput.org/)

* Energy Summary
A virtual device that summarizes your SMA inverters and energy meter in one device.

Best,
Richard

**Comment by IvoDerksen** [comment]
Yes I will, it can be end of this week!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by ricott** [comment]
Smokin' 😍

**Comment by IvoDerksen** [comment]
Thaaanks man!
