### ISSUE TITLE
com.smappee

### ISSUE THREAD

**Issue by edwinvdpol** [athombv/homey-vectors-public#155]
Hi, can you please create a vector for the 6 devices below?

Would be cool if the Smappee logo's in the center of the EV charging stations are visible.
The name of the devices are above each image.

Much appreciated!

---
### Gas & Water
![Smappee Gas   Water](https://user-images.githubusercontent.com/9265514/189545127-45630770-578f-48cd-a33d-9ac5ccbd7926.png)

---
### Genius
![Smappee Genius](https://user-images.githubusercontent.com/9265514/189545162-461df05b-86ff-441d-bdc9-4be59a3ae23f.png)

---
### Switch
![Smappee Switch](https://user-images.githubusercontent.com/9265514/189545193-d1ae3b0b-0db4-4d84-b88d-672402bbedc4.png)

---
### EV Base
![Smappee EV Base](https://user-images.githubusercontent.com/9265514/189545204-956d9cac-6a28-4118-90c7-fb8bfdb563fd.png)

---
### EV Base Ultra
![Smappee EV Base Ultra](https://user-images.githubusercontent.com/9265514/189545221-3527584f-22d5-4a82-9156-5b16bb2c3ae0.png)

---
### EV Wall
![Smappee EV Wall](https://user-images.githubusercontent.com/9265514/189545237-6da03a20-c79a-4687-9bc6-b9e12392f20e.png)

**Comment by IvoDerksen** [comment]
Yes! Let me have a look! It will take a week or so due to the amount of icons :)

**Comment by edwinvdpol** [comment]
No problem, no rush. Thanks in advance!

**Comment by edwinvdpol** [comment]
Thank you @IvoDerksen for you time and effort!

**Comment by IvoDerksen** [comment]
Wow your quick!
I wanted to say here you go! :) 
good luck on completing the app! Love this stuff!

**Comment by edwinvdpol** [comment]
@IvoDerksen If you have the time, can you also create icons for the following Smappee devices, please?

Thanks in advance!

---
**Smappee Energy**
![Smappee Energy](https://github.com/athombv/homey-vectors-public/assets/9265514/ff101550-528e-4d32-9923-dab825178d3b)

---
**Smappee Plus**
![Smappee Plus](https://github.com/athombv/homey-vectors-public/assets/9265514/ba88a5b7-116a-49bc-bcd1-ecaac9da9503)
