### ISSUE TITLE
Images and icons for com.ostberg.heru

### ISSUE THREAD

**Issue by henrikjonhed** [athombv/homey-vectors-public#157]
Hi!

Could you help out with creating app icon and images for https://ostberg.com

and device icon and images for their ventilation unit called "[Heru](https://fsp.ostberg.com/products/4348/heru-160-t-ec)": https://fsp.ostberg.com/uploads/Product%20pictures/HERU_T_EC/heru_160TEC_y1_RE_01_web.jpg

**Comment by IvoDerksen** [comment]
Yes no problem

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by henrikjonhed** [comment]
Thanks a lot @IvoDerksen!
