### ISSUE TITLE
nl.qluster-it.DeviceCapabilities

### ISSUE THREAD

**Issue by XeroxQ** [athombv/homey-vectors-public#159]
Hey,

I would love as much .svg as i can get, for the virtual devices with custom icons and custom icons for the capabilities.

There are currently 80 slots for capabilities.
The slots for those icons can be filled, just like device icons, with a set of default icons.

This Defaults Icon set can/should be as "large as possible".
![image](https://user-images.githubusercontent.com/43435060/191249468-f95e97e4-3b49-4d78-acd6-d4ca556b21d4.png)

**So any icons i can used would be great!** Because i currently don't have that many.

P.s. I allready have it packed into one compressed file to save App Install time (and not have to install hundreds of icons every time).

**Comment by XeroxQ** [comment]
Is there any response?

**Comment by XeroxQ** [comment]
It's for the Advanced Virtual Devices from Device Capabilities, for which people can set there own custom icons for devices and for capabilities.

Thats why i would love more icons for it, that reflect Homey icons.

**Comment by IvoDerksen** [comment]
Hey!

Let me check first, as far as I know it is not policy to provide all capability icons to external.

Like the idea though!

I'll get back at you!

**Comment by XeroxQ** [comment]
Thanks, but I don't need the real default capability icons.
Users can allready select all default capabilities (and not set a custom icon for it) and the will get the default capability icon.

But the can also set 80 custom capability icons (to set as icon for a capability).
And those 80 "slots" can be filled with a large list of default icons:
Here an image of the 80 slots:
![image](https://user-images.githubusercontent.com/43435060/192359248-ad56805d-b8ed-412d-9b29-e4c2a9d91308.png)

When you push the magnifying glass, you get all default images i currently have (not many):
![image](https://user-images.githubusercontent.com/43435060/192359352-c4921b9e-0324-4b62-89ef-f026e380ba73.png)

What i would like, is as many svg's i can get from athom, that i can add to the default icon list.
So users can really customise it like crazy.

:)
And the icons are shared to other users, so the more good icons, the beter.

**Comment by IvoDerksen** [comment]
My own svg repo is not as handy as I thought. I am working on a community set.

**Comment by XeroxQ** [comment]
What do you mean?
You have a community set (then) that i may include in my app?

**Comment by IvoDerksen** [comment]
Kinda, I'm collecting then for you :)

So you'll get a set yes!

**Comment by XeroxQ** [comment]
Great!

Well, i don't know how you implement the icons on the Homeys, but you are free to use my sourcecode and method for it ;)
It saves install time and space, very much, and handy during development, but since you need a compressed file which is uncompressed on Homey after install, in total, it cost more space.
But it doesn't require a npm package or anything.

**Comment by XeroxQ** [comment]
And looking forward to it!
I hope they are just as nice as all Homey icons ! ;)

**Comment by XeroxQ** [comment]
In case you do wanna use the compressed way, i just turned the compressed file in a zipped to further reduce the mainpackage from 432kB to 317kB, while the actual size is 699kB (on my disc 1,01MB).

**Comment by IvoDerksen** [comment]
[assorti.zip](https://github.com/athombv/homey-vectors-public/files/9739718/assorti.zip)

Hey here you go!

**Comment by XeroxQ** [comment]
Thanks m8, i'll implement it.
But it looks like the new Homey Pro will not support this app and its custom icons.

**Comment by IvoDerksen** [comment]
Hey! I hope it does or Athom finds a way to make it possible in another way :)
