### ISSUE TITLE
net.pelliniscreenline

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-vectors-public#16]
Hey Ivo, 

I want an SVG for the remote of a Screenline Windows Blinds (functional equal to Brell)

it is this remote: 
http://www.pellinishop.net/en/w-system-battery/56-radiocomando-99-canali-per-sistema-f-screenline-pellini.html

![image](https://user-images.githubusercontent.com/12412734/32299706-daafd776-bf56-11e7-8cb7-d5dc5d3d67c9.png)

the small buttons below the display are - and + 
only Up and Down emit a radio signal. 
the 3rd button (lowest) is Reset Channel. 

This is a screenshot from the manual you can download in the link above:
![image](https://user-images.githubusercontent.com/12412734/32299947-bad4e85a-bf57-11e7-907c-b965b407c7e7.png)

**Comment by IvoDerksen** [comment]
I've added the icons and an app icon / logo of ScreenLine
If you need animations, please feel free to reopen the issue and tell me what I can animate!

Kind regards and good luck on completing the app!
