### ISSUE TITLE
Ring Glass Break Sensor

### ISSUE THREAD

**Issue by daneedk** [athombv/homey-vectors-public#165]
Hi Ivo,

Can you create an icon for the Ring Glass Break Sensor?

![ACC_Bear_ATF_dotcom_front_wall_1280x1280_ca2372ac-843a-4a62-b9b5-62cff116c9f0_2000x2000](https://user-images.githubusercontent.com/16610696/193794460-75476039-b644-4543-8601-010a7b7807f1.png)

Thanks!

**Comment by IvoDerksen** [comment]
Hey! Yes to all you issues! Will get to it this week :)

**Comment by IvoDerksen** [comment]
[com.ring.zip](https://github.com/athombv/homey-vectors-public/files/9739550/com.ring.zip)

**Comment by IvoDerksen** [comment]
Here you go, for all of your 4 commits

**Comment by IvoDerksen** [comment]
I've also posted them to the repo, but the folder above is the same :)

**Comment by daneedk** [comment]
Thanks @IvoDerksen!

**Comment by daneedk** [comment]
Hi Ivo,

Sorry to bother you again, but these new icons, while displaying correctly in the Homey app, do not show up correctly on the homey.app website:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/16610696/194750974-97594c2b-2a83-4994-9141-248102b5d8da.png">

Screenshot taken from this link: https://homey.app/nl-nl/app/com.ring.security/Ring-Security/test/

Cheers,

Danee

**Comment by IvoDerksen** [comment]
Thanks Dane, let me check with someone from Homey!
It works in the app, so it should work in their image conversions, but it seems it doesn't.
