### ISSUE TITLE
no.ensy

### ISSUE THREAD

**Issue by palsivertsen** [athombv/homey-vectors-public#167]
I'm developing an app for Ensy home environment units (air conditioning like units). Can someone please help me with some driver icons?

The unit haas a weird look since it's ment to be partly covered. Here are some picures:
![image](https://user-images.githubusercontent.com/11890143/198884928-0ce292cb-f1ad-43e9-a3f9-8161fef8b074.png)
![IMG_20221030_154813__01](https://user-images.githubusercontent.com/11890143/198885209-21218d84-4837-4a12-9983-a4e877b794b9.jpg)
![IMG_20221030_154821__01](https://user-images.githubusercontent.com/11890143/198885212-8b52d617-6dd4-4d11-8d1a-68695a0de121.jpg)
![IMG_20221030_154827__01](https://user-images.githubusercontent.com/11890143/198885215-836ddb8c-b1d1-493c-93e0-e3066469ff5d.jpg)

**Comment by IvoDerksen** [comment]
Yes! Let me have a look coming week!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by palsivertsen** [comment]
Thank you!
