### ISSUE TITLE
no.tjweb.smartcharging

### ISSUE THREAD

**Issue by thorleifjacobsen** [athombv/homey-vectors-public#168]
Hi

I would love to have this as a ICON for the app. But my SVG skills are not there. If anyone could do this I would be very happy.

![image](https://user-images.githubusercontent.com/8550684/201745851-485cb82b-83c7-4ddd-975a-a436e5f15dd2.png)

**Comment by IvoDerksen** [comment]
Hey!

I can not receate this, but I can make my / a homey version!

Gimme a few days!

Kind regards!

**Comment by IvoDerksen** [comment]
[no.tjweb.smartcharging.zip](https://github.com/athombv/homey-vectors-public/files/10050876/no.tjweb.smartcharging.zip)

Anything you like?
I like the first one!

**Comment by IvoDerksen** [comment]
Hey! You like?

**Comment by thorleifjacobsen** [comment]
Hey, sorry. I've been a gone a bit. I love the first aswell! Thanks a lot @IvoDerksen !! :)

**Comment by IvoDerksen** [comment]
Thanks!
Great to hear!
I'll close the issue and you combine my two fields of interests with this app :)
