### ISSUE TITLE
Device Icons for ady.solarman

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#170]
Hi,

Could you make some nice icons for the new SoFar / Solarman app please.
The repo is https://github.com/AdyRock/ady.solarman/tree/master

Thank you.

**Comment by IvoDerksen** [comment]
Ofcourse!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by AdyRock** [comment]
Thank you. Look lovely as usual.
