### ISSUE TITLE
New Misol device

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#172]
Hi,

Could you update the icon at https://github.com/AdyRock/com.misol/tree/a8e4d822c995038af7b88e8de0cbd74d62442c02/drivers/Temp_Water/assets so it shows it is a water temperature measuring device. The one that is there is copied from the Temperature and Humidity device just so I can test the ne device.

**Comment by AdyRock** [comment]
I just realised I copied the Temp driver icon and not the Temp_Hum driver icon as reported in the previous post, so hope that didn't confuse matters.

**Comment by IvoDerksen** [comment]
Ivo hurts himself in confusing, haha. Do you want just a water temperature icon?

Temperature and humidity together would not be handy, as I would expect you to split them in two data capabilities right?
Or am I wrong?

**Comment by AdyRock** [comment]
:-) Correct, I just want a water temperature icon for the device. So just ignore my other rambling.

**Comment by IvoDerksen** [comment]
Here you go!
