### ISSUE TITLE
TP-Link KP303

### ISSUE THREAD

**Issue by LRuesink-WebArray** [athombv/homey-vectors-public#173]
Hi, could you make a vector image for the following?

![large](https://user-images.githubusercontent.com/65756537/210977246-1da0bc39-aa9c-4357-9aea-acb892a9ced6.png)

It's for com.tplink.kasa.

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by Dijker** [comment]
Hi Lex, 
Where can I contact you? 
Maybe teh Community forum ?
https://community.homey.app/u/dijker/summary

**Comment by LRuesink-WebArray** [comment]
> Hi Lex, Where can I contact you? Maybe teh Community forum ? https://community.homey.app/u/dijker/summary

I have a profile on the community now where you could reach me.
