### ISSUE TITLE
SwitchBot Blind Tilt

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#174]
Hi Ivo,

Could you provide an icon for this new device please:
https://github.com/AdyRock/com.switchbot/tree/master/drivers/blind_tilt_hub/assets

The jpg images are up to date to give you an idea of the devices appearance.

Thank you for your support.

**Comment by IvoDerksen** [comment]
Yes I can and yes I will!

**Comment by IvoDerksen** [comment]
Here you go!
