### ISSUE TITLE
com.lixee Zlinky

### ISSUE THREAD

**Issue by mathieuChamois** [athombv/homey-vectors-public#175]
Hi, i have create my own SVG for Zlinky into my app Lixee but i'm not really a designer 😄 
is it possible to create a better SVG for this device please  ?

![zigate-usb-ttl](https://user-images.githubusercontent.com/14921914/212770173-4a8c3a5e-35c9-46b8-9e8f-3c6bb0f9f5c3.jpeg)

![zigate-usb-ttl_2](https://user-images.githubusercontent.com/14921914/212770189-f27474a9-05dd-4622-8dd5-597787c08bcc.jpeg)

![zigate-usb-ttl_3](https://user-images.githubusercontent.com/14921914/212770195-2c8de743-4ccc-43a9-8e5c-1019a1a48f4e.jpeg)

**Comment by IvoDerksen** [comment]
Here you go!
