### ISSUE TITLE
com.home-connect cleaning robot and warming drawer

### ISSUE THREAD

**Issue by mijgame** [athombv/homey-vectors-public#178]
Hi!

Could you make an .svg for the cleaning robot and warming drawer? Thanks!
<img width="500" alt="Robotstofzuiger" src="https://user-images.githubusercontent.com/8114544/217055508-e69d88a4-f144-425f-af18-a075fb708810.png">

<img width="500" alt="Warmhoudlade" src="https://user-images.githubusercontent.com/8114544/217056168-d53059ec-f8c1-4596-bba3-7f0c57b32fd4.png">

**Comment by IvoDerksen** [comment]
Ofcourse!

**Comment by IvoDerksen** [comment]
Forgot the warming drawer
