### ISSUE TITLE
com.fibaro

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-vectors-public#18]
Would like new SVG icons for the Fibaro Thermostat Valve

**Comment by IvoDerksen** [comment]
Hey Marco, 

Robin has already created an issue from Homey internal.
It is enclosed in this issue as well, but we are also working on it!

Kind regards!
Ivo

**Comment by mruiter** [comment]
Ok, then i will use my new driver with a smiley icon until they publish the athom version ;)
