### ISSUE TITLE
Aeotec Smart Outdoor Plug and Z-Stick Gen5

### ISSUE THREAD

**Issue by SPAeotec** [athombv/homey-vectors-public#180]
Hi,

I need an icon for Aeotec Smart Outdoor Plug and Z-Stick.

https://trello.com/c/2DM2V2Cf/235-outdoor-smart-plug
https://trello.com/c/IZCB61I0/113-z-stick

Thank'

cheers 
Sebastian

**Comment by IvoDerksen** [comment]
Coming right up! Probably this weekend!

**Comment by IvoDerksen** [comment]
Here you go Sebastian!
