### ISSUE TITLE
com.zaptec

### ISSUE THREAD

**Issue by PatrickE94** [athombv/homey-vectors-public#181]
Hi,

I could use some neat icons for the Zaptec products,

* [Zaptec Go](https://cdn.shopify.com/s/files/1/0518/9071/6865/products/zaptec-go-rock-grey_d4312984-dc06-4d1d-9f1f-13c2c917d5ed.png?v=1616051048)
* [Zaptec Sense](https://cdn.shopify.com/s/files/1/0518/9071/6865/products/ZaptecSense_View08_R01_dyp_8415471c-cbfb-4947-bfd8-3f4d469579fd.png?v=1676638713)

If you need better pictures, there's  a whole lot on [their webpage](https://shop.zaptec.com/tilbehor).

**Comment by IvoDerksen** [comment]
Hey here you go!

**Comment by PatrickE94** [comment]
Impressive feat! Many thanks!
