### ISSUE TITLE
Ring Chime

### ISSUE THREAD

**Issue by daneedk** [athombv/homey-vectors-public#182]
Hi Ivo,

Can you create an icon for the Ring  Chime, thanks!
![Chime 1024x1024](https://user-images.githubusercontent.com/16610696/229305071-7f8da488-9465-43ee-9ec4-6824648da0d1.png)

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
X3 :D

**Comment by daneedk** [comment]
Thanks Ivo, that was fast 🙂
