### ISSUE TITLE
Ring Stick Up Cam

### ISSUE THREAD

**Issue by daneedk** [athombv/homey-vectors-public#184]
Hi Ivo,

Can you create an icon for the Ring Stick Up Cam, Thanks!
![Stick Up Cam 2000x2000](https://user-images.githubusercontent.com/16610696/229305121-5be94060-5fc0-4840-a783-bb84972f18e6.png)

**Comment by IvoDerksen** [comment]
https://github.com/athombv/homey-vectors-public/commit/f578e746b5e92729c823ba2936f1d123520d8750

**Comment by IvoDerksen** [comment]
minor update in the above commit!
