### ISSUE TITLE
se.pax.calima

### ISSUE THREAD

**Issue by christian-ek** [athombv/homey-vectors-public#185]
Hi,
I am creating an app for the Pax Calima fan.
Could you help me create an icon for it?

https://pax.se/produkter/ventilation/badrumsflaktar/calima/1550-1

![Image Bathroom fan Front](https://user-images.githubusercontent.com/25098185/229746597-fffdeb97-caa8-42ff-92f3-f9a19d73ac0c.png)

**Comment by IvoDerksen** [comment]
Ofcourse

**Comment by christian-ek** [comment]
This pdf might be of some help.

https://pax.se/storage/AF9E205A062BADEB67348AA4E3CE271B5AFCA45DBDD155958C2786F8E4F2BF4B/5251cd4bdd5d4479bf7d74f7ce0ba789/pdf/media/244c560a39604de4b3b50ff0e61b7e19/Pax%20Calima%20folder.pdf

**Comment by IvoDerksen** [comment]
Do you also need a pair icon?

**Comment by christian-ek** [comment]
I need an icon for the device which I guess also is shown while pairing :)

**Comment by IvoDerksen** [comment]
It can, but it is not necessary. If you need to press an icon we'd often suggest to create an addition pair icon. Otherwise an instruction will do :)

Here you go!

**Comment by christian-ek** [comment]
Nice job, thank you :)
