### ISSUE TITLE
eu.blebox

### ISSUE THREAD

**Issue by Piotr-Grochowski** [athombv/homey-vectors-public#186]
Hello,
I need an icon for custom capability "Heat Index". As Heat index combines temperature and humidity into one value, the icon could also be a combination of the temperature and humidity icons. You can also see the icon for heat index in original BleBox application - the screenshot is on this page: https://blebox.eu/en/product/humiditysensor/ (scroll down to paragraph MULTI-PARAMETER INDICATOR!).

**Comment by IvoDerksen** [comment]
[heat index.zip](https://github.com/athombv/homey-vectors-public/files/11256088/heat.index.zip)
One of these should do!

**Comment by Piotr-Grochowski** [comment]
Thanks! They look great. I've chosen heat_index_3.svg

**Comment by IvoDerksen** [comment]
You're welcome!
