### ISSUE TITLE
com.groups

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#189]
Hey, 

Sorry for all the requests at once, but i've been saving them up. 

I am looking to add device icons for the three types of advance devices in the group app, I was hoping these could just look like the standard icons I already use for the names which are generic emoji. 

Clone Group : ⛓️ 
Fused Group : 🔗 
United Group : 📎 
Capacity Group : 🖇️ 
Blended Group: 🧷 

Thanks very much and let me know if there is anything else I can do?

**Comment by IvoDerksen** [comment]
No biggie :)

So if I'm correct you want to have the emoji's as base for the type of group (and the group is a device icon).

I can do that, let's keep em consistent then :)

**Comment by hive** [comment]
Sorry I didnt realise that there was a question. 

So there are groups for each type of device.class - which you created the awesome. 

But there are now 5 types of 'advance' groups, which mix and match devices which are all different types of classes (ie a group with a sensor a light and a door handle). 

Thats what the new icons are for, I think it has a consistent look as well.

**Comment by hive** [comment]
Hey Ivo, curious as to whether there is an ETA on these,  just looking to self organise my self. 

Thanks

**Comment by IvoDerksen** [comment]
Hey Jamie, yes I was planning on yesterday, but I didn't make it.
Will be this morning, or Monday!

**Comment by IvoDerksen** [comment]
it is the first, not the latter ;)
