### ISSUE TITLE
eu.duco

### ISSUE THREAD

**Issue by woudt** [athombv/homey-vectors-public#190]
Hi,

I'd like to request some icons for DucoBox devices.

Specifically:

1. DucoBox Silent/Focus

front view: https://www.duco.eu/Wes/CDN/1/Cms/ImagelistImages/DucoBox_Silent_5.jpg
side view: https://www.duco.eu/Wes/CDN/1/Products/ProductImages/2021-01-26%2016.25.29.277%20-%20DucoBox-Silent.png

2. DucoBox Energy Comfort

front view: https://i.ytimg.com/vi/-r4xS5CB3FM/maxresdefault.jpg
side view: https://www.duco.eu/Wes/CDN/1/Attachments/DucoBox-Energy-Comfort-D400_637922612430900734.jpeg

Note: this one comes in different sizes. The one on the side view corresponds to the second one on the front view. One size is sufficient.

3. DucoBox Energy Premium

front view: https://www.ventilatieland.nl/resize/ducoboxenergyrechtsvooraanzicht_3182511345347.png/500/500/True/ducobox-energy-wtw-rechts.webp
side view: https://www.duco.eu/Wes/CDN/1/Products/ProductImages/2021-02-15%2008.20.52.855%20-%20DucoBox-Energy-Premium.jpg

4. DucoBox Sensor

front view: https://i0.wp.com/bouwshop-twente.nl/wp-content/uploads/2019/12/4.1.1-Bedieningsschakelaar.png
side view: https://www.duco.eu/Areas/Website/UploadData/1/TinyMce/bedieningen-zwart-wit-v2.jpg

Thanks a lot!

Edwin

**Comment by IvoDerksen** [comment]
Hey Edwin, sorry it took me a while! Here you go!
