### ISSUE TITLE
io.olae.dirigera

### ISSUE THREAD

**Issue by olaeriksson** [athombv/homey-vectors-public#191]
I need a device icon and some pairing icons for the IKEA Dirigera gateway.

Device icon:
![image](https://user-images.githubusercontent.com/29456953/233981619-4f73fb36-d2fa-4120-8017-4ced6e333d97.png)
![image](https://user-images.githubusercontent.com/29456953/233981643-e5fa07d0-6eed-4637-b25a-c68be89105c3.png)

Pairing
During the pairing process, the user is required to press a button on the back of the dirigera device in order to authenticate.
Would be great if we could have an animated icon that demonstrates pushing the action-button as seen in this image:
![image](https://user-images.githubusercontent.com/29456953/233982182-feef8362-09ad-40a1-8b27-52c261314758.png)

Thanks a bunch!

**Comment by IvoDerksen** [comment]
Sure!
Lettme have at it!
I see what you mean!

**Comment by olaeriksson** [comment]
Thank you, I appreciate it!

**Comment by IvoDerksen** [comment]
Here you go!
