### ISSUE TITLE
brandweerrooster.nl

### ISSUE THREAD

**Issue by mickelluiten** [athombv/homey-vectors-public#192]
brandweerrooster.nl

PLease convert attached image to svg for the upcoming app brandweerrooster.

THanks in advance.

![4923429ec4cc874b57b82b7b6a1661b4_400x400 (1)](https://user-images.githubusercontent.com/26140350/236837914-46e8d3a0-349a-4c81-8e63-5fb05798dc37.png)

**Comment by IvoDerksen** [comment]
sure!

**Comment by IvoDerksen** [comment]
Here you go!
