### ISSUE TITLE
Glowmarkt smart meter app

### ISSUE THREAD

**Issue by jmdraper** [athombv/homey-vectors-public#193]
Hi

Please could I get 1 x app icon and 1 x driver icon made up for my new app which will connect to UK smart meters using a device made by Glowmarkt?

The app icon should be based on the Glowmarkt logo which looks like this:
![f0828c96479d43baf85211c4088b6e4e](https://github.com/athombv/homey-vectors-public/assets/20240325/7cb66adb-3da0-4ef2-a01d-ad066463d803)

And the driver image should look like the meter display device which is:
![image_1024x1024](https://github.com/athombv/homey-vectors-public/assets/20240325/fe94a655-a0b9-4609-b49e-33dba8aeb88c)

Thanks in advance!

Jon

**Comment by IvoDerksen** [comment]
Here you go!
