### ISSUE TITLE
io.everythingsmart

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey-vectors-public#194]
Hi Ivo,

I'd like to request an app and driver icon based on the following:
- App icon: https://cdn.shopify.com/s/files/1/0622/2512/1477/files/EST_Compact_Logo_39a737b5-afce-4e67-9a42-db994df3e7d2.png?v=1666001871&width=500
- Driver icon: https://cdn.shopify.com/s/files/1/0622/2512/1477/products/everythingsmartmotion-1_7a0af72b-7b20-46ed-968e-0457baa454ce.png?v=1663787485&width=2048

Thanks!

**Comment by IvoDerksen** [comment]
Ofcourse!
