### ISSUE TITLE
Media Control Icons

### ISSUE THREAD

**Issue by kraineff** [athombv/homey-vectors-public#195]
Hello! Can you please make a new icon set for TV media control buttons, or align current one. Now some icons are different in thickness and size, and I also tried to find a visual center for each icon, but I don't know if it's the right one.

Oh and also I found that like, home icons vectors left side and right side not the same mirrored.
And I need a dislike icon.

Thank you! :)

<img width="332" alt="Safari 7J7VMrYB" src="https://github.com/athombv/homey-vectors-public/assets/7906418/8343fabf-2477-4c80-bc2c-8ca484bb7006">

**Comment by Kraineff** [comment]
![media_back](https://github.com/athombv/homey-vectors-public/assets/7906418/77d04025-c2cd-4cdb-8fdf-a0068988ead6)
![media_down](https://github.com/athombv/homey-vectors-public/assets/7906418/5ed97aff-a2d7-4505-a63a-3bfa43a42b95)
![media_home](https://github.com/athombv/homey-vectors-public/assets/7906418/9f51da95-56dd-48eb-bf85-b2df2d981c84)
![media_left](https://github.com/athombv/homey-vectors-public/assets/7906418/70fad87b-ac1e-4a66-8b15-702ab7aaf767)
![media_like](https://github.com/athombv/homey-vectors-public/assets/7906418/9b875cec-6499-4975-a069-95d739782fe6)
![media_power](https://github.com/athombv/homey-vectors-public/assets/7906418/6fdc1fbe-a4b2-4988-912e-718779b524b0)
![media_right](https://github.com/athombv/homey-vectors-public/assets/7906418/48bde0c5-d42e-4e52-a3bf-05ed5459ea91)
![media_up](https://github.com/athombv/homey-vectors-public/assets/7906418/0789d0bf-0169-49b8-8f09-2b937988b319)

**Comment by Kraineff** [comment]
For “ru.yandex” app

**Comment by IvoDerksen** [comment]
Hey!
I can take a look for sure :) You've done a good job already though!

**Comment by Kraineff** [comment]
Thank you! :)

**Comment by kraineff** [comment]
Looks Amazing! Thank you so much!
