### ISSUE TITLE
nl.robinflikkema.rluxtronik

### ISSUE THREAD

**Issue by RobinFlikkema** [athombv/homey-vectors-public#198]
Hi, for a new app I am planning on releasing soon I am in need of a icons. The github repo is currently private until I have figured out everything for release 1.0.0

# Driver Icon
This is a heatpump, so it is a large device (the large model is 2 meters). I have attached pictures below.

This is a picture an example heatpump:
![17](https://github.com/athombv/homey-vectors-public/assets/4777401/ded5c078-7726-4d86-b18d-0f029c4da98d)

Below you can see the three heatpump on the left. Those are "3d" so you get an idea what it is about.
![alpha-innotec-sfeer-1](https://github.com/athombv/homey-vectors-public/assets/4777401/8929636d-e5dc-4e0e-b224-077c17854762)

This is what I had in my head:
![Untitled](https://github.com/athombv/homey-vectors-public/assets/4777401/120e13a5-aef9-4016-86bc-a525b26e8604)

# App Icon
As the App is currently named "Luxtronik", i though about just putting the name in the app icon, or making the app icon the controller itself.
FYI: Luxtronik is the name of the controller multiple heatpump manufacurers use.

See below the images of the controller (front view)
![Bild1](https://github.com/athombv/homey-vectors-public/assets/4777401/44d43c02-5657-4678-9d19-ecbbc19fe224)
![14-1 (1)](https://github.com/athombv/homey-vectors-public/assets/4777401/3f0ace0e-b5f3-4f1e-ac52-77cd4fd8cae3)

This is what I had in my head:
![Bild2](https://github.com/athombv/homey-vectors-public/assets/4777401/b532eb02-4c0e-4929-b153-17d9164e66b1)

Ofcourse, feel free to adapt or ask questions

Robin

**Comment by IvoDerksen** [comment]
Hi! 
I've provided you three options for an app icon!
Based on the module, but not as you suggested in fully (a minimalist approach)

I hope you like em and can chose one!
