### ISSUE TITLE
com.doorbird

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#2]
I would like to have proper vector images for the Doorbird IP Video Station.

App icon: https://lh3.ggpht.com/jzK6pwLVx-bVurFy-0rsZKbsZUdy17MynCsXa3cFzWkPIDQYFJKo9BQY-sIRVTzi8tw=w300

Device: https://www.dropbox.com/s/hhp38riujwdnkc4/prod_sp_d101_.png?dl=0

**Comment by IvoDerksen** [comment]
Hey Jelger,

The icons are done! Good luck on finishing the app!

**Comment by jghaanstra** [comment]
Looking awesome, thanx!

**Comment by jghaanstra** [comment]
Hello Ivo,

DoorBird has updated their logo. Can you create a new vector logo for me?

https://www.doorbird.com/images/doorbird_logo_dark.png

**Comment by IvoDerksen** [comment]
There you go!

Met vriendelijke groet,

Ivo Derksen

**Comment by jghaanstra** [comment]
Nice, thanx!
