### ISSUE TITLE
com.tractive

### ISSUE THREAD

**Issue by edwinvdpol** [athombv/homey-vectors-public#200]
@IvoDerksen If you have the time, can you create icons for the following Tractive devices, please?

Thanks in advance!

**EDIT 17/7:** Removed 1 device

---
**Tractive Tracker**
![tractive-dog-lte-tracker](https://github.com/athombv/homey-vectors-public/assets/9265514/19eaabda-5d5d-4ea9-a15e-e68ed57b6401)

**Comment by IvoDerksen** [comment]
Ofcourse

**Comment by edwinvdpol** [comment]
You are awesome, thanks! ❤️
