### ISSUE TITLE
io.quatt

### ISSUE THREAD

**Issue by trietsch** [athombv/homey-vectors-public#201]
Hi! Could you help out creating a vector image for the Quatt Heatpump?
Logo can be found [here](https://assets-global.website-files.com/61c051a291f24f93d47cdaf7/649956878e5e9efd16cdc77c_Etranz_Heat-pump_F2B_Front%201-p-2000.webp).

![image](https://github.com/athombv/homey-vectors-public/assets/22979744/682c00c4-e71c-45b4-b98e-1da74f2f9662)

**Comment by IvoDerksen** [comment]
Yes! I'll have it tomorrow or coming week!

**Comment by trietsch** [comment]
Awesome, coming week is quick enough btw. Still working on the app 😁

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by trietsch** [comment]
Awesome, thanks Ivo!
