### ISSUE TITLE
com.technisat.smarthome

### ISSUE THREAD

**Issue by Tymec** [athombv/homey-vectors-public#203]
I would like to request a device icon for the following water sensor: https://www.technisat.com/en_XX/Water-Sensor-1/352-11334-11759/?article=0000/9516
![DV025_ppic_0000+9516_010100_001](https://github.com/athombv/homey-vectors-public/assets/2727109/3f74fd8c-6821-4860-9302-4520b4218ad0)

If possible an additional icon for pairing would also be welcome. The pairing is done by pressing the black tamper switch/button on the left bottom of the device three times within one second ![IMG_20230719_025712544~2](https://github.com/athombv/homey-vectors-public/assets/2727109/12eb2679-b669-4c5f-860f-774d9d978407)

**Comment by IvoDerksen** [comment]
Ofcourse!

**Comment by IvoDerksen** [comment]
Here you go, both the driver icon and the pair icon with instructions!
