### ISSUE TITLE
io.olae.ferroamp

### ISSUE THREAD

**Issue by olaeriksson** [athombv/homey-vectors-public#204]
I need some icons for the the Ferroamp solar panel system.

Four devices:
- Ferroamp EnergyHub
- Ferroamp Solar String Optimizer
- Ferroamp Energy Storage Module
- Ferroamp Energy Storage Optimizer

**EnergyHub**
![image](https://github.com/athombv/homey-vectors-public/assets/29456953/19101fb8-5ada-4275-ba29-8797a6f12439)
![image](https://github.com/athombv/homey-vectors-public/assets/29456953/cdafac75-155b-48c1-aba5-21ef0b4d31bc)

**Solar String Optimizer**
![image](https://github.com/athombv/homey-vectors-public/assets/29456953/4fea7fc7-2129-4140-b12b-80ea987169f5)

**Energy Storage Module**
![image](https://github.com/athombv/homey-vectors-public/assets/29456953/2dfa80d9-c007-4eb0-ba5f-361282b93edc)

**Energy Storage Optimizer**
![image](https://github.com/athombv/homey-vectors-public/assets/29456953/2a00f4b4-f639-41c4-b36a-ff6414d7f1ed)

**Comment by IvoDerksen** [comment]
Yes sure! Nice products!

**Comment by IvoDerksen** [comment]
Here you go!
