### ISSUE TITLE
com.ady.button_plus

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey-vectors-public#205]
Hi,

Could you create some of your lovely icons for my new app please.
https://github.com/AdyRock/com.ady.button_plus

I would need the app icon and the icons for the two drivers.
The link to the product is https://button.plus/

Thank you.

**Comment by IvoDerksen** [comment]
Here you go!
https://github.com/athombv/homey-vectors-public/commit/c1ceb855fa261312df98ac722b0f4602605cceb7

**Comment by AdyRock** [comment]
Thank you
