### ISSUE TITLE
Aeon Labs (Aeotec) DSC06106

### ISSUE THREAD

**Issue by SPAeotec** [athombv/homey-vectors-public#207]
Hi,

can you please create an icon for me for the Smart Energy Switch and Pico Devices?

![AEO_SEI](https://github.com/athombv/homey-vectors-public/assets/62385464/68d21de6-23fc-4336-8ecd-d1e58c04f414)
![AEO_PICO](https://trello.com/1/cards/64e31a0bb690ce89b499db57/attachments/64e31bc8e6cd9e424318c48e/download/PicoSwitch_N_01.jpg)![AEO_PICO]

Thanks
Sebastian

**Comment by IvoDerksen** [comment]
Here you go Sebastian!
