### ISSUE TITLE
Icons for Zaptec Pro and Zaptec Sense

### ISSUE THREAD

**Issue by PatrickE94** [athombv/homey-vectors-public#208]
Hi again,

The Zaptec Go icon made a success and is in the app store! It's time to add some more Zaptec devices.

Could you assist me with icons for the [Zaptec Pro](https://zaptec.com/en/charging-station-zaptec-pro/) and the [Zaptec Sense](https://zaptec.com/en/sense/)?

Many thanks!

**Comment by IvoDerksen** [comment]
Congrats! And I will have them ready this weekend!

**Comment by PatrickE94** [comment]
That's great! 

While we're at it, can you add the discontinued [Home charger](https://zendesk.zaptec.com/hc/article_attachments/360012159937/EN_-_PRODUCT_SHEET_-_ZAPTEC_HOME_-_16102020.pdf) as well?

**Comment by IvoDerksen** [comment]
Here you go!
I saw no difference in the Home and Pro except the more professional base, so they are basically the same!
