### ISSUE TITLE
com.tplink.kasa

### ISSUE THREAD

**Issue by mijgame** [athombv/homey-vectors-public#209]
Hi! Could you make icons for these new TP-Link devices? Thanks!

EP40:
![large](https://github.com/athombv/homey-vectors-public/assets/8114544/eb024cd5-4728-402a-b16c-335344766bca)

HS300:
![large](https://github.com/athombv/homey-vectors-public/assets/8114544/b22076a5-3131-4e5a-bb1e-d666789b22e8)

KP115:
![large](https://github.com/athombv/homey-vectors-public/assets/8114544/5a761c60-bde8-4b2c-90b4-1760c42770c5)

KP200:
![large](https://github.com/athombv/homey-vectors-public/assets/8114544/f8d21773-af73-4fa2-8389-3985fefb930b)

KP401:
![large](https://github.com/athombv/homey-vectors-public/assets/8114544/bb07a177-796a-4ca1-8234-561c2c910099)

**Comment by IvoDerksen** [comment]
can you give me your driver names per device? So I can make it easier for you

**Comment by mijgame** [comment]
Sure, I've added them to the original post.

**Comment by IvoDerksen** [comment]
Here you go!
