### ISSUE TITLE
com.popp

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-vectors-public#21]
Would love 2 have some icons updated to coolness for the PoPP Z-wave App.

PoPP Solar Siren
PoPP Z-Rain
PoPP Weather
PoPP Secure Flow Stop

I Will upload some pics in the next post

**Comment by mruiter** [comment]
![popp z-weather](https://user-images.githubusercontent.com/17739535/33797282-80e08660-dd05-11e7-93c5-162c8f1c03ed.png)
![Uploading popp secure flow stop.jpg…]()
![Uploading Popp Z-Rain.jpg…]()
![Uploading solar siren.jpg…]()

**Comment by mruiter** [comment]
And the keyfob please

![large](https://user-images.githubusercontent.com/17739535/33802995-898ee218-dd85-11e7-90c8-be0f295c0c14.png)

**Comment by mruiter** [comment]
And the new keypad lock also please ;) 
![popplock](https://user-images.githubusercontent.com/17739535/33941048-875919d0-e011-11e7-8b5d-a4ba5124ee46.jpg)

**Comment by mruiter** [comment]
Sorry , i'm adding a lot of device support.
Also the CO2 detector please.
Thank you 
![co2](https://user-images.githubusercontent.com/17739535/33941439-efab907a-e012-11e7-9e11-8c4c1bf630d1.jpg)

**Comment by IvoDerksen** [comment]
Sure, I'm on them! Could take me a bit longer then previous!

**Comment by mruiter** [comment]
No problem offcourse.. Thx again !

**Comment by IvoDerksen** [comment]
There you go!!

**Comment by mruiter** [comment]
Wauw they look good thx.

Im missing they keyfob btw 😜

**Comment by IvoDerksen** [comment]
My bad, I've counted them, but them I forgot I also added the popup water sensor!

**Comment by IvoDerksen** [comment]
It's in the repo!

**Comment by mapulu** [comment]
Please create a device icon for Popp Smart Outdoor Plug
![Popp Smart Outdoor Plug](https://www.popp.eu/wp-content/uploads/2018/12/smart-outdoor-plug-flyer-DE_front.jpg)

**Comment by mapulu** [comment]
Can be closed

**Comment by mapulu** [comment]
Thought I've seen a similar device icon. But can't find it.

So please also create a Icon for Popp Mold detector 
 ![Popp Mold Detector](https://www.popp.eu/wp-content/uploads/2018/12/Z-Wave_POPP_Mold_Detector_24104-768x751.png)

**Comment by mapulu** [comment]
And please create a icon for this wallplug
![Popp Plug](https://shop.bsg-smarthome.de/media/image/product/169/lg/popp-power-plug-zwischenstecker~2.jpg)

**Comment by IvoDerksen** [comment]
> Thought I've seen a similar device icon. But can't find it.
> 
> So please also create a Icon for Popp Mold detector
> ![Popp Mold Detector](https://camo.githubusercontent.com/6e1715162baf08550be6abb34208b5c0dee0c938/68747470733a2f2f7777772e706f70702e65752f77702d636f6e74656e742f75706c6f6164732f323031382f31322f5a2d576176655f504f50505f4d6f6c645f4465746563746f725f32343130342d373638783735312e706e67)

It is fairly similar to a door sensor of Fibaro. I've modified it slightly.

**Comment by IvoDerksen** [comment]
These three will be done tomorrow.

**Comment by IvoDerksen** [comment]
Here you go!
