### ISSUE TITLE
New devices for com.sensibo

### ISSUE THREAD

**Issue by oh2th** [athombv/homey-vectors-public#211]
I'm in the process of updating the branding and a new device for Sensibo.

Could I get these two:

driver/Sensibo
![Sensibo](https://github.com/athombv/homey-vectors-public/assets/59442255/046898fe-d9f6-453b-9817-bda0e76f6b5e)

driver/SensiboElements
![elements](https://github.com/athombv/homey-vectors-public/assets/59442255/a863917b-c5d6-4ddc-9056-a3083faf86b5)

The app was recently transferred to me by balmli.

**Comment by IvoDerksen** [comment]
Yes ofcourse!
