### ISSUE TITLE
de.blueforcer.awtrixlight

### ISSUE THREAD

**Issue by bckp** [athombv/homey-vectors-public#212]
Hello, can I please request help with App i create, i need App icon and device icon.

Site: https://blueforcer.github.io/awtrix-light/#/hardware

Logo they using: ![image](https://github.com/athombv/homey-vectors-public/assets/179652/07cda053-3e33-4c92-a6b2-96d9c0930188)

AwtrixDevice: https://www.ulanzi.com/products/ulanzi-pixel-smart-clock-2882 this is Ulanzi Clock, but by design any ESP32 with proper connection should work, so not sure if only some kind of matrix icon?

Thanks
Radovan

**Comment by IvoDerksen** [comment]
Here you go!
app icon, 2 clock icons, one a matrix screen (generic) and one with the shape of the clock.
