### ISSUE TITLE
com.ember

### ISSUE THREAD

**Issue by kraineff** [athombv/homey-vectors-public#213]
Hello!
I would like to ask 4 icons for the Ember app!

![Safari g17N2eaS](https://github.com/athombv/homey-vectors-public/assets/7906418/4fc689a6-4aa3-453d-a3e4-1b3429f17dbe)

Here you can find more images: https://ember.com/collections/all-drinkware
Thank you!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by kraineff** [comment]
Thank you so much!!!!!!
