### ISSUE TITLE
com.galcar.tami4edge

### ISSUE THREAD

**Issue by gal-car** [athombv/homey-vectors-public#218]
Hi,

I am writing a new Homey-app for "Tami4 Edge Plus" water-bar.
The product is described here:
https://www.tami4.co.il/bar-store/edgeplus

You can also look for "Tami4 Edge Plus" on the internet, you will find many pictures.

Would you be willing to create icons for that device?

Thank you so much,
Galcar

**Comment by gal-car** [comment]
Hi,

I forgot to mention that I would also need icons for the capabilities I have in my app:
1. A button called "Boil Water" which boils the water of the water-bar
2. A number capability called "UV Lamp Replacement" which shows how many days are left before you have to replace your UV-Lamp
3. A number capability called "Filter Replacement" which shows how many days are left before you have to replace your filter

Would it be possible to create icons for those as well?

Thanks you very much,
Galcar.

**Comment by IvoDerksen** [comment]
Yes ofcourse!

**Comment by gal-car** [comment]
Thanks!
Looking forward :-)

**Comment by IvoDerksen** [comment]
Here you go!
You might want to work with alarms, otherwise the normal versions work (with the 2 in the folder name)

**Comment by gal-car** [comment]
This is EXCELLENT!
Thank you so much, I really appreciate it :-)

**Comment by IvoDerksen** [comment]
Thanks!
