### ISSUE TITLE
icons for com.plugwise.zigbee (TOM, LISA, PLUG)

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-vectors-public#22]
The icons that I have made so far aren't that perfect.
I suspect I did not use the right resolution/dimensions.
Also the icon for Lisa could be much better.

The svg's can be found at https://github.com/kasteleman/com.plugwise.zigbee

**Comment by IvoDerksen** [comment]
I am still working on the plug. But the Lisa and Tom are done!
Happy Holidays!

**Comment by kasteleman** [comment]
Thx Ivo.
Happy Holidays!

**Comment by IvoDerksen** [comment]
They can be found [here](https://github.com/athombv/homey-vectors-public/commit/8d672390fbbcf11eebd0460463e39bf5d2d6ffae)!

**Comment by IvoDerksen** [comment]
Ho Ho Homey!

**Comment by IvoDerksen** [comment]
Good luck on completing the app, and/or enjoy the fresh icons! Best wishes!
