### ISSUE TITLE
com.galcar.linksys_router

### ISSUE THREAD

**Issue by gal-car** [athombv/homey-vectors-public#221]
Hi,

I created an app for Linksys routers support.
For now, I have only one kind of Linksys-router-  Linksys "Velop - WHW03", which is a 3-node mesh router. You can find pictures and information about Linksys-velop-whw03 right here:
https://www.linksys.com/whw0303---tri-band-intelligent-mesh-wifi-5-system-3-pack/WHW0303.html

If possible, I will therefore need Icons for the following:
1. Driver icon (should show that typical velop-router, as you can see in the picture in the link mentioned above)
2. Icons for the following capabilities:
- external IP (sensor type)
- firmware last check date (sensor type)
- firmware version (sensor type)
- number of connected 5 GHz devices (sensor type)
- number of connected  2.4 GHz devices (sensor type)
- number of connected  LAN devices (sensor type)
- number of unknown connection-type devices (sensor type)
- overall number of connected devices (sensor type)
- number of nodes (sensor type) - a node is a single "tower" so maybe a picture of one tower similar to the 3 towers of the driver's icon?
- wan connection status (sensor type)
- turn on/off guest network (toggle type)
- reboot router (button type)

Please accept my apology - I know it's a lot of I know it's a lot of icons - but I think this app can contribute to a lot of users, and if others will require, I can extend it to any other linksys router that supports "Smart Wifi".

Thanks a lot for your great help, I really appreciate it!
Please feel free to ask anything regarding this router or the app I developed.

Thank you,
Galcar.

**Comment by IvoDerksen** [comment]
My first response is wow, that is a lot of depth for an app. So congrats on that. I'll take them in account and hopefully I can fix this soon!

**Comment by gal-car** [comment]
Thank you so much, I really appreciate your efforts!

**Comment by gal-car** [comment]
Hi Ivo,
Did you have the chance to take a look at my requests?

**Comment by IvoDerksen** [comment]
Yes and no! I have sketches, I will create them tonight!

**Comment by gal-car** [comment]
Thank you very much, Ivo, I really appreciate your efforts.

**Comment by IvoDerksen** [comment]
here you go! let me know if it is good or needs some work still :)

**Comment by gal-car** [comment]
Absolutely amazing!
Thank you so much!!!
Have a great weekend :-)

**Comment by IvoDerksen** [comment]
You too, happy holidays!
