### ISSUE TITLE
no.enua

### ISSUE THREAD

**Issue by jaottosen** [athombv/homey-vectors-public#224]
Hi!

I am developing a Homey app for Enua, and need an icon for the Enua EV Charger (portable electric vehicle charger):

![image](https://github.com/athombv/homey-vectors-public/assets/153720908/44288275-c131-4461-a172-4025ef91b03e)

![image](https://github.com/athombv/homey-vectors-public/assets/153720908/59b8093b-1f56-4d2e-8055-be4d45e97bb0)

![image](https://github.com/athombv/homey-vectors-public/assets/153720908/89e0b452-f918-46da-b68b-722586dbcdad)

![image](https://github.com/athombv/homey-vectors-public/assets/153720908/232f2a97-5f46-4718-b448-f783e2fe0902)

You will find more images if you visit our [website](https://www.enua.no/) :)

Thank you!

**Comment by IvoDerksen** [comment]
I will be working on it! Nice product!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by jaottosen** [comment]
Thanks!
