### ISSUE TITLE
com.ecobee

### ISSUE THREAD

**Issue by TimBrouwersBscript** [athombv/homey-vectors-public#225]
Hi,

Can you please make icons for 2 ecobee thermostats

- https://www.ecobee.com/en-us/smart-thermostats/smart-thermostat-premium/
- https://www.ecobee.com/en-us/smart-thermostats/smart-thermostat-enhanced/

I would also like an icon for an airquality custom capability

Thanks
Tim

**Comment by IvoDerksen** [comment]
Hey Tim, here you go!
