### ISSUE TITLE
com.baumus.rctpowerstorage

### ISSUE THREAD

**Issue by Baumus** [athombv/homey-vectors-public#227]
Please create an icon for my app, that monitors the RCT Power Storage DC. RCT Power is a registered trademark of RCT Power GmbH. This app is not provided by, endorsed by, supported by, or affiliated with RCT Power GmbH in any way.

Please do also create a driver icon for the RCT Power Storage DC.

More details (product image and logo) here: https://www.rct-power.com/de/power-storage-dc.html

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
I've updated the file (names) and added the app icon too! @Baumus
