### ISSUE TITLE
com.tuya.zigbee (Nous A4Z device)

### ISSUE THREAD

**Issue by neoscaler** [athombv/homey-vectors-public#228]
Hi there,

I try to develop support for the Nous A4Z device in the [com.tuya.zigbee](https://github.com/JohanBendz/com.tuya.zigbee) app. Can you perhaps support me in creating the driver icon? 

The device looks like this:

![A4Z_box-removebg-preview](https://github.com/athombv/homey-vectors-public/assets/1023650/1823c50e-231d-4add-bcdf-8f22c6318f95)

**Comment by IvoDerksen** [comment]
Planned for today!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by neoscaler** [comment]
> Here you go!

Thanks a lot, looks great
