### ISSUE TITLE
com.jilles.rfxcom.2

### ISSUE THREAD

**Issue by nattlip** [athombv/homey-vectors-public#23]
![rfxtrx](https://user-images.githubusercontent.com/7040452/34325613-b333dfb2-e896-11e7-8633-5ddccddd325f.JPG)

**Comment by nattlip** [comment]
![rfxlan](https://user-images.githubusercontent.com/7040452/34325617-ee43e052-e896-11e7-8a09-ceae21452372.jpeg)

**Comment by nattlip** [comment]
![large](https://user-images.githubusercontent.com/7040452/34325625-2798dd58-e897-11e7-92c3-73d490f11fb9.jpg)

**Comment by nattlip** [comment]
![large](https://user-images.githubusercontent.com/7040452/34325628-438e89c2-e897-11e7-8140-d5ecdbf8ed70.jpg)

**Comment by nattlip** [comment]
![large](https://user-images.githubusercontent.com/7040452/34325630-5c3576a2-e897-11e7-80fa-e4725697c3f7.jpg)

**Comment by IvoDerksen** [comment]
Fresh icons! Hot off the press. Best wishes!
