### ISSUE TITLE
TKBHome TZE93 images please

### ISSUE THREAD

**Issue by pshotton** [athombv/homey-vectors-public#230]
I need icon and learnmode images for the TKBHome TZE93 thermostat device.
Device image here:
![large](https://github.com/athombv/homey-vectors-public/assets/5080305/5b7ad4ae-8aff-4a82-9626-42758d50ca86)

Inclusion is started by:
Make sure the thermostat is in off state. 
Press 3 times within 1,5 sec on the left hand menu button.

Thanks

**Comment by IvoDerksen** [comment]
Here you go!
