### ISSUE TITLE
SONOFF SNZB-06P - Occupancy Sensor images

### ISSUE THREAD

**Issue by wavegazer** [athombv/homey-vectors-public#231]
Hi,

I developed the driver/app for this new sensor, which is not yet supported on any other Homey app and I would like to either publish it or allow another SONOFF Zigbee app to add it. In both cases images/vectors are required.
May I kindly ask your support to create the required images?

This is the device:
https://sonoff.tech/product/gateway-and-sensors/snzb-06p/

![image](https://github.com/athombv/homey-vectors-public/assets/92792016/7a70f7eb-a236-4fa9-8aab-0b75b3b374f3)

![image](https://github.com/athombv/homey-vectors-public/assets/92792016/34c697d6-51db-4bde-a8e0-c195f6d33ec7)

Please let me know if other info is needed as this is my first app/request.

Thank you.

Kind regards,
Ricardo

**Comment by IvoDerksen** [comment]
Hey Ricardo, 
no problem!
Do you have pair instructions? I could add a learn mode  / pair icon too :)

**Comment by wavegazer** [comment]
Hi, Ivo.
Thanks, that would be great!

To enter in pairing mode the user needs to press the power button for 5secs till the LED in the power button starts to blink red ~every second. Here's a screenshot from the user manual:

![pairing_screenshot](https://github.com/athombv/homey-vectors-public/assets/92792016/08be6da8-2fdd-42e4-a293-5bcee6a8a010)

Btw, I contacted the developer of the SONOFF Zigbee app in case he wants to add this driver and I'm still waiting for a reply. Otherwise, I'll publish it myself.

For your reference, this is the community app, in case you want to check the look&feel of the imagery (maybe you've done it yourself...).
https://homey.app/en-us/app/tech.sonoff/SONOFF-Zigbee/

Thanks, again.

Cheers,
Ricardo

**Comment by IvoDerksen** [comment]
And the pair icon!

**Comment by wavegazer** [comment]
This is awesome, Ivo! Many thanks for your work. Cheers!
