### ISSUE TITLE
com.sortedbits.incomfort

### ISSUE THREAD

**Issue by sorted-bits** [athombv/homey-vectors-public#232]
I am looking for a Driver icon for the Intergas Comfort Touch thermostat.  I tried designing it myself, but I failed a dozen times. Hoping someone can help me out.

The device is wall-mounted thermostat, available in 2 colors, white and black.

![image](https://github.com/athombv/homey-vectors-public/assets/111713/edd38454-8520-4eb0-9b48-d5ea7e6e96c3)

 ### Failed attempts:
Here are some failed attempts, they all feel off and not in the same quality as the rest of the icons.

![old](https://github.com/athombv/homey-vectors-public/assets/111713/d58af89f-7ce2-4810-beef-153f0fc20463)
![old2](https://github.com/athombv/homey-vectors-public/assets/111713/c759413f-a612-43f6-b1c6-94440b3edbd5)
![old3](https://github.com/athombv/homey-vectors-public/assets/111713/d41054c4-d18e-46e0-b5d6-4869d1a4bb1e)
![icon copy](https://github.com/athombv/homey-vectors-public/assets/111713/7637f75e-0261-4b08-86d7-d020a0f7ff57)

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
Your tries though, were really good already (we now use a 3D view)
