### ISSUE TITLE
Victron app device icons

### ISSUE THREAD

**Issue by ricott** [athombv/homey-vectors-public#234]
Hi,

May I request new device icons for the `com.victronenergy` app.

- Victron GX
Really more of a software, that can take multipe physical forms. You can buy any of the Victron packaging like [Cerbo GX](https://www.victronenergy.com/communication-centres/cerbo-gx), the[ Ekrano GX](https://www.victronenergy.com/communication-centres/ekrano-gx), or the [Color Control GX](https://www.victronenergy.com/communication-centres/color-control). Or you can simply install the OS on a raspberry pi by yourself.

- Victron VRM
[Victron's online portal/APIs](https://www.victronenergy.com/panel-systems-remote-monitoring/vrm). Currently only used for forecasts of solar production and energy consumption.

- Tank sensor
Any type of sensor that measures the level of a tank containing fuel, water, waste water, gas, etc

- Temperature sensor
Any type of [temp sensor](https://www.victronenergy.com/live/temperature_sensors) from Victron, or any compatible solution.

- EV Charger
I'm about to add support for their [EV Chargers](https://www.victronenergy.com/ev-charging).

Best,
Richard

**Comment by IvoDerksen** [comment]
Hey Richard, sorry for the delay.
I have created the gx, arm and ev icon.

What do you mean with the sensors, are these devices you can couple? E..g should I make driver icons for these too?
Any example of the tank sensor? Else I would create a 2D icon for this (a sensor / capability icon

**Comment by ricott** [comment]
Hi!

The sensors are also device types, one for Temperature and one for monitoring Tank fill level (0-100%).

In a Victron system, you can connect multiple temp sensors, for instance inside your garage, on the batteries, fridge, etc. They are sensors that can be connected to your GX device using wires or Bluetooth. There is a fairly new addition of support for the [Ruuvi temp](https://www.victronenergy.com/blog/2022/01/31/venus-os-v2-80/) sensors which are popular. The temp sensor can take many forms and you can have multiple of them - thus a separate device type.

Similarly, the tank sensor works the same way, you can have a tank for fresh water, one for fuel for your generator, etc. What you want to measure is the tank fill level in percentage. A GX system can have multiple tanks sensors connected.
Googling a bit more on the topic it [this](https://acdcmarineinc.com/product-category/marine-engine-sending-unites-switches/liquid-level-sensors/) seem to be a good representation.

**Comment by ricott** [comment]
🙏
