### ISSUE TITLE
Swedish Trafikverket weather device icon

### ISSUE THREAD

**Issue by ricott** [athombv/homey-vectors-public#235]
Hi,

May I request a new device icon for the `se.trafikverket.vader` app.

Only one device here and that is a weather station installed along the Swedish highways.
They typically look something like [this](https://sv.wikipedia.org/wiki/Vvis).
It is a [governmental](https://bransch.trafikverket.se/tjanster/trafiktjanster/VViS/) organisation so not a lot of fancy graphics or english content.

Regards,
Richard

**Comment by IvoDerksen** [comment]
Here you go!
