### ISSUE TITLE
TP-LINK - KP115 / KP105

### ISSUE THREAD

**Issue by shaarkys** [athombv/homey-vectors-public#236]
Hi,
can you please create vector icon out of this image ? 

It's https://www.tp-link.com/uk/home-networking/smart-plug/kp115/ for this app - https://homey.app/en-cz/app/nu.baretta.tplink/TP-Link-KASA-Smart-Home---LAN/test/

Thank you ;-)

![large](https://github.com/athombv/homey-vectors-public/assets/14859895/ad3f0443-5956-4f26-b55a-0bc9bfcf66d9)

**Comment by IvoDerksen** [comment]
Here you go!
