### ISSUE TITLE
com.coderax.heimgard

### ISSUE THREAD

**Issue by Coderaxx** [athombv/homey-vectors-public#240]
Hey! I'm working on a new project, and I need a couple of icons.😊
The app I'm working on is Heimgard's door lock. This is a Zigbee device, so a learnmode as well, would have been awesome!

The door lock is called "HT-SLM-2", and I've attached an image of it below.
![heimgard-smart-fingerprint-digital-las-sort](https://github.com/athombv/homey-vectors-public/assets/48462275/1517fed9-544b-4fe1-aa71-802c3342757a)

And here's an image showing both front and back of the lock.
![heimgard-smart-lock-580x650-1-500x500](https://github.com/athombv/homey-vectors-public/assets/48462275/a98bc5b9-6f59-4baf-ab7e-502a40ed53f2)

I have no specific requests or instructions, as you are more capable of graphic design than I am.😅

As for the learnmode, there is no graphic instructions on how to put your lock in pairing mode. I'll attach the user manual below, and you can see for yourself if there is something you could use. If not, you're completely fine to make something up yourself. Maybe the door lock image itself, showing both front and back, and maybe the relevant keys circled out? As for the driver icon, no specific requests or instructions. You're the expert!😊
[https://heimgard.com/content/2023/08/Heimgard-Smart-Lock-EN-NO-SE-DKv1-01.pdf](https://heimgard.com/content/2023/08/Heimgard-Smart-Lock-EN-NO-SE-DKv1-01.pdf)

Thanks in advance!😁

**Comment by IvoDerksen** [comment]
Pardon for the delay, hope you like it!

**Comment by Coderaxx** [comment]
No worries! Looks amazing, thanks for your persistent great work!😄
