### ISSUE TITLE
com.tuya.zigbee / Fain coil thermostat

### ISSUE THREAD

**Issue by danielloczi** [athombv/homey-vectors-public#241]
Hi!

I'm working on the integration with the Tuya Fan Coil Thermostat (_TZE204_mpbki2zm / TS0601) and would like to request 3 icons for the project. One for the device and two for custom capabilities.

The thermostat looks like this:
![IMG_0383](https://github.com/athombv/homey-vectors-public/assets/11349934/0ba1a884-4d8c-4167-87cd-03f94fcaace0)
![IMG_0382](https://github.com/athombv/homey-vectors-public/assets/11349934/25827382-7688-4ec4-be8c-135ffbaeb0a7)
![image](https://github.com/athombv/homey-vectors-public/assets/11349934/690e03c0-e09d-453b-87c7-9bfd1e1c131c)

A link to the shop where it can be bought (there are a few more images there):
https://www.aliexpress.com/item/1005005650411387.html?spm=a2g0o.cart.0.0.3c4238dawX5N0w&mp=1

I've implemented two custom capabilities, but the icons are missing for them:
- one displays the valve status (open/closed)
- the other one indicates the speed of the fan
Both of them are also displayed by the device, so would be cool to use their icons in Homey too:
![image](https://github.com/athombv/homey-vectors-public/assets/11349934/03072c38-5d48-4fbc-aaf3-7c742b5bf85e)

Can you please help me and create these 3 icons?
Thank you in advance!

**Comment by IvoDerksen** [comment]
Here you go!
