### ISSUE TITLE
cc.xyzroe.zigusb / ZigUSB Device

### ISSUE THREAD

**Issue by abn** [athombv/homey-vectors-public#242]
Hi there. I am developing a new app and driver for the [ZigUSB](http://xyzroe.cc/ZigUSB/) device. The app is being developed at https://github.com/abn/cc.xyzroe.zigusb and the hardware is developed at https://github.com/xyzroe/ZigUSB.

Can I please request vector art for the device driver? Thank you for your work.

![With Casing](https://raw.githubusercontent.com/xyzroe/ZigUSB/main/images/top_pcb_touch.jpeg)
![Without Casing](https://raw.githubusercontent.com/xyzroe/ZigUSB/main/images/top_touch.png)

**Comment by IvoDerksen** [comment]
Here you go!
