### ISSUE TITLE
Icons in new format for Tapo products

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/homey-vectors-public#243]
Hi Ivo,

For a new integration I am looking for icons for the following devices:

-  Tapo P115: Smart Socket (Energy)
-  Tapo P100: Smart Socket
-  Tapo P125M: Mini Smart Plug (Energy)
-  Tapo L900-10: Multicolour LED
-  Tapo L920-5: Multicolour LED
-  Tapo L920-10: Multicolour LED
-  Tapo L930-5: Multicolour LED
-  Tapo L630: Smart Wi-Fi Spotlight, Multicolor
-  Tapo S505D: Smart Switch

**Comment by IvoDerksen** [comment]
Sorry for the delay, but here they are!
