### ISSUE TITLE
Icon request for com.galcar.netatmo

### ISSUE THREAD

**Issue by gal-car** [athombv/homey-vectors-public#246]
Hi,

I have build an app with a large set of drivers.
My Review with Athom was rejected due to the fact my icons do not represent the devices, so I need some help in creating the following icons:
- Cable-outlet: https://www.legrand.com/ecatalogue/en/our-products/cable-outlet-mosaic-16-with-cable-grip-2-modules-white-077551?category_id=43546
- Contactor: https://www.legrand.com/ecatalogue/en/our-products/contactor-cx3-with-front-face-handle-2-pole-25a-250v-2-no-contacts-with-230v-coil-1-module-412544
- Dimmer Switch: https://www.legrand.com/ecatalogue/en/our-products/belanko-s-universal-rotary-dimmer-led-halogen-300w-white-617635
- Micromodule: https://www.legrand.com/ecatalogue/en/our-products/connected-lighting-micromodule-with-dimmer-option-150w-led-064899
- Light switch: https://www.legrand.com/ecatalogue/en/our-products/connected-switch-arteor-with-netatmo-574201
- Power Outlet: https://www.legrand.us/wiring-devices/radiant-collection/outlets/radiant-smart-15a-outlet-with-netatmo-white/p/wnrr15wh
- Remote Control: https://www.legrand.fr/pro/catalogue/commande-generale-sans-fils-departarrivee-pour-installation-connectee-celiane-with-netatmo-blanc
- Roller Shutter switch: https://www.legrand.com/ecatalogue/en/our-products/connected-roller-shutter-switch-arteor-with-netatmo-574204
- Teleruptor: https://www.legrand.pt/e-catalogo/cx3-with-netatmo-telerruptor-conectado-para-o-quadro.html
- Smoke Detector: https://www.netatmo.com/fr-fr/smart-smoke-alarm
- Energy Meter: https://www.legrand.com/ecatalogue/en/our-products/connected-electricity-meter-emdx3-with-netatmo-100-240v-supplied-with-1-closed-current-transformer-80a-1-module-412015
- Load Shedder: https://www.legrand.com/ecatalogue/en/our-products/connected-load-shedder-with-netatmo-412172

Please let me know if any more information is required. 

Thank you for your help,
Gal.

**Comment by IvoDerksen** [comment]
Sure! I want to complete it in a week!

**Comment by gal-car** [comment]
Thank you so much! I really appreciate your efforts 


________________________________

**Comment by gal-car** [comment]
Hi, 
What is the status of this request?

**Comment by IvoDerksen** [comment]
Well sorry for that! I fixed them (see commit)

**Comment by IvoDerksen** [comment]
Happy coding and see you next time!

**Comment by gal-car** [comment]
Amazing! Excellent work! They are awesome!
Thank you so much, Ivo.
My next app is on its way :-)
