### ISSUE TITLE
Icons for BMW Connected

### ISSUE THREAD

**Issue by sschutten** [athombv/homey-vectors-public#247]
I'm extending the [BMW Connected](https://homey.app/en-nl/app/com.rexwel.bmwconnected/BMW-Connected/) app to add support for Mini. Both use the same platform.

**App icon**
The app icon is currently the BMW logo. Since we will also support Mini it would be nice to have a logo to reflect that.

**Device icons**
More importantly, right now the app uses the BMW logo for the devices. In line with the [app store guidelines](https://apps.developer.homey.app/app-store/guidelines#id-1.5.-icons) it would be nice to use the outline of a BMW or Mini car. I was thinking of using the front of each brand, since they're both very recognizable. For example, take the mini outline in this image:
![image](https://github.com/athombv/homey-vectors-public/assets/10097564/aaa1ede8-b2a0-4534-a858-be8a3aa31b73)

Thanks a lot in advance 😃

**Comment by IvoDerksen** [comment]
I made you some variants, sorry for the delay.

**Comment by sschutten** [comment]
That's fine, I had other (good) stuff on my mind anyway. Thanks for the icons, I think they're excellent!
