### ISSUE TITLE
com.bluesound

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#25]
I'd like to request vector icons for the Bluesound logo and music devices. Here are some options. I probably only need one device icon though.

**Logo**: http://www.technologyintegrator.net/wp-content/uploads/sites/15/2016/03/Bluesound_B_Wordmark_Centred-2.jpg?x18413

**Node 2**: https://images.crutchfieldonline.com/ImageHandler/trim/620/378/products/2015/32/813/g813NODE2W-F.jpg

**Powernode 2**: https://www.hifisound.de/out/pictures/master/product/1/bluesound_powernode2_black(1).jpg

**The Vault:** http://www.van-duppen.nl/hifi/wp-content/uploads/2012/08/Bluesound_Vault2_White.jpg

Thanx in advance!

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by jghaanstra** [comment]
Nice job again, thanx!
