### ISSUE TITLE
App and Device Icons for Mercator Ikuü / com.gslender.mercator

### ISSUE THREAD

**Issue by gslender** [athombv/homey-vectors-public#253]
App is located at https://github.com/gslender/com.gslender.mercator

The devices that this app supports is from the company website at https://www.ikuu.com.au/

At this stage I'd like 

1) an App icon, which I guess is the triangle? Seems a bit daft but not sure what else would be valid !? Can you use the full name and icon as the App icon (like the community SMA Energy app did)

2) a Device icon for the Light Fan Controller https://www.ikuu.com.au/product/ac-fan-controller/

3) a Device icon for the Light Dimmer https://www.ikuu.com.au/product/light-dimmer/

Thanks :-)

**Comment by gslender** [comment]
Hello @IvoDerksen - no rush, but interested in when you might be able to take a look?

**Comment by IvoDerksen** [comment]
The coming days

**Comment by IvoDerksen** [comment]
Terribly sorry for the delay!
