### ISSUE TITLE
Add two more device icons to com.galcar.netatmo

### ISSUE THREAD

**Issue by gal-car** [athombv/homey-vectors-public#255]
Hi again,

I recently added two more devices to my app: com.galcar.netatmo:
1. Smart Indoor Siren: https://shop.netatmo.com/en-gb/security/systeme-d-alarme/smart-indoor-siren
2. Smart Carbon Monoxide Alarm: https://shop.netatmo.com/en-gb/security/carbon-monoxide-alarms/carbon-monoxide-alarm

Can you please create driver icons for them?
Please notice that you already created several icons for this app, so you probably want to follow the same UX conventions you had in the past.

Thank you so much for all your hard work!

**Comment by gal-car** [comment]
Hello,

Was there any progress with my previous requests?

In addition, I added a few more devices. 
Can I please request for the following icons?
1. Bticino external unit: https://catalogo.bticino.it/prodotto/sistemi-videocitofonici-e-citofonici/pulsantiere-esterne/pulsantiere-linea-3000/BTI-343093-IT
2. Bticino Garage Door/Gate Opener: https://catalogue.bticino.com/product/smart-home-solutions/living-now-smart---modular-version/wired-devices-for-light-and-shutter/BTI-3586C-EN

Thank you for your assistance,
Gal.

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
The other ones will come soon!

**Comment by gal-car** [comment]
This is AWESOME!!!
Thank you so much, Ivo!

**Comment by gal-car** [comment]
Hi Ivo, 
Any news with the additional 2 icons I requested? (The external unit and the Garage Door opener)?

**Comment by gal-car** [comment]
Thank you so so much!
These are awesone!!!

**Comment by IvoDerksen** [comment]
Thanks! Next time the lead times will be a lot less, had a couple of rough weeks and a small holiday!

**Comment by gal-car** [comment]
Sounds great 😊
