### ISSUE TITLE
nl.EcoDim new set of icons

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#258]
Hi Ivo, can you make a new set of icons for the EcoDim app?

All the Zigbee lights shown at:
https://www.ecodim.nl/nl/zigbee-lampen/

All the Zigbee dimmers (Z-wave and Matter have the same form-factor):
https://www.ecodim.nl/nl/smart-led-dimmers-en-schakelaars/zigbee/

All the Wireless switches:
https://www.ecodim.nl/nl/smart-led-dimmers-en-schakelaars/draadloze-schakelaars/

Best regards,

Ted

**Comment by IvoDerksen** [comment]
pardon the delay Ted, here you go!
