### ISSUE TITLE
com.xiaomi-zigbee additional vectors

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#26]
Hi @IvoDerksen 

Can you make some additional device icons for the following devices for the Xiaomi Zigbee app (https://github.com/TedTolboom/com.xiaomi-mi-zigbee/):
1. Aqara curtain controller:
https://xiaomi-mi.com/sockets-and-sensors/xiaomi-aqara-smart-curtain-controller-white/
2. Xiaomi smoke detector: 
https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mijia-honeywell-smoke-detector-white/
3. Xiaomi gas detector:
https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mijia-honeywell-gas-leak-detector-white/

**Comment by IvoDerksen** [comment]
Will do! Expect it in the beginning of coming week! Happy Easter!

**Comment by TedTolboom** [comment]
Thanks Ivo, as always looking forward to your artwork! Happy Easter!

**Comment by TedTolboom** [comment]
Hi @IvoDerksen,

Would it also be possible to add device icons for the [Aqara door lock with fingerprint reader](https://ae01.alicdn.com/kf/HTB1fRJoi3fH8KJjy1zcq6ATzpXaV/Original-Xiaomi-Aqara-Smart-Door-Touch-Lock-Live-Fingerprint-Unlock-Password-4-in-1-Unlock-App.jpg):

And the [Aqara lock core](https://ae01.alicdn.com/kf/HTB1_5K5flfM8KJjSZFrq6xSdXXat/Original-Xiaomi-Aqara-Security-Door-Lock-Core-with-Key-Compact-Anti-theft-with-5-keys-1.jpg)

Would be greatly appreciated.

**Comment by IvoDerksen** [comment]
Yes on it, expect them all somewhere tomorrow 👍 The curtain controller takes a bit more time than expected.

**Comment by IvoDerksen** [comment]
Curtain controller is left, probably tonight it's all done! I've updated the repo just now with the others!

**Comment by TedTolboom** [comment]
@IvoDerksen great thanks... but I guess you still need to press the push button ;-P
Last commit is from February 12th....

**Comment by TedTolboom** [comment]
You sure are! Great work again Ivo.
Enjoy the weekend!
