### ISSUE TITLE
com.xiaomi-mi-zigbee (next wave)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#267]
Aqara Cube T1 Pro: https://www.aqara.com/en/product/cube-t1-pro/
Aqara Light sensor T1: https://www.aqara.com/kr/product/illuminance-sensor-t1/
Aqara Wall outlet H2: https://www.aqara.com/en/product/wall-outlet-h2-eu/

Aqara Roller Shade Controller T1S: https://www.aqara.com/en/product/roller-shade-controller-t1s/
Aqara FP1E sensor: https://www.aqara.com/en/product/presence-sensor-fp1e/
Aqara FP2 sensor: https://www.aqara.com/en/product/presence-sensor-fp2/

Aqara Smart LED strip driver: https://www.aqara.com/kr/product/smart-led-strip-driver/

Aqara Door and Window Sensor P2: https://www.aqara.com/en/product/door-and-window-sensor-p2/
Aqara Motion and Light Sensor P2: https://www.aqara.com/en/product/motion-and-light-sensor-p2/
Aqara M2 Hub: https://www.aqara.com/en/product/hub-m2/
Aqara M3 Hub: https://www.aqara.com/en/product/hub-m3/

Aqara smart wall switch (no neutral, single rocker, US): https://www.aqara.com/en/product/smart-wall-switch-with-neutral/
Aqara smart wall switch (no neutral, double rocker, US): https://www.aqara.com/en/product/smart-wall-switch-with-neutral/
Aqara Smart Plug(US Version): https://www.aqara.com/en/product/smart-plug/

Aqara Wireless knob H1 https://homesmart.sg/product/aqara-wireless-knob-switch-h1/
Aqara Smart lock U200 https://www.aqara.com/en/product/smart-lock-u200/

Aqara High Precision motion sensor: https://www.aqara.com/kr/product/high-precision-motion-sensor/

Aqara Spotlight T1 https://www.aqara.com/en/product/spotlight-t1/

**Comment by IvoDerksen** [comment]
with some delay! here you go
