### ISSUE TITLE
New icons for se.styrahem.sonoff.zigbe

### ISSUE THREAD

**Issue by hakana** [athombv/homey-vectors-public#269]
Hi,

We need some icons for new products from Sonoff.

se.styrahem.sonoff.zigbe

SNZB-04P
![image](https://github.com/user-attachments/assets/8f944f4a-1f31-4284-8c7b-bfaac1a52d20)

SNZB-03P
![image](https://github.com/user-attachments/assets/ac12cd83-756c-4a7a-98c1-7c57aefba962)

**Comment by hakana** [comment]
@IvoDerksen  Any action here? Waiting for the icons so we can make a release.

**Comment by IvoDerksen** [comment]
here you go!
