### ISSUE TITLE
icons for Ubisys devices

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-vectors-public#27]
Request for icons for the Ubisys devices listed below:

Universal dimmer D1: http://ubisys.de/downloads/ubisys-d1-leaflet-en.pdf

Universal dimmer D1-R: http://ubisys.de/downloads/ubisys-d1r-leaflet-en.pdf

Power switch S2: http://ubisys.de/downloads/ubisys-s2-leaflet-en.pdf

Power switch S2-R: http://ubisys.de/downloads/ubisys-s2r-leaflet-en.pdf

Power switch S1: http://ubisys.de/downloads/ubisys-s1-leaflet-en.pdf

Power switch S1-R: http://ubisys.de/downloads/ubisys-s1r-leaflet-en.pdf

**Comment by IvoDerksen** [comment]
App icon and the dimmer/switch is created.
The other raildin version is coming!
