### ISSUE TITLE
More icons to se.styrahem.sonoff.zigbee

### ISSUE THREAD

**Issue by hakana** [athombv/homey-vectors-public#271]
Hi @IvoDerksen,

Looking for some awesome vector icons for these products!

SWV-BSP that is a outdoor water valve
![image](https://github.com/user-attachments/assets/4c6c6ce5-fe4f-4429-a439-314ab71d07d7)
![image](https://github.com/user-attachments/assets/11fd4651-6c02-4fbc-8eb2-e5573af54557)

ZBMicro that is a USB-switch
![image](https://github.com/user-attachments/assets/a3fb860d-6d98-4da9-9bee-334c55d47722)
![image](https://github.com/user-attachments/assets/17103c54-3cf4-4c37-af21-bff8208f87c4)

Best regards
Håkan Åkerberg
Tarra AB, Sweden

**Comment by hakana** [comment]
Also need a vector icon for ZBCurtain

![image](https://github.com/user-attachments/assets/6ae39e22-063b-4b4b-a0a0-5ef18ce979cc)

**Comment by hakana** [comment]
@IvoDerksen , will you have time to create the three icons  above?

**Comment by hakana** [comment]
@IvoDerksen, any update?

**Comment by hakana** [comment]
@IvoDerksen 
Monday? ;)

**Comment by IvoDerksen** [comment]
Yes, sorry!

**Comment by hakana** [comment]
No problem, thanks!
