### ISSUE TITLE
Icons for Inovelli app

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/homey-vectors-public#272]
Hi Ivo, can you make a new set of icons for the Inovelli app?

Blue series
    On/Off Switch (LZW30)
    Smart Dimmer Switch (LZW31)
    On/Off or Dimmer (VZW31)
    Smart Dimmer/Presence Sensing (VZW32)
    
Red series:
    Smart Fan/Light Canopy Module (LZM36)
    Smart Fan Switch (LZM35)
    On/Off or Dimmer (LZM31)
    Smart Dimmer/Presence Sensing (DZW32)

Thanks!

Best,
Leendert

**Comment by IvoDerksen** [comment]
Yes! On it this weekend!

**Comment by IvoDerksen** [comment]
I've created the icons by the best of my search skills, if any don't match can you please send a link or photo of the device!

**Comment by koktaildotcom** [comment]
Hi @IvoDerksen. Thank you for the icons again!
