### ISSUE TITLE
Nuki lock icon

### ISSUE THREAD

**Issue by jordenc** [athombv/homey-vectors-public#28]
Hi Ivo,

Can you make a cool icon for https://github.com/jordenc/io.nuki.smartlock ?

Thanks!

Greetings, 

Jorden

**Comment by IvoDerksen** [comment]
There you go! Fob, and bridge also included!

**Comment by IvoDerksen** [comment]
Logo can be used for app icon and the other for the drivers!
Happy Kingsday!

**Comment by jordenc** [comment]
Thanks a lot!
