### ISSUE TITLE
New icon for se.styrahem.sonoff.zigbe

### ISSUE THREAD

**Issue by hakana** [athombv/homey-vectors-public#289]
Hi @IvoDerksen,

I need an awesome vector icon for this new flood sensor!

![image](https://github.com/user-attachments/assets/65374581-ad6e-4972-a42f-1fb88de3857f)

Best regards
Håkan

**Comment by hakana** [comment]
Hi @IvoDerksen 
Do you know when you will have time for this?

**Comment by IvoDerksen** [comment]
Yes the coming days! I was on a brief holiday!

**Comment by hakana** [comment]
Thanks!

**Comment by hakana** [comment]
Hi @IvoDerksen 

When will this icon be available?

**Comment by hakana** [comment]
@IvoDerksen

What is going on?

**Comment by IvoDerksen** [comment]
Sorry here you go!
