### ISSUE TITLE
com.robot.xiaomi-mi

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#3]
Although this app will not be published in the app store (the setup procedure is to complex as there is no official API) I'm still sharing it on the forum and would like to have a proper app and device icon.

App & device icon: https://www.vopmart.com/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/i/mi-robot-vacuum-c.jpg

**Comment by IvoDerksen** [comment]
Hey Jelger,

The icon is done! Good luck on finishing the app!
If you need a pairing icon, just reopen the issue, or comment again. 
With a manual or a description (maybe with a picture, if it is not on the icon already), I can make an additional pairing icon with can be pasted in the setup wizard.
