### ISSUE TITLE
Icons for com.swiid

### ISSUE THREAD

**Issue by glennsp** [athombv/homey-vectors-public#30]
Hi,

may I request som icons for the Swiid Z-wave devices, please? Only SwiidInter Cord Switch is supported at the moment, though.

[Source code](https://github.com/glennsp/com.swiid)

[SwiidInter](http://www.swiid.com/en/produits.html#swiidinter)
[Graphics and logos](http://www.swiid.com/en/support/logos.html)
[Learning mode](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0bTVy1uBZ3_X3SpkhOohD-oO-fiuu66LJ_Xn2Gi0UPhaY56tO)
[Manual](http://www.swiid.com/medias/documents/ZCS-User-s-manual-vBAT2-02.12.2014.pdf)

Thanks!

**Comment by IvoDerksen** [comment]
Sure! 
I'll try and finish them in the coming days!

Thank you for the clear instructions!

**Comment by IvoDerksen** [comment]
Hello Glenn, 
com.swiidThe icons are finished. All the devices supported in the pack are created, so it's future proof!
Good luck on completing the app!

Kind regards!
Ivo
