### ISSUE TITLE
sma.modbus

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#31]
Hi Ivo, could you create a svg icon for a SMA Sunny Boy inverter. Below is an example image: 

https://www.alternagy.co.za/wp-content/uploads/2017/07/Sunny-Boy-Inverter-5.0KW-AV40-2.jpg

Thanx in advance.

**Comment by IvoDerksen** [comment]
Hey Jelger, It will be coming up today or tomorrow!

**Comment by IvoDerksen** [comment]
Finished! Good luck on completing the app!

**Comment by jghaanstra** [comment]
Awesome as always, thanx again!

**Comment by IvoDerksen** [comment]
Will remove the logo icon, since you've already have one!

**Comment by jghaanstra** [comment]
I used an online converter for that. I just downloaded yours and have overwritten it.

**Comment by IvoDerksen** [comment]
Ah, ok! Thanks for letting me know!
Happy coding on the SMA Sunnyboy! 
Just curious, is it the inverter for the IKEA solar system(the connected one)?

**Comment by IvoDerksen** [comment]
Ah, nice! Well then I'll probably see a few other issues then ;)

**Comment by jghaanstra** [comment]
I don't hope so. I will use one driver to support multiple inverters. The current icon is pretty generic for all SMA inverters.

**Comment by IvoDerksen** [comment]
Ah ok!  Good luck!
