### ISSUE TITLE
com.rainforestautomation

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#32]
Would it be possible to get the SVGs of the Eagle-200 by rain-forrest automation.

Thanks

https://rainforestautomation.com/rfa-z114-eagle-200-2/

**Comment by IvoDerksen** [comment]
Yes, coming up today or tomorrow!

**Comment by IvoDerksen** [comment]
It's done!
Good luck on completing the app!
I've also added the logo for an app icon.
