### ISSUE TITLE
com.xiaomi-mi-zigbee/ new (default) capability icons

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#34]
Hi Ivo,

For the new Aqara vibration sensor, I'm looking for some new capability icons; that likely will become new default capabilities...

Alarm icons:
alarm_vibration : alarm when the sensor detects a vibration
alarm_tilt: alarm when the sensor detects that it has been tilted
alarm_drop: alarm when the sensor detects that it has been dropped

Measure icons:
measure_vibration: actual vibration detected
measure_tilt: actual tilt angle detected

Can you create these icons for me? 
Adding them to the com.xiaomi-mi-zigbee/ folder would be ok.

Thanks, Ted

**Comment by IvoDerksen** [comment]
Hey Ted!
I'm currently assigned the job to redo all capability icons, I've added yours to the list. This might take a bit more than a week!
I'll keep you updated and put them in the repo when they are done!

**Comment by TedTolboom** [comment]
Hi @IvoDerksen,
To set my expectations, when do you think you would be able to deliver these icons?

The device driver is ready in the meantime... so the choice I have to make is to either deliver a first update with temporary icons or delay the app update and wait for the icons...

I would prefer to include the final icons.

Thanks Ted

**Comment by IvoDerksen** [comment]
Hello Ted, it will be at least at the end of this week, but I expect Monday next week the capability icons will be ready.
So I'll let you know when they are done!

**Comment by IvoDerksen** [comment]
Hey Ted, 
I'm finishing the icons, but I'll let them pass internally before release, because of it probably being default icons! So Thursday morning, or Wednesday afternoon I'll commit them!
Sorry for the delay!

**Comment by IvoDerksen** [comment]
Here is a teaser though!
<img width="621" alt="screen shot 2018-09-25 at 23 03 21" src="https://user-images.githubusercontent.com/22196684/46043061-402e8800-c117-11e8-89c1-3c526523ff40.png">

**Comment by IvoDerksen** [comment]
Hey Ted, I have to refine the Tilt icon.
So therefore tomorrow all will be committed.

**Comment by IvoDerksen** [comment]
[Capability icons.zip](https://github.com/athombv/homey-vectors-public/files/2428642/Capability.icons.zip)

These are the icons for the capabilities. There are alarm booleans, so active, non active and measure icons have one state.

There you go!
Now I'll go after your other issue. This weekend I hope it's done!
