### ISSUE TITLE
no.thermofloor/ new device icons

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#35]
Yep.... 

Extending the empire further... 

Are you able to create new (fancy) icons for the new ThermoFloor / Heat-it devices:
https://www.heatit.com/z-wave/heatit-z-din-616/   -> I could re-use / slightly alter https://github.com/TedTolboom/dk.logichome/blob/development/drivers/LHC5028/assets/icon.svg but if you have a better suggestion, please let me know
https://www.heatit.com/heating-control/water-based-heating/hatit-z-water/

https://www.heatit.com/heating-control/snow-smelting-automation/heatit-z-ice-control/
https://www.heatit.com/z-wave/heatit-z-relay/
https://www.heatit.com/z-wave/heatit-z-scene-controller/   -> I could re-use https://github.com/TedTolboom/dk.logichome/blob/development/drivers/ZHC5002/assets/icon.svg
https://www.heatit.com/z-wave/heatit-z-dim/

https://www.heatit.com/z-wave/heatit-z-temp/
https://www.heatit.com/z-wave/heatit-z-stoveguard/

No particular rush on these icons... will start working on this app end of September

Thanks, Ted

**Comment by IvoDerksen** [comment]
Hey Ted, 
Sure thing! I'll update the existing versions to match the style a bit more. (fatter lines, more clear for the screens).
I'll schedule this for half september!

**Comment by IvoDerksen** [comment]
And this will be done this weekend!

**Comment by IvoDerksen** [comment]
Here you go!
You can also re use the scene controller in logichome if desired.

**Comment by TedTolboom** [comment]
Hi Ivo,
Thanks once more! Great artwork.

Ted

**Comment by IvoDerksen** [comment]
You're welcome!
