### ISSUE TITLE
magic.home.wifi

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#36]
And here we go again. This will be the last one for now.

Logo: https://is4-ssl.mzstatic.com/image/thumb/Purple117/v4/1d/30/0a/1d300aa7-fda4-cb68-d646-461b54ff5187/mzl.hrfyccgu.jpg/1200x630bb.jpg

LED controller: https://image.dhgate.com/0x0/f2/albu/g5/M01/50/41/rBVaJFiwMrOAQuTIAAF0mxI24PY857.jpg

**Comment by jghaanstra** [comment]
Thanx @IvoDerksen  ... fast and looking great as always!

**Comment by IvoDerksen** [comment]
You're welcome!
