### ISSUE TITLE
com.swttt.devicegroups

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#38]
Hi, i've added support for missing device classes to devicegroups app, and was wondering if it would be possible to get an icon for each of Athom's device classes.  

[
  "other",
  "socket",
  "light",
  "vacuumcleaner",
  "fan",
  "heater",
  "thermostat",
  "sensor",
  "kettle",
  "coffeemachine",
  "homealarm",
  "speaker",
  "button",
  "doorbell",
  "lock",
  "windowcoverings",
  "tv",
  "amplifier",
  "curtain",
  "blinds",
  "sunshade"
  "all"
]

![image](https://user-images.githubusercontent.com/239140/46421875-7e125880-c776-11e8-8398-d1f9b71a01bc.png)

This UI currently displays are a list, but I will be changing it to tiles. 

It is how capabilities are grouped, its important to give a visual representation to each of the device classes, as they can be confusing to (new) users. (blinds vs. sunshade vs. windowcovering) or even what a socket is. 

Thank you.

**Comment by IvoDerksen** [comment]
Hello Jamie, 

I need to discuss this first. Since I will probably do all then.
But I think I will be working on this ASAP.
I'll start sketching this week!

Since these are a few, it'll take me some time!

Kind regards,
Ivo

**Comment by hive** [comment]
Hi Ivo, 

I'm excited to see what we end up with.

Thank you.

**Comment by IvoDerksen** [comment]
Hey Jamie,

I'm going to digitalize the sketches this week.
I hope they are done this week. I'm aiming for Thursday, but could also be Friday or Saturday!

**Comment by hive** [comment]
Can't wait, 

Thanks

**Comment by IvoDerksen** [comment]
Jamie, I haven't had enough time, since I underestimated the amount of work. Still working on this! I'm hoping I can release them all in the coming days. Sorry for the delay!

**Comment by hive** [comment]
Hi Ivo, 

No problem, its a big task, if there is anything I can do to help please don't hesitate to let me know. 

Thanks for you help

**Comment by hive** [comment]
Hi Ivo, 

I was just wondering if you have an updated ETA on the icons?

**Comment by hive** [comment]
Hey, 


1) The difference between sunshade, blind and window covering. 

> Blinds : Device class for blinds, both horizontal and vertical. 

Currently we are using the following 

https://thenounproject.com/term/blinds/54950/

Something similar which matches the other icons selected would make sense. 

> Sunshade : Device class for sunshades (window coverings against the sun). 

I believe that the intention behind a sunshade was something similar to

![image](https://user-images.githubusercontent.com/239140/47718700-23005280-dc9d-11e8-9f97-c7b2e8b8df1d.png)


But i'm just guessing. 

> Window Covering : "Device class for window coverings, when the `curtains`, `blinds` or `sunshade` device class doesn't apply."

I believe this is a more generic icon, for 'anything else', perhaps if the icon's focus is the 'window' itself rather then attempting to guess what it will be. ie. 

https://thenounproject.com/search/?q=window

Will be most helpful to users.

---


2) The sensor icon is a tricky one, as it can be so many things, there are three options : 

a) Something generic like this  https://thenounproject.com/term/timer-light/1467915/
b) Something abstract like this https://thenounproject.com/search/?q=sensor&i=614179
c) An example of a sensor like this https://thenounproject.com/search/?q=sensor&i=591262

I think my preference in this case is something like "b". 

---

3. Other is actually not that important (in homey v1) as it doesn't actually have any capabilities and thus will be empty. So what ever you believe is best, empty, the app icon, perhaps something related to smart devices or connected devices. 

---

The amplifier is looking great, ill have a think about the icons and update this issue if I have any ideas pop up. 

Thanks!

**Comment by IvoDerksen** [comment]
Jamie, you have some say in a few options that I've created.

![button](https://user-images.githubusercontent.com/22196684/48020692-d1414780-e136-11e8-9b88-632564f6871f.png)
![heater](https://user-images.githubusercontent.com/22196684/48020693-d1d9de00-e136-11e8-8f86-e87506990168.png)
![lock](https://user-images.githubusercontent.com/22196684/48020694-d1d9de00-e136-11e8-94ba-5c04642fc25d.png)

**Comment by hive** [comment]
Hey Ivo, '

They look great, thanks!

In regards to the button, as it is not a 'toggle' then it should absolutely be the middle one, however I think we have to be careful that it doesn't look like a power button, as that could be confusing, at the moment its using the power icon. 

I like the second heater.

And I think the first lock is perfect, as we don't know whether it will have a door handle. 

---


Just a couple of things for the sake of consistency with Homey. 

home_alarm.svg should be homealarm.svg
vacuum.svg should be vacuumcleaner.svg
curtains.svg should be curtain.svg
window_coverings.svg should be windowcoverings.svg
outlet.svg should be socket.svg


Thanks!

**Comment by hive** [comment]
Sorry, 

I just noticed that the Tv and Amp icons don't seem to be sitting correctly on the vertical axis. 


<img width="174" alt="image" src="https://user-images.githubusercontent.com/239140/48073617-3ed29e00-e233-11e8-96c1-6549305862dc.png">

**Comment by IvoDerksen** [comment]
Thanks for the feedback!

Will change them, and the names tonight!

**Comment by IvoDerksen** [comment]
I've adjusted the alignment, names and choices in the repo.
Button has been changed by preference of Athom, so that one now looks like a single wall button of KaKu.
If there are no more remarks I'll close the issue!

**Comment by hive** [comment]
Ive included the icons and pushed, thank you again for your help.

**Comment by IvoDerksen** [comment]
Attached is the alteration. Blinds and coverings are now smaller, but all windows are roughly the same size!
[sized_windows.zip](https://github.com/athombv/homey-vectors-public/files/2561533/sized_windows.zip)

**Comment by IvoDerksen** [comment]
If there are any remarks, just comment! I'll close the issue!

**Comment by IvoDerksen** [comment]
Nice!
I really the more icon! 
And a universal remote icon I can manage!

Still working on the Philips issue, but will start after!

**Comment by IvoDerksen** [comment]
Hey Jamie, Thank you! You too! A Homey new year ;)

We've already incorporated these alarms in core, I believe.

The icon you've shown indeed is for a general device error, not an alarm.
I've created sensor capabilities icons for core and added alarm icons, for each capability, too. Like the tilt icon. (Example of motion is below)

I don't quite understand what you mean, do you want me to make alarm icons for all sensor capabilities? Or do you mean to say the icon of a tilt alarm looks too much like an unavailable icon?
The idea is a general device error is the alert/alarm icon you've sent, but a specific alarm of a sensor capability that is triggered is using that element, on top of the existing icon, as you can see below.

![motionalarm](https://user-images.githubusercontent.com/22196684/51026751-8fe27380-158f-11e9-90d8-3daf053201b3.jpg)

Can you clarify what you mean? 

Kind regards,
Ivo

**Comment by IvoDerksen** [comment]
Now I understand.
Is it an idea to use the alarm icon that is presented on the cards? It's a bit different, though uses the same point, and is more general.

Attached:
![alarm_option](https://user-images.githubusercontent.com/22196684/51241684-96516080-197e-11e9-8ce2-0ae3311ee801.png)

**Comment by IvoDerksen** [comment]
Here you go!

[general_alarm.svg.zip](https://github.com/athombv/homey-vectors-public/files/2764377/general_alarm.svg.zip)
