### ISSUE TITLE
com.hivehome enhancement

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey-vectors-public#4]
Currently the driver for Hive Active Heating is implemented as such that it adds two devices; one for the thermostat functionality (heating control) and one for the hot water control. The devices currently use the same icon (and different name) as can be seen in the attached screenshot, however it would be nice if the icons would reflect their functionality, like they do in the Hive smartphone app (see screenshot). To be clear; the devices are not physically different devices, they are both the device displayed in the current icon, but their functionality is different.

![screen shot 2017-02-16 at 5 06 23 pm](https://cloud.githubusercontent.com/assets/5762579/23029471/f1b20564-f46a-11e6-9117-6fac1624758d.png)

![img_2132](https://cloud.githubusercontent.com/assets/5762579/23029543/3632de02-f46b-11e6-8e53-28a814c79657.PNG)

**Comment by IvoDerksen** [comment]
Closed! See repo
