### ISSUE TITLE
com.heiman

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#40]
Hi Ivo,

Could you make the device icons and brand icon for the Heiman Z-wave (and Zigbee) devices?

For these devices:
https://products.z-wavealliance.org/Search/Index?regionId=-1&searchText=heiman

Each device has a "manufacturer provided manual" which shows a reference image of the device.
<img width="841" alt="schermafbeelding 2018-11-15 om 16 22 59" src="https://user-images.githubusercontent.com/17163431/48562587-ccc51d80-e8f2-11e8-8994-ef5ec86cfb5f.png">

If you want, I can add these screenshots myself for all devices. Let me know if that helps...

**Comment by TedTolboom** [comment]
en ja, weer een nieuwe projectje... ;-P

**Comment by IvoDerksen** [comment]
Hey Ted,

Yes!
Screenshots are great, PDFs are also very possible!

I'll update the repo continuously, I'm aiming for 1,5 weeks!
Greetings!

**Comment by IvoDerksen** [comment]
Ted, I'm counting 13 unique devices. Are you planning on implementing them all? Or can you place a screenshot of all the devices that will be supported in the first release?

**Comment by TedTolboom** [comment]
Hi Ivo,

The [first wave of devices](https://www.robbshop.nl/#sqr:(q[heiman])) I'll be adding will be:
HEIMAN HS1MS-Z: https://products.z-wavealliance.org/Search/ProductDetails?productId=1801
HEIMAN HS1CA-Z: https://products.z-wavealliance.org/Search/ProductDetails?productId=1940
HEIMAN HS1SA-Z: https://products.z-wavealliance.org/Search/ProductDetails?productId=1936
HEIMAN HS1CG-Z: https://products.z-wavealliance.org/Search/ProductDetails?productId=2070
HEIMAN HS1HT-Z: https://products.z-wavealliance.org/Search/ProductDetails?productId=3015

But the remaining 8 devices will follow within reasonable time.

And likely some more, since the Heiman product portfolio is rapidly expanding, see their [Z-wave devices](http://www.heimantech.com/product/intelligentgasalarm.html) and [Zigbee devices](http://www.heimantech.com/product/intelligentinfrareddetector.html).
Advantage is that they use the same housing for both Z-wave as Zigbee devices

**Comment by IvoDerksen** [comment]
Thank you! 
I'm on them asap, 1-2 weeks approx!

**Comment by IvoDerksen** [comment]
First batch is on the way.

**Comment by IvoDerksen** [comment]
If you could add screenshots of the remaining 8, or links as you did now are fine too!
I'll get on them too within a reasonable notice!

**Comment by TedTolboom** [comment]
Hi Ivo,

Great work again! Thanks.

Could you still add the following 5 (remaining) devices?
HEIMAN HS2SK-Z: https://products.z-wavealliance.org/products/2315
HEIMAN HS2SK-Z: https://products.z-wavealliance.org/products/1941

Including the latest additions:
HEIMAN HS3WL-Z: https://products.z-wavealliance.org/products/3027
HEIMAN HS3MS-Z: https://products.z-wavealliance.org/products/3026
HEIMAN HS3DS-Z: https://products.z-wavealliance.org/products/3016

Thanks, Ted

**Comment by IvoDerksen** [comment]
Yes! On it this week, or next week!

**Comment by IvoDerksen** [comment]
Ho ho ho... I mean happy holidays!
Added the last 5.

The metering and socket icon are the same, also device numbers. So I suggest putting that in the name. I'll probably discuss a visual difference in these kind of cases in the next year!
