### ISSUE TITLE
com.twinkly

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#41]
And another request ... Could I get icons for:

**Logo:** https://www.twinkly.com/wp-content/uploads/2018/08/twinkly-gold-padded.png

**Device:** https://www.twinkly.com/products/

Maybe something like this?: https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/6e/fc/54/6efc54b6-7bd6-920b-1328-f47f7c965524/pr_source.jpg/643x0w.jpg

**Comment by IvoDerksen** [comment]
Hey Jelger,

Cool I will, is it really as awesome and as instant as the video shows?
I'll think about the device icon, I like your suggestion!
Will be done after Shelly Plug S and Heimann, so I'm guessing 1-2 weeks.

**Comment by jghaanstra** [comment]
I cant fully comment on how awesome it is. I'm not using the my Twinkly LED string in a christmas tree but I create a flat tree by hanging the string on the wall in the shape of a tree. This way it's really awesome, you can even create custom patterns.

Dont worry about the timeline, I'll probably use crappy converted SVG icons first for the Twinkly app.

**Comment by IvoDerksen** [comment]
The logo is converted, it's in the repo.. It is zipped. Mentioned in the above commit!

**Comment by caseda** [comment]
Just for fun added information 😛 have twinkly now since last year's christmas, on an actual (big) tree it can be a bit finicky to get the lights synced properly (pretty much impossible with the long version) at least that was the case last year, it might have been improved in the mean while.

**Comment by IvoDerksen** [comment]
I can imagine the amount of offline 'calibration' needed haha.
But putting it on a wishlist for the future :) Thanks for sharing the experiences!

**Comment by jghaanstra** [comment]
I'm now using a converted logo as device icon and it's pretty good if you ask me. If you dont have much time to do this you can close this request and I'll stick with that one.

https://github.com/jghaanstra/com.twinkly/blob/master/drivers/twinkly/assets/icon.svg

**Comment by IvoDerksen** [comment]
I'll keep it open! If you want to update the app before christmas you can.
But thanks! I also think it's pretty good illustrating the tree!
I'm planning the icon to look like:
![twinkly_okos_karacsonyfa_fenyfuzer_105_led_4](https://user-images.githubusercontent.com/22196684/48962177-d0087b00-ef7c-11e8-9787-72dddc374e80.jpg)

But yours now is nice too!

**Comment by IvoDerksen** [comment]
Hey Jelger!
I'll close it for now, when the app is updated with new devices, i"ll update the repo!
You know where to find me!
