### ISSUE TITLE
nl.philips.hue

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#42]
Hey Ivo!

I'm looking to do a quick PR/Alt to the Athom Philips Hue App in order to add the following features/globes. 

---

The first is to add support for the LLC001 Lamp, 

https://github.com/athombv/homey/issues/2775

[Image of LLC001](https://thegadgetflow.com/wp-content/uploads/2013/05/Philips-LivingColors-Translucent-Changing-LED-Lamp-3.jpg)

Its worth noting that the  LCC010 (iris) was an updated LCC001, with an added band at the top, and the app currently has the LCC010 [Icon](https://github.com/athombv/nl.philips.hue/blob/master/drivers/bulb/assets/icons/LLC010.svg). 

---

The second is to add support for the candle globes (LCT012 and LTW012)

https://github.com/athombv/homey/issues/2800

[Image of LCT012](https://images-na.ssl-images-amazon.com/images/I/81Z59PBP5LL._SX425_.jpg)

Attached are the official pdf from Phillips Developer Program. (Unfilled/Filled)
[e14.pdf](https://github.com/athombv/homey/files/2369369/e14.pdf)
[e14.pdf](https://github.com/athombv/homey/files/2369362/e14.pdf)

[SVGS.zip](https://github.com/athombv/homey-vectors-public/files/2618126/SVGS.zip)

**Comment by IvoDerksen** [comment]
On them! Could be a week though before it's done, I've already got a candle icon made, will be in the repo.
I think you mean an Iris, instead of the bloom right? Doesn't matter, I'll update and add that icon too coming week!

**Comment by hive** [comment]
Hi Ivo,

You were right, I got my modal numbers / names a bit mixed up. Ive updated the ticket. Thanks!

![image](https://user-images.githubusercontent.com/239140/49235170-9ab4cf00-f44d-11e8-9e53-c2bb7961ddfb.png)

The candles are all done, and pushed, the only thing I noticed while I was doing this was that the Hue White also doesn't have the right Icon. This is the cheapest one, that only dims, and it looks the most like a traditional light globe. 

![image](https://user-images.githubusercontent.com/239140/49233826-f598f700-f44a-11e8-9909-a51be3b895b4.png)


 
If you get a chance, I would be happy to also add the icon as well, while I am doing these others as it is the most common globe. (You get one free with ever echo)

**Comment by IvoDerksen** [comment]
Hey Jamie, here you go.

I'll not update the public repo, as I'll pass them to Athom's repo!
So please use the attached files below!

[light_hue_white_e27.svg.zip](https://github.com/athombv/homey-vectors-public/files/2661049/light_hue_white_e27.svg.zip)
[light_LLC001.svg.zip](https://github.com/athombv/homey-vectors-public/files/2661050/light_LLC001.svg.zip)

**Comment by hive** [comment]
Hey, thanks they all look great have been pushed and are just awaiting Athom :)

https://github.com/athombv/nl.philips.hue/pulls

Are there any other icons you which I can upgrade while I am working on this?

---
My attempt at making the sultan globe in the same style
---

![image](https://user-images.githubusercontent.com/239140/49782403-4d4c3200-fd6a-11e8-8842-9efc743eaa1c.png)

---
My attempt at making the g10 globe in the same style
---
![image](https://user-images.githubusercontent.com/239140/49782777-9c469700-fd6b-11e8-90af-7ab317334667.png)

**Comment by IvoDerksen** [comment]
Very nice, they fit the style indeed!

I still have the source files and can tweak them a bit more. So if you want I can change these two slightly as well. For a next small update :)

For a nice good to know: This was one of my first five icons I did for Athom :)

**Comment by hive** [comment]
Sounds great! My work could use a lot of help!

**Comment by hive** [comment]
Hey Ivo, did you ever get a chance to tweak the icons?

**Comment by IvoDerksen** [comment]
Hey Jamie, not yet!
I was other ways engaged this week. I'm picking up the sultan and GU10 this week!

**Comment by hive** [comment]
Hi Ivo, 

I have the Philips Hue Pedestal (LCF005) and I am looking add it to the Hue App but I need an Icon. 

https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/271283-L-LO.jpg

Is this something you can help with?

Thanks

**Comment by IvoDerksen** [comment]
Hey Jamie, 

Yes, consider it done. Will be available tomorrow!

**Comment by IvoDerksen** [comment]
Just checking, no april fools right ;)

**Comment by hive** [comment]
No April Fools :-) April 2nd here.

Just a heads up I also got a Lily (50% off hue lights sale), but I haven't added it to yet, so maybe there already is an icon?

https://cdn.shopify.com/s/files/1/2986/1338/products/1744930A7-RTP-global-001-lily1_1024x1024@2x.png?v=1550217289

**Comment by IvoDerksen** [comment]
Haha, good to know!

There is no lilly, so it's added to the list!

**Comment by IvoDerksen** [comment]
There you go Jamie!

**Comment by hive** [comment]
Hey Ivo!

It's been a while, I hope you have been well.

I'm looking to add the Hue Ambiance Downlight (LTD001). 

![image](https://user-images.githubusercontent.com/239140/63696750-b8895600-c85e-11e9-965d-71153a13d7d2.png)

![image](https://user-images.githubusercontent.com/239140/63696766-c2ab5480-c85e-11e9-8cb8-5bbc951fe31b.png)

Please let me know if there is anything I can do to help. 

Thanks

**Comment by IvoDerksen** [comment]
I am thank you, and hopefully you too!

I'm on it Jamie! Will be done before the weekend!
Thanks for your input!

**Comment by IvoDerksen** [comment]
Here you go!

Happy coding! & Controlling ;)
