### ISSUE TITLE
be.uwsoftware.max

### ISSUE THREAD

**Issue by dolfje** [athombv/homey-vectors-public#43]
The implementation is found on https://github.com/dolfje/be.uwsoftware.maxcube
I need a logo:
![eq3](https://user-images.githubusercontent.com/2472049/50487042-f2b70500-09fc-11e9-8ae1-4c588f961c16.png)
(Maybe with the cube itself in the background:
![image](https://user-images.githubusercontent.com/2472049/50487099-2eea6580-09fd-11e9-9f44-3ba78b83c05a.png)

And also the devices:
![image500x500](https://user-images.githubusercontent.com/2472049/50487075-08c4c580-09fd-11e9-9d16-6016020be116.jpg)
![image500x500](https://user-images.githubusercontent.com/2472049/50487076-08c4c580-09fd-11e9-9c6c-1640e98baba8.jpg)
![image500x500](https://user-images.githubusercontent.com/2472049/50487077-08c4c580-09fd-11e9-95dc-d40276f2f273.jpg)

The others will follow later:
![image](https://user-images.githubusercontent.com/2472049/50487131-4fb2bb00-09fd-11e9-95dc-9f813c274928.png)
![image](https://user-images.githubusercontent.com/2472049/50487136-57725f80-09fd-11e9-8b6a-93f87a279ea9.png)

Is this enough information or should I add more?

**Comment by IvoDerksen** [comment]
Hello! I'll be on them in the new year! The information is sufficient, so you can just wait till I'm done!

**Comment by IvoDerksen** [comment]
Sorry it took a while. Here they are attached to the commit below!
