### ISSUE TITLE
Icons for WeatherFlow

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-vectors-public#44]
Devices are the Sky, Air and the Hub

https://goo.gl/images/5ZKB5P

http://weatherflow.com/smart-home-weather-stations/

Maybee also a icon for a future device so its already there the Breath

**Comment by IvoDerksen** [comment]
Yes, expect them this weekend.
Will also make the breath for the future.

**Comment by mruiter** [comment]
No hurry the app is far from working ;)

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
forgot the app name for thefolder name.
well who would have guessed it wil be com.weatherflow 🤟

**Comment by IvoDerksen** [comment]
Hey!

I've finished the icons!
Logo (2 versions) and weather icons are added!
