### ISSUE TITLE
Icon for Synology Surveillance Station

### ISSUE THREAD

**Issue by jordenc** [athombv/homey-vectors-public#45]
For the https://apps.athom.com/app/com.synology.surveillance app, I would like to use a better icon for the device, which is a webcam, and for the driver.

The current icons I use don't display so well.

**Comment by IvoDerksen** [comment]
You mentioned "and for the driver", do you mean you need another icon or is this sufficient?

**Comment by IvoDerksen** [comment]
Ah well, then I'd still using the synology icon as app icon. I'll update this tonight!

**Comment by IvoDerksen** [comment]
Hey! I'd recommend the logo as app icon, since it is more recognisable than a webcam icon. Then the driver I've made is the icon for the surveillance station.

[synology.zip](https://github.com/athombv/homey-vectors-public/files/2780073/synology.zip)

**Comment by jordenc** [comment]
Thanks a lot Ivo! The second driver icon even looks better :) I will use the logo as the app icon and the new cam icon as the driver icon.
