### ISSUE TITLE
Icon for com.sony.bravia.smarttv

### ISSUE THREAD

**Issue by Retrospected** [athombv/homey-vectors-public#46]
i'm looking for a new icon for the sony bravia smarttv app.

in homey 1.x i used this icon but it doesnt really scale very nice in the homey v2 app:
https://github.com/Retrospected/com.sony.bravia.smarttv/blob/f03f78d94f3b87253b9d13460a5696a9b5d935c7/assets/icon.svg

homey app link: https://apps.athom.com/app/com.sony.bravia.smarttv
github link: https://github.com/Retrospected/com.sony.bravia.smarttv/

thanks in advance!

**Comment by IvoDerksen** [comment]
I'd suggest to use the same icon as app icon. I've edited it, so it's maximised properly.
Also created a more appealing driver icon!

[sony_bravia.zip](https://github.com/athombv/homey-vectors-public/files/2777046/sony_bravia.zip)

Kind regards!

**Comment by Retrospected** [comment]
awesome :) thx !
