### ISSUE TITLE
Telldus - svg-icon (Z-wave)

### ISSUE THREAD

**Issue by yhaugom** [athombv/homey-vectors-public#47]
Icon keeps getting whitespace on the right and at the bottom in the converter I use. Could you please help me create a new icon without the white space? 
![img_0731](https://user-images.githubusercontent.com/1016457/51760923-fc02c280-20cb-11e9-84c6-137cdb93dc95.jpeg)

![telldus_logo](https://user-images.githubusercontent.com/1016457/51760834-c362e900-20cb-11e9-974e-23746a691c8f.png)

**Comment by IvoDerksen** [comment]
Here you go! Enjoy!
Happy coding!

[app_icon.svg.zip](https://github.com/athombv/homey-vectors-public/files/2797173/app_icon.svg.zip)

**Comment by yhaugom** [comment]
Thank you! :)
