### ISSUE TITLE
Publish Zone Icon here?

### ISSUE THREAD

**Issue by specialcircumstances** [athombv/homey-vectors-public#48]
Hi. So far as I can see there is no way to reference a zone icon (I need this for my settings pages).

`Cannot GET /manager/zones/assets/icons/home.svg`

So, unless there is a new path I can use to include them, if they could be published here I can at least copy them into my apps assets. Would of course be better to get the URL from the zone objects though...

Thanks :)

**Comment by WeeJeWel** [comment]
The zone icons are not publicly available.
