### ISSUE TITLE
com.greenwavesystems powernode-5

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#5]
Hi Ivo,

For adding the Greenwave Powernode-5 device to the app, I would like to request a new proper vector image for the Powernode-5 (UK and 5 port version of the Powernode-6) 

Device image
![powernode_2_ok](https://cloud.githubusercontent.com/assets/17163431/24326114/94cff946-11a7-11e7-8def-9ce335325450.jpg)

Option could be to re-use the Greenwave Powernode-6 vector image and replace the 6 schuko sockets with an insert with 5 (! not 6) UK sockets.

Much appreciated, Ted

**Comment by IvoDerksen** [comment]
Hello Ted, 
Thanks for integrating the PowerNode 5, I've altered the existing icons to this version.
You can find them in the Repo!

**Comment by TedTolboom** [comment]
Hi Ivo, great work... wouldn't come close to this level of quality if I had to do it myself..

**Comment by IvoDerksen** [comment]
Thank you Ted!
Glad to help achieving awesome goals!
