### ISSUE TITLE
Keywe SVG

### ISSUE THREAD

**Issue by uzumaki378** [athombv/homey-vectors-public#53]
Hi will need help with 3 svg icon for Keywe

1 for homey apps icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgar4zVGEiL80suTPQKMe-eQPxQbk8Sb9ayB5MsKtYsvFxm_BZ

1 for device : https://ksr-ugc.imgix.net/assets/022/189/794/25943b7852266da779f95ca23b94330a_original.png?ixlib=rb-1.1.0&w=639&fit=max&v=1533918761&auto=format&gif-q=50&lossless=true&s=ba2fe3b3f66438fe4204ba24a8628fb1

1 for learn mode: https://imgur.com/a/YE8pezl

Thanks in advance for the help

**Comment by IvoDerksen** [comment]
Here you go! Happy coding!
