### ISSUE TITLE
SVG icon for ambi climate & Sensibo

### ISSUE THREAD

**Issue by uzumaki378** [athombv/homey-vectors-public#54]
Hi IvoDerksen thanks for the keywe svg icon.

Will need help again for Ambi climate & Sensibo

Ambi climate:
Logo : https://pbs.twimg.com/profile_images/885334062914707456/LR4LlM2b_400x400.jpg
Device SVG: https://www.fortress.com.hk/medias/11663467-11663467.jpg?context=bWFzdGVyfGZyb250em9vbXwzMTM3MDB8aW1hZ2UvanBlZ3xmcm9udHpvb20vaDA5L2hlMy84ODEzNTE2OTgwMjU0LmpwZ3xkN2IyOWFjZmIwZjA1ZWU5YTkwMjYxZGUyYWIwODYyN2VmZTViMjc3MzYyNGRmMDVhY2U5Y2IyNDcyNmU0ZTcw 

Sensibo:
Logo: https://m.media-amazon.com/images/S/abs-image-upload-na/c/AmazonStores/ATVPDKIKX0DER/d6b008ef6263f74632a58ad166b2685f.w1000.h1000.png
Device:https://onefantasticshop.com/4498-large_default/sensibo-sky-smart-air-conditioner-controller-sensibo-sky.jpg

Thanks in advance

**Comment by IvoDerksen** [comment]
Nice products, will look at them asap! I expect them to be done friday!

**Comment by uzumaki378** [comment]
Hi IvoDerksen Sorry for the inconvenience you can remove the Sensibo logo from your busy schedule. Just realize someone already did the apps.

Many thanks

**Comment by IvoDerksen** [comment]
No problem! Thank you for informing me!

**Comment by IvoDerksen** [comment]
Here you go!
