### ISSUE TITLE
SVG device icon for Slide

### ISSUE THREAD

**Issue by jordenc** [athombv/homey-vectors-public#56]
nl.innovationinmotion.slide (https://apps.athom.com/app/nl.innovationinmotion.slide)

I would love to replace the curtains-icon with one that shows the Slide device (https://cdn.shopify.com/s/files/1/0015/1243/9872/files/7-1400x1300-2.jpg?1132)

**Comment by IvoDerksen** [comment]
Sure, will get on it this week. Expect it this week :)

**Comment by IvoDerksen** [comment]
Expect it now!
Here you go!

**Comment by jordenc** [comment]
Thanks a lot!
