### ISSUE TITLE
com.homeconnect

### ISSUE THREAD

**Issue by BertvanHoekelen** [athombv/homey-vectors-public#57]
com.homeconnect https://apps.athom.com/app/com.home-connect

Can you create an icon for this hood or similiar home connect hood: https://www.siemens-home.bsh-group.com/nl/productoverzicht/koken-en-bakken/afzuigkappen/wandschouwkappen/wandschouwkappen-recht/LC97FVQ60S

See for more information: https://github.com/athombv/com.home-connect/pull/6

**Comment by IvoDerksen** [comment]
Hey there! It's fixed. 

Oddly enough I didn't receive an email or it didn't catch my attention 4 days ago.

Sorry for that.

It is fixed in this commit:

**Comment by BertvanHoekelen** [comment]
For reference: 764f4ab14e9882b6c51d7482475340edea9b0fed
