### ISSUE TITLE
Icons for PM1, PM10 and VOC

### ISSUE THREAD

**Issue by rickardp** [athombv/homey-vectors-public#58]
For use with capabilities.

There is already an icon for PM2.5, and I suppose the others should look just like it.

**Comment by IvoDerksen** [comment]
Hey there! These are done. The icon of the Electrolux will be done within a few days!
See commit below!

**Comment by rickardp** [comment]
Brilliant, thanks! Just a question, are they intentionally smaller than PM2.5, or should I do something when integrating them?

![IMG_9B0758608971-1](https://user-images.githubusercontent.com/167356/57326901-cf6c3700-710d-11e9-9c63-41d864a4cb8f.jpeg)

**Comment by rickardp** [comment]
Never mind, the "artboard" tool in Illustrator seems to have taken care of it. My Illustrator skills are not exactly great, but it seems to have done the job :)

**Comment by IvoDerksen** [comment]
Thank you, I've delivered the icons as I've delivered the previous ones to Athom, so I'm guessing the artboard indeed was off! Thanks for fixing it :)

**Comment by IvoDerksen** [comment]
I've created the alarms of these icons too.

You can find them in the mention below!

**Comment by birsanandrei** [comment]
> For use with capabilities.
> 
> There is already an icon for PM2.5, and I suppose the others should look just like it.

hi guys.
where can I find this PM2.5 icon? I've been looking everywhere for it

**Comment by daviwil2** [comment]
The PM2.5 icon is native to Homey, you use define it as capability `measure_pm25` and Homey will automatically display the icon for that. If you still want the SVG file then you'll need to email Athom and as them for it as, as a matter of policy apparently, they don't post them here.
