### ISSUE TITLE
Device icon for Electrolux Pure A9

### ISSUE THREAD

**Issue by rickardp** [athombv/homey-vectors-public#59]
The device has got a pretty special pentagonal shape.

https://www.electroluxhome.se/Temp/d1928686aae04046ae0d45f129f46efc-1742229961.aspx
https://news.microsoft.com/transform/electrolux-smart-air-purifier-breathe-easy-polluted-cities/
https://hiveminer.com/Tags/a9%2Celectrolux

**Comment by IvoDerksen** [comment]
Here you go!
