### ISSUE TITLE
hk.com.remotec initial icon set

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#6]
Hi Ivo,

Could you do me another favour to create a nice icon set for a new Remotec app; specifically for the Remotec Scene master..
![scene-master-zrc-90](https://cloud.githubusercontent.com/assets/17163431/25375294/8fadc4f0-29a0-11e7-9832-1f2f4ff71c64.jpg)

Remotec Scene master device icon (taken from manual, need to be resized)(icon.svg):
![icon_remotec_zrc-90](https://cloud.githubusercontent.com/assets/17163431/25375017/b6ad3258-299f-11e7-9c1e-9cb0ca99a9e7.jpg)

Learn / unlearn icon (taken from manual, coarsely removed some arrows) (learnmode.svg):
Made in China / CE mark might be removed
<img width="908" alt="icon_remotec_zrc-90_learnmode" src="https://cloud.githubusercontent.com/assets/17163431/25374873/4e74d1b4-299f-11e7-92b3-a77180c6e646.png">
Important is that the W R L buttons are clearly visible, L button needs to be highlighted for inclusion

Brand / app icon (icon.svg):
<img width="624" alt="remotec" src="https://cloud.githubusercontent.com/assets/17163431/25375167/1fc75a8e-29a0-11e7-9d19-0979dec0af0a.png">

Device images (for reference):
Remotec App (large.jpg):
![large](https://cloud.githubusercontent.com/assets/17163431/25375250/67e547a4-29a0-11e7-886c-583194551c9d.jpg)

ZRC-90 Scene master (large.jpg):
![large](https://cloud.githubusercontent.com/assets/17163431/25375261/70a2e126-29a0-11e7-8395-d00295f84410.jpg)

Much appreciated!

Ted

**Comment by IvoDerksen** [comment]
Completed!
Good luck on completing your app!
Regards,
Ivo
