### ISSUE TITLE
Icon for "filter life" capability

### ISSUE THREAD

**Issue by rickardp** [athombv/homey-vectors-public#60]
Like HEPA filter or dust filter. Request is for an app for an air cleaner, but maybe it would also be applicable for robot vacuums etc (my Xiaomi vacuum has the concept of remaining filter life at least, but the Homey app doesn't expose it currently).

**Comment by rickardp** [comment]
Something like this maybe?
https://www.shutterstock.com/image-vector/air-filter-effect-black-symbol-vector-462412087?src=I_wtu7sg3mI4RQcqFzfGEw-1-0

or this?
https://www.pngkey.com/detail/u2q8i1u2e6w7w7i1_icon-airfilter-air-filter-clip-art/

Whatever fits the Homey app design language best :)

**Comment by IvoDerksen** [comment]
Filter life is like a battery level right? e.g. A percentage?

I can tackle this when I'm doing the Electrolux purifier!

**Comment by rickardp** [comment]
Yes, on the Electrolux it is a percentage remaining. IIRC some devices use time remaining instead of a percentage, so if you intend to create a generic icon it mat be worth considering.

**Comment by IvoDerksen** [comment]
<img width="642" alt="Screenshot 2019-05-15 at 15 36 50" src="https://user-images.githubusercontent.com/22196684/57779892-5bdab300-7727-11e9-86dd-ad71248d9fff.png">

Do you like/identify this for filter life?

**Comment by rickardp** [comment]
Nice! For me, the left one came off more clearly as a filter at a first glance.

**Comment by IvoDerksen** [comment]
Yes, I agree. But I was capturing the filter life. So should I add the 'dirt' particles to the right too?
It is supposed to be a degraded filter.

**Comment by rickardp** [comment]
I think the particles makes it clear it is a filter. And usually “degraded” means “dirty” I guess, but showing this may not be needed, as I would expect a brand new filter not to show as degraded even if I understand your intent. It would be cool to change the icon the more degraded the filter was, but I don’t think the Homey supports this.

Another thought, would it be more clear it is a filter if you turned the lines 90 degrees? But maybe you already tried and rejected that. I have a hard time imagining in my head now how that would look.

**Comment by IvoDerksen** [comment]
The left it is, when turning it 90 degrees, so upside down it looks like gravity and bubbles. 
The left to right of this icon represent the active filtering best imho!

**Comment by rickardp** [comment]
I meant the stripes on the filter, not the entire filter. But never mind, the left icon looks great in the app. Thanks!
