### ISSUE TITLE
com.arlo

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#61]
Hey, 

I've created a new app which allows users to add the Arlo Cameras to Homey.

It would be really helpful if you could help me with the icons, i'm going to start with the wireless cameras and base stations. 

There are four camera base stations. 

1) Arlo Base Station (VMB3000).

![image](https://user-images.githubusercontent.com/239140/58378547-eef1d380-7fd8-11e9-95cc-127348704fba.png)

2) Arlo Pro Base Station (VMB4000)

![image](https://user-images.githubusercontent.com/239140/58378559-34ae9c00-7fd9-11e9-8fc1-6444c8f580f3.png)

3) Arlo Pro Base Station v2 (VMB4500)

![image](https://user-images.githubusercontent.com/239140/58378602-f5cd1600-7fd9-11e9-8e4a-9c4612955e91.png)

4) Arlo Ultra Base Station (VMB5000)

![image](https://user-images.githubusercontent.com/239140/58378608-05e4f580-7fda-11e9-8660-fcf30fddf29b.png)

---

And I will be adding support for 4 cameras to start with : 

1) Arlo Camera(VMC3030)

![image](https://user-images.githubusercontent.com/239140/58378704-9839c900-7fdb-11e9-97b4-9759b6735bf1.png)

2) Arlo Pro Camera (VMC4030)

![image](https://user-images.githubusercontent.com/239140/58378677-1f3a7180-7fdb-11e9-9c44-5e09a6b5b43e.png)

3) Arlo Pro 2 Camera (VMC4030P)

![image](https://user-images.githubusercontent.com/239140/58378639-84da2e00-7fda-11e9-99b2-8b4cc5b8686b.png)

4) Arlo Ultra Camera (VMC5040)

![image](https://user-images.githubusercontent.com/239140/58378666-f3b78700-7fda-11e9-8bbb-f180ce8006de.png)

---

If there is anything i can do to help please let me know, 

Thank you!

**Comment by IvoDerksen** [comment]
Hey Jamie, 

I'll give you an Arlo camera icon this week for neat testing! But... the rest unfortunately is possible after next weekend, due to limited time and a short holiday.

**Comment by hive** [comment]
Thanks Ivo!

**Comment by IvoDerksen** [comment]
Hey Jamie, I got a bit delayed, I expect the coming days, for the rest of the icons. 
Sorry for the delay.

**Comment by hive** [comment]
No problem Ivo. Have a great weekend.

**Comment by hive** [comment]
Would it also be possible to get a capability icon for 'sound alarm' for this app? 

A sound alarm is triggered when the camera detects sound. 

Thanks

**Comment by IvoDerksen** [comment]
Hey Jamie, the icons have been made.
For sound we use the term noise, and we measure that currently.

I'll have to think about a sound alarm, because an volume icon with an alarm is a bit ambigues.
Let me check back soon!

**Comment by hive** [comment]
Thanks Ivo, ive brought the cameras in and they are looking great. 

Your right about the sound alarm it could be tricky. 


---


![image](https://user-images.githubusercontent.com/239140/59834340-34f94780-938b-11e9-9ee1-284142f29133.png)

![image](https://user-images.githubusercontent.com/239140/59834370-404c7300-938b-11e9-8d4a-6aa711e82929.png)

![image](https://user-images.githubusercontent.com/239140/59834422-54907000-938b-11e9-8f13-78172889ef67.png)


![image](https://user-images.githubusercontent.com/239140/59834450-5e19d800-938b-11e9-9ef4-d67322f283e0.png)

![image](https://user-images.githubusercontent.com/239140/59834617-9d482900-938b-11e9-8b54-85e1b5708dba.png)

**Comment by IvoDerksen** [comment]
Hey Jamie, I've also added alarm_noise.svg
We already have a DB (noise) measure icon.

So I've used that one for consistency. 
I find the first three the best, but for consistency adapted an already used Icon.

As a bonus I've added the DB measure icons I'd prefer too, but they must be clear to other users too.
Let me know what you think!

**Comment by hive** [comment]
Hey Ivo, I think I will use option 2 if that's ok with you, it also means if I get around to adding their baby camera ill already have the db_measure. 

I've put in a request to get a new 'system' capability to show that a device is charging however I would like to keep moving forward. 

It would be great to grab your thoughts, obviously something like this make sense : 

![image](https://user-images.githubusercontent.com/239140/59838941-2f076480-9393-11e9-8fd3-762946b4fef7.png)

But thats already being used by the battery_alarm_false. I though perhaps a cable with a battery but thats commonly used by apple to show a dead battery : 

![image](https://user-images.githubusercontent.com/239140/59839252-b0f78d80-9393-11e9-8aee-002fb39b2def.png)

![image](https://user-images.githubusercontent.com/239140/59839282-be147c80-9393-11e9-8f0f-e561e5d36013.png)

Any thoughts?

**Comment by IvoDerksen** [comment]
That's certainly ok with me.

Regarding the icons for charging, I'm looking at it today and hopefully I can also finalise an icon!

**Comment by IvoDerksen** [comment]
Hey Jamie,

I designed a plugged in icon. It does not state charging per sé, but I think it can be used even broader. When plugged in and you do not use the battery(alarms with backup battery), but there is also a state ofcourse where the battery can also be charged. You can refer this issue to your request/add the icon there. It's not my call if it makes it or not.

Kind regards!

**Comment by hive** [comment]
Its great, thank you! 

Have a awesome week!

**Comment by IvoDerksen** [comment]
You too!
