### ISSUE TITLE
com.heiman HS1CG 

### ISSUE THREAD

**Issue by mapulu** [athombv/homey-vectors-public#62]
Hello, could you create an icon for Heiman HS1CG Smart Combustible Gas Sensor?

http://www.heimantech.com/product/82.html

![Heiman](https://products.z-wavealliance.org/ProductImages/Index?productName=ZC10-16125343)

**Comment by IvoDerksen** [comment]
It's already available here!
[com.heiman/sensor_HS1CG-Z.svg](https://github.com/athombv/homey-vectors-public/blob/master/com.heiman/sensor_HS1CG-Z.svg)

Happy coding!

**Comment by mapulu** [comment]
Sorry didn't saw that.

I also need a custom capability icon for gas. (Methane - CH4)
Maybe like the CO Icon but with CH4

**Comment by IvoDerksen** [comment]
Will provide you with one tonight!

**Comment by IvoDerksen** [comment]
Here you go, I've also added the alarm and the alarms for PM1 - PM10 and VOC, I don't know if they are applicable to you.

Enjoy the icons!
