### ISSUE TITLE
com.devolo

### ISSUE THREAD

**Issue by mapulu** [athombv/homey-vectors-public#63]
Also this is not my app (it is an app from athom) but I want to add the devices to that app with a Pull Request.
But I need the missing Icons first.

Smoke Sensor MT2651
![smokesensor](http://manuals-backend.z-wave.info/img/DEV/DEVE9875/smoke.jpg)

Smart Plug MT 2792
![SmartPlug](https://www.devolo.de/shop/media/image/00/0e/75/9914_hc_schaltmesssteckdose_2-0_produktpicture_liegend_DE_screen_01_300x350H7T0Plz4gEq6C.png)

Thank you

**Comment by IvoDerksen** [comment]
Hello!

I expect them to be finished tomorrow.

Kind regards,
Ivo

**Comment by IvoDerksen** [comment]
Here you go!
