### ISSUE TITLE
athombv/com.aeotec vector images

### ISSUE THREAD

**Issue by vinta7** [athombv/homey-vectors-public#64]
Hi, please help with vector images for device Nano Shutter ZW141
![Nano Shutter ZW141](https://user-images.githubusercontent.com/47777127/61269637-84227480-a79f-11e9-95bf-3f46be20925a.jpg)

**Comment by IvoDerksen** [comment]
Here you go!

[switch_nano.svg.zip](https://github.com/athombv/homey-vectors-public/files/3395978/switch_nano.svg.zip)

**Comment by vinta7** [comment]
Thanks for the fast reply, but it is not the same, there are 7 screw holes in the Nano Shutter, only 6 holes in the Nano Switch.
Regards

**Comment by vinta7** [comment]
Thanks for the fast reply, but it is not the same, there are 7 screw holes
in the Nano Shutter, only 6 holes in the Nano Switch.
Regards

Den tir. 16. jul. 2019 kl. 12.20 skrev Ivo Derksen <notifications@github.com

**Comment by IvoDerksen** [comment]
Sorry, I've not looked at differences, will be redone before 5!

Kind regards!

**Comment by IvoDerksen** [comment]
And it's done!
