### ISSUE TITLE
com.popp custom capabilities

### ISSUE THREAD

**Issue by mapulu** [athombv/homey-vectors-public#65]
Hello!
I need more icons from you for the popp app
alarm_rain - like the measure_rain but with an exclamation mark (cloud with 2 raindrops)
measure_dewpoint - a thermometer icon with 3 raindrops on the right side.
measure_wind_strenght - a windsack
alarm_siren - maybe like something when google images "siren alarm icon"

Thank you

**Comment by mapulu** [comment]
And also want the measure_rain icon as capability icon for custom capability

**Comment by IvoDerksen** [comment]
Will be on these this week. 
I believe the wind_strenght is an existing capability already.

**Comment by mapulu** [comment]
Yes for wind_strenght is already a capability icon at the homey core. So I don't need a wind_strenght Icon.

If you have a idea for a mold alarm icon I also would use it. If not I use the generic alarm icon.

**Comment by IvoDerksen** [comment]
Here you go
