### ISSUE TITLE
com.abus

### ISSUE THREAD

**Issue by mapulu** [athombv/homey-vectors-public#67]
Hi, I need some of your wonderful vector icons for my ABUS Homey App.

Waterleak Detector
![Waterleak Detector](https://products.z-wavealliance.org/ProductImages/Index?productName=ZC10-18116319)

Magnetic Contact
![Contact](https://products.z-wavealliance.org/ProductImages/Index?productName=ZC10-18116318)

Multisensor
![Multisensor](https://products.z-wavealliance.org/ProductImages/Index?productName=ZC10-19016351)

Doorlock
![Doorlock](https://products.z-wavealliance.org/ProductImages/Index?productName=ZC10-19076649)

Bulb
![Bulb](https://products.z-wavealliance.org/ProductImages/Index?productName=ZC10-18106286)

Thank you

**Comment by IvoDerksen** [comment]
Hey! This will be done somewhere next week!

**Comment by IvoDerksen** [comment]
Here you go!
