### ISSUE TITLE
com.globalcache

### ISSUE THREAD

**Issue by SiobhanBaynes** [athombv/homey-vectors-public#68]
I’ve added the Flex range of devices to the com.globalcache app. Could you assist in providing vector images for them please?
App link: https://github.com/plarsson/com.globalcache/
Device images are here: https://www.globalcache.com/products/flex/

Thanks :)

**Comment by IvoDerksen** [comment]
Morning!

Yes I can make these icons. 
As far as I see there are two hardware distinctions, so I'll create those two icons!
I'm guessing they're done this week!

**Comment by IvoDerksen** [comment]
Hey!
Here you go!

**Comment by SiobhanBaynes** [comment]
Perfect, thanks! :)

**Comment by IvoDerksen** [comment]
You're welcome!
