### ISSUE TITLE
no.ThermoFloor vector images

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey-vectors-public#7]
Hi Ivo,

Working on another Thermostat app (Thermo-Floor aka Heatit) with a request for some nice vectors..

The App (store) picture; will clean it up a bit with the app icon. 
![thermofloor_app_500](https://cloud.githubusercontent.com/assets/17163431/25685226/5a0a9770-3066-11e7-96f9-4ca860274a8e.jpg)

Can you make the app icon and device icons?
App Icon (you could use only the Thermo Floor section of it)
![tf_logo](https://cloud.githubusercontent.com/assets/17163431/25685172/ff9cfc42-3065-11e7-9a3f-0c208865d7b3.png)

Device Icon == learnmode
![thermofloor_thermostat_empty](https://cloud.githubusercontent.com/assets/17163431/25685161/efb60396-3065-11e7-9087-67c31d0fd9cb.png)

Much appreciated (again)!

With kind regards,

Ted

**Comment by IvoDerksen** [comment]
They are done Ted!
Good luck on finishing or publishing the app!
