### ISSUE TITLE
Xiaomi ClearGrass Air Detector

### ISSUE THREAD

**Issue by GreyEarl** [athombv/homey-vectors-public#70]
Hi,

I would like to have a proper SVG of the following device:
https://www.red-dot.org/project/cleargrass-air-monitorcleargrass-luftueberwachung-39226/

I am also missing a TVOC (Total Volatile Organic Compounds) capability, which I'm using now as custom capability. Could you create one that is been used in this image?
https://ae01.alicdn.com/kf/HTB1YIe3azzuK1Rjy0Fpq6yEpFXa5/Xiaomi-Mijia-Clear-Grass-Air-Detector-3-1-IPS-Touch-Screen-Comprehensive-Monitor-PM2-5-APP.jpg_q50.jpg

I tried a custom SVG of my own, but for some reason Homey does not show the images that I created.

**Comment by IvoDerksen** [comment]
Hello GreyEarl!
Can you tell me what the app name is? e.g. com.xiaomi xxx

For VOC I've already created an icon
homey capability Icons/measure_VOC.svg

If it is not the same as tVOC I will create a new one.
Please let me know!

Kind regards,
Ivo

**Comment by GreyEarl** [comment]
Hi Ivo!

Ah, the VOC icon I now see in homey capability Icons/ would work indeed! Because there was no (t)VOC related App Reference to be seen I thought there would be no icon as well. The icon seems a bit smaller than other icons though:

https://imgur.com/a/vVEjdJH

The ClearGrass device is meant for the [io.homeassistant app](https://github.com/rogro82/io.homeassistant) to make it work with Homey.

**Comment by IvoDerksen** [comment]
Well I've tried to change it, making it bigger, unless there is an alarm.

And added the icon for the cleargrass.

happy coding!

**Comment by GreyEarl** [comment]
Great! Looks awesome, Ivo! Appreciate your fast response and action. On a Sunday :)
