### ISSUE TITLE
com.kaipule

### ISSUE THREAD

**Issue by mapulu** [athombv/homey-vectors-public#71]
Hello!
I need icon for Kaipule Z-Wave PIR Motion Sensor
https://images-na.ssl-images-amazon.com/images/I/61vEYgnFdRL._SL1500_.jpg

And Kaipule Z-Wave Door/Window sensor.
https://www.mindolife.com/wp-content/uploads/2017/12/IMG_8161-2-1.jpg

**Comment by IvoDerksen** [comment]
Sure!
Will be done tomorrow!

**Comment by IvoDerksen** [comment]
They're done already. Enjoy!
