### ISSUE TITLE
com.roco.pipup

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey-vectors-public#72]
I was asked for a icon.svg for app approvement so here is my request.
Image here:
![large](https://user-images.githubusercontent.com/19249884/68886368-64806600-0717-11ea-9ce4-379a9de4d50f.png)

**Comment by IvoDerksen** [comment]
Hey!

You're in luck, it was an easy one.
I'd choose icon.svg, due to readability. (got a second one based on above image  #too)

Happy coding, or appstore submission!
[Here it is](https://github.com/athombv/homey-vectors-public/commit/4cb99bbeec9317a1120ec0d4b114c8d9caf891d1)

Kind regards!
Ivo
