### ISSUE TITLE
request for icons new INNR filament vintage bulbs

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-vectors-public#74]
Request for icons concerning INNR filament vintage bulbs that are going to be released.
Pictures are in the big_filament_bulb_vintage and long_filament_bulb_vintage driver folder: https://github.com/kasteleman/com.innr

**Comment by IvoDerksen** [comment]
On it!

**Comment by IvoDerksen** [comment]
I've (reordered) placed all drivers in there.
The big_filament and long_filament are new!

**Comment by kasteleman** [comment]
Thx Ivo. Great Job

**Comment by kasteleman** [comment]
Hi Ivo,

it seems to me you mixed up the bulbs. Can you please check?
Also i changed the drivers directory and buld description to edison for the "long" and Glode for the "big" version of the filament vintage bulbs.

Thx,

Martin

**Comment by IvoDerksen** [comment]
You are right. Thanks!

I switched them. Did you mean globe or glode?

**Comment by kasteleman** [comment]
Oeps, Globe !
Thx
