### ISSUE TITLE
no.tjweb.opengarage

### ISSUE THREAD

**Issue by thorleifjaocbsen** [athombv/homey-vectors-public#77]
If you have time I would love a few icons.

1. App Icon their logo is (https://opengarage.io/wp-content/uploads/2016/11/logo.png) so a garage door?
2. Device icon, possible a garage door here aswell. As the device is a garage door opener.
3. Sensors: Car in garage
4. Sensor: Wifi signal strength (RSSI) shown in -57dB
5. Sensor: Distance measurement (the sensor hangs in ceiling and measures distance down to port or car to figure out where stuff is. This is a centimeter reading) 

Current view: https://imgur.com/a/wUdgSN7

**Comment by IvoDerksen** [comment]
Hey! I really like your preview of sensors already. They fit well I must say!

Do you mind if I only redo the distance to simply it? 
Else please tell me what you'd like to see.

I've done the app Icon, as the current (not so graceful) logo. But I've made the device icon, that you see in the app more appealing.
Is this what you'd expect?

Kind regards!

**Comment by thorleifjaocbsen** [comment]
Yeah I love them :) 

Better than what I had. The only thing is that the current car and wifi signal is ripped off a random website. Not sure about copyrights and stuff. If they could be remaked to also have the right sizes to fit right into my app that would be perfect. Thanks a lot so far!

**Comment by IvoDerksen** [comment]
Good point! Indeed copyright is a point, nounproject icons etc are free to use. The Wifi is no problem, I'll do the car with the appropriate linewidths too!

I'll mention you when it's done! (max one hour!)

**Comment by thorleifjaocbsen** [comment]
No hurry! Thanks a lot! :)

**Comment by IvoDerksen** [comment]
Here you go!
