### ISSUE TITLE
cn.kaiterra

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/homey-vectors-public#78]
Hey
I am working on a Kaiterra integration over here https://github.com/MadMonkey87/homey.kaiterra. Could you please provide me the following icons?

- kaiterra logo without the text, [see](https://www.kaiterra.com/uploads/medias/a4e765e8-3364-4043-ae1a-295803e0d64a/kaiterra-logo-2019-white-01.svg)
 - a logo for the laser egg device see [laser egg](https://www.kaiterra.com/en/laser-egg), [laser egg+ chemical](https://www.kaiterra.com/en/laser-egg-chemical), [laser egg+ CO2](https://www.kaiterra.com/en/laser-egg-co2), [sense edge](https://www.kaiterra.com/en/sensedge)
 - a capability logo for the air quality index (aqi)

Thx a lot!

**Comment by IvoDerksen** [comment]
Here you go!
