### ISSUE TITLE
com.hiome

### ISSUE THREAD

**Issue by Piotr-Grochowski** [athombv/homey-vectors-public#79]
Hello,
I'm working on Hiome.com occupancy sensors integration. I need an icon for devices: occupancy sensor and door sensor. 
The occupancy sensor looks like the one on the webpage: www.hiome.com (wired one).
The door sensor is the same as occupancy sensor + a magnet under him (rectangular).

Also I would need an icon for a capability: number of people in a room (I think the best would be an icon with e.g. 3 persons).

**Comment by IvoDerksen** [comment]
Hey!
I saw the icon of Hiome when it was asked if the icon was properly set up.

Did you succeed?

I'll get on to this :)

**Comment by Piotr-Grochowski** [comment]
Hello,
The app is under review with some temporary icons, after I submitted I saw this GitHub project. 
Reg. the question if the Hiome icon was properly set up - I don't know what you mean, no one asked me about this.

Thanks!

Piotr

**Comment by IvoDerksen** [comment]
Ah oké! Then maybe I was asked by our reviewer!
Never mind then!

The system looks really useful, I have 'occupancy' sensors, but this one seem really good :)

**Comment by Piotr-Grochowski** [comment]
Yeah, I use them for about a week and I'm really impressed. They work flawlessly, I can remove most of my motion sensors because Hiome gives me much better effects. After another week or two of tests with this app and Homey integration I will make a review on our community forum, because I think much more people may be interested in Hiome.

Piotr

**Comment by IvoDerksen** [comment]
Hey! I got an update for you. I think monday I'll be done. 
But I've checked with the one reviewing your app for my side, and redid your app icon. I don't know exactly why, but there was a big white background (probably a clipping mask). It's fixed now and added to the other icons :)

**Comment by Piotr-Grochowski** [comment]
Great, that's really fast!
Reg the logo - I've received it from the producer. Thanks for corrections!

**Comment by IvoDerksen** [comment]
Here you go, the core and core with magnet.
And the logo working properly.

Good luck, and I'm awaiting the review. 
Would you mind reminding me here? I don't browse the community forum often :)

**Comment by Piotr-Grochowski** [comment]
Hello,
Thank you, but... I need a sensor, and sensor with magnet, not the core...

Yes, I’ll remind you when I publicysta the review.

**Comment by Piotr-Grochowski** [comment]
![12A881E7-B7AF-41D3-AE2E-FE3C0BA7A953](https://user-images.githubusercontent.com/51405454/80414818-e6350c00-88d1-11ea-8271-f97f03183b51.png)
![B93A0B64-479E-49F2-87A2-904626C7D7A9](https://user-images.githubusercontent.com/51405454/80414833-ecc38380-88d1-11ea-9b4d-f96f89cb3129.png)

Here is the sensor

**Comment by IvoDerksen** [comment]
Ah, too

**Comment by Piotr-Grochowski** [comment]
Occupancy capability You mean?

**Comment by IvoDerksen** [comment]
Yes indeed!
Do you also have an image of the magnet + sensor?

**Comment by Piotr-Grochowski** [comment]
![image](https://user-images.githubusercontent.com/51405454/80415433-d669f780-88d2-11ea-9bf8-28b8436f4fbd.jpg)

![image](https://user-images.githubusercontent.com/51405454/80415481-e681d700-88d2-11ea-870b-ad5c5e85d74a.jpg)

Occupancy and Door sensor (with magnet)

**Comment by Piotr-Grochowski** [comment]
![image](https://user-images.githubusercontent.com/51405454/80415599-0c0ee080-88d3-11ea-99da-804735c094e5.jpg)

![image](https://user-images.githubusercontent.com/51405454/80415639-19c46600-88d3-11ea-8358-2a69e7197fe9.jpg)

Occupancy only sensor (no magnet)

**Comment by IvoDerksen** [comment]
Thank you. On them again. I'm sorry! Will be done tomorrow :)
Including the capability icon!

**Comment by Piotr-Grochowski** [comment]
Thanks!

**Comment by IvoDerksen** [comment]
Hey Piotr, I've created a clean sensor image. and one with a magnet! 

Enjoy and good luck on completing the app!

**Comment by IvoDerksen** [comment]
Look at the last commit, I'm sorry, it exports PNGs by default, they look the same in my preview window. 

It's all good! Goodluck!

**Comment by IvoDerksen** [comment]
For the capability icon I prefer ocupancy4.svg

You too?

**Comment by Piotr-Grochowski** [comment]
Thank you very much!
They look really great! And I also prefer occupancy4.svg - I will use it.

**Comment by Piotr-Grochowski** [comment]
I promised to let you know when I post the review on the community forum. Here is the link to the small review I've made: https://community.athom.com/t/app-hiome-almost-perfect-occupancy-sensors/30401
