### ISSUE TITLE
com.xiaomi-miio

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#8]
Hello,

I'd like vector images for the following.

- Mi Home Logo: https://xiaomi.eu/store/images/feature_variant/0/mi-jia-logo-250-2.jpg
- Mi Air Purifiers: https://76.my/Malaysia/original-xiaomi-mi-air-purifier-high-perfomance-smart-air-purifier-miworld1-1602-15-F65237_1.jpg
- Mi Humidifier: https://gloimg.gearbest.com/gb/pdm-product-pic/Electronic/2016/12/07/goods-img/1481053203350488133.jpeg
- Mi Smart Power Strip: https://xiaomi.eu/store/images/detailed/0/xiaomi-6sckt-smart-power-strip-white-mew.jpg
- Mi Smart Socket Plug: https://xiaomikopen.nl/wp-content/uploads/2017/03/Xiaomi-Mi-Smart-WiFi-Socket.jpg
- Mi Smart Home Gateway: https://xiaomi.eu/store/images/detailed/0/xiaomi-mi-jia-smart-home-gateway.jpg
- Yeelight: http://image4.geekbuying.com/ggo_pic/2016-06-03/201606301757331an4pxif.jpg
- A custom capability icon for Air Quality Index, something like: http://a2.mzstatic.com/us/r30/Purple3/v4/c8/f8/cb/c8f8cb49-bb08-cf2c-5852-6680e79b4abf/icon175x175.png or http://a5.mzstatic.com/us/r30/Purple6/v4/d2/31/7d/d2317d7a-edc0-302c-fc12-0802a6cb5852/icon175x175.png

**Comment by IvoDerksen** [comment]
Can be expected after the weekend!
Nice app, looking forward to it!

**Comment by IvoDerksen** [comment]
Hello Jelger,

I also made a few alternatives for the purify icon.
You can check if you understand them, and which you prefer.
This will probably be also integrated as a sensor icon, so please let me know which you prefer, so I can take in account your preference and input as well!

[purify_alternatives.zip](https://github.com/athombv/homey-vectors-public/files/1021859/purify_alternatives.zip)

**Comment by jghaanstra** [comment]
Hello Ivo,

Thanks for all the icons. Aesthetically I'd go with the 2nd purify icon but I think the first one is more self explaining because it shows best what an air purifier actually does. So my vote goes out to #1.

**Comment by jghaanstra** [comment]
@IvoDerksen I'd like to request two more Yeelight icons for this app.

**Yeelight Bedside Lamp II:** https://www.mi.com/mj-bedsidelamp/
Unfortuntely it's hard to find a good image. The lamp is very similar to the Yeelight Bedside Lamp I one though. Only the color of that base and the logo on the base are different. It would not be a big deal to just use this image: http://www.megaone.pk/wp-content/uploads/2015/09/xiaomi-yeelight-pakistan.jpg

Yeelight Ceiling Lamp: https://c.76.my/Malaysia/xiaomi-yeelight-smart-ceiling-light-lamp-remote-app-mi-wifi-bluetooth-whypaymoreonline-1704-05-whypaymoreonline@2.jpg

**Comment by IvoDerksen** [comment]
Added the icons!

**Comment by jghaanstra** [comment]
Awesome, thanx @IvoDerksen .

**Comment by jghaanstra** [comment]
@IvoDerksen 

I have one more, could you create a vector icon for the Yeelight Ceiling Lamp: https://image2.geekbuying.com/ggo_pic/2017-10-13/Xiaomi-Yeelight-Moonlight-Smart-LED-Ceiling-Light-474856-.jpg

**Comment by IvoDerksen** [comment]
Sure, expect them after the weekend!

**Comment by jghaanstra** [comment]
Great, no rush to it. Still got to code the drivers.

**Comment by IvoDerksen** [comment]
Here you go! Happy Holidays!

**Comment by jghaanstra** [comment]
@IvoDerksen I have another request. Could you supply me with vector icons for these. Thanks in advance.

**PM2.5 Monitor:** https://www.solidrop.net/photo-2/original-xiaomi-mi-pm2-5-detector-know-your-air-anytime-anywhere-helps-track-real-time-air-quality-clock-mode-cute-portable.jpg

**WiFi DC Fan**: https://www.dhresource.com/0x0s/f2-albu-g5-M01-4D-89-rBVaJFnsYn-AedVxAAHg1zVfKBw095.jpg/original-xiaomi-mi-smart-dc-frequency-stand.jpg

**Comment by jghaanstra** [comment]
@IvoDerksen Any news on the PM2.5 monitor and WiFi DC Fan vector images?

**Comment by IvoDerksen** [comment]
Yes! I'm working on them! Tomorrow or tonight!

**Comment by IvoDerksen** [comment]
There is still room for improvement, although I want to keep them simple. 
They are pushed right now!

**Comment by jghaanstra** [comment]
Hi Ivo, can I get a svg for the Yeelight Desk Lamp.

https://www.yeelight.com/en_US/product/mijia-lamp

Thanx in advance.

**Comment by IvoDerksen** [comment]
Yes on it!

**Comment by IvoDerksen** [comment]
And it's committed!

**Comment by jghaanstra** [comment]
Hello Ivo, Xiaomi has released an new humidifier with different capabilities. I will be making a new driver for it and therefor also need a new icon.

https://nl.aliexpress.com/item/2018-Originele-Smartmi-Xiaomi-Evaporative-Luchtbevochtiger-2-voor-uw-huis-Air-dampener-Aroma-diffuser-essenti-le/32854744155.html

**Comment by IvoDerksen** [comment]
Sure!

**Comment by jghaanstra** [comment]
And yet another product, would be great if you could make an icon for the Yeelight Bedside Lamp 2: https://www.dhresource.com/0x0s/f2-albu-g8-M00-09-2B-rBVaVFw1wJ6AZkMdAAGbv1fB3nU952.jpg/original-xiaomi-mi-bedside-lamp-2-mijia-smart.jpg

**Comment by IvoDerksen** [comment]
Hey Jelger,
On that one. Expect a rainy icon forecast after the weekend.

By coincidence I was checking this thing out too.
A real smart Philips wake up light. Integrate these flows within Homey

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by jghaanstra** [comment]
A new Yeelight has been released. Could you fix me an icon for it?

https://www.aliexpress.com/item/YEELIGHT-Meteorite-LED-Pendant-Lights-Wireless-APP-Control-Colorful-Atmosphere-Lighting-Xiaomi-Indoor-Light/32964899139.html

**Comment by IvoDerksen** [comment]
Yes!

**Comment by IvoDerksen** [comment]
Here you go!
