### ISSUE TITLE
nl.klikaanklikuit ZPIR 8000 & ZCTS-808

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/homey-vectors-public#80]
Hi, could you please create an icon of the following zigbee sensors?

https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn/zpir-8000-draadloze-bewegingssensor.html

https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn/zcts-808-zigbee-draadloze-contactsensor.html

**Comment by IvoDerksen** [comment]
Yes on it!

**Comment by IvoDerksen** [comment]
Here you go! I got 2 motion sensor Icons, normally I'd recommend icon2(since it is less prominent), but I'm curious what you think!

Happy coding and implementing your zigbee hardware!
