### ISSUE TITLE
[de.dresden-elektronik.zigbee] App icon and LED driver icon

### ISSUE THREAD

**Issue by KyleTaylorParkins** [athombv/homey-vectors-public#86]
Hi Ivo,

For my Dreden Elektronik Zigbee app I'm needing some icons to finish the first version of the app.
I"ll need an app icon. I've already tried to use this one: https://www.dresden-elektronik.de/assets/images/1/logo-9997a4ed.svg, but that looks quite weird because it's too long. The 'E' would be nice as an app icon since it would be a perfect fit in Homey's icon system.

For the driver, I'm currently support this LED driver in the app: https://www.dresden-elektronik.de/files/dresden-elektronik/content/produkte/BN-600093_3.jpg
Since most of their drivers look identical, it would be nice to create a generic LED driver shape which only contains the text 'Phoscon FLS'. Should I decide to add other drivers I can simply reuse the same icons!

Thanks in advance!

**Comment by IvoDerksen** [comment]
Here you go man! I did refrain from the use of text, as well as given you the choice the choose between the LEDdriver or a LEDstrip icon. 
Fixed the logo too!

Happy coding!
