### ISSUE TITLE
Icon for INNR OSL Outdoor Spot

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey-vectors-public#88]
Request for icon for the INNR OSL Outdoor Spot. Link for jpg: https://github.com/kasteleman/com.innr/blob/master/drivers/rgbw_osl/assets/images/OSL%20130%20C%20Spot%20Outdoor%20Spot%20on%20shadow.jpg

**Comment by IvoDerksen** [comment]
Ofcourse
