### ISSUE TITLE
Capability icons as SVG

### ISSUE THREAD

**Issue by Joolee** [athombv/homey-vectors-public#89]
I'm allowing users to select their own Homey capability for some device types. For single-capability devices, it would be nice if I could set the device icon to that capability instead of a generic icon. Is it possible to release the standard Homey capability icons in SVG format? I can only find them as PNG's.

**Comment by IvoDerksen** [comment]
Hello!

It's policy that I can't just pass on our internal icons through Github. You can request them by mailing Athom support, they'll be able to give a more appropriate answer and might provide you with the pack/permission to PM me :)

Just refer to this issue :)

Sorry!
