### ISSUE TITLE
tv.video.sonarr.radarr

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey-vectors-public#9]
Hi Ivo,

I'd like to have icons for Sonarr and Radarr download software.

Driver Sonarrr: https://github.com/Sonarr/Sonarr/tree/develop/Logo
Driver Radarr: https://github.com/Radarr/Radarr/tree/develop/Logo

App icon: a combination of the two, below is the app store image I plan to use, would be great if you can match the icon.svg for it.

![large](https://cloud.githubusercontent.com/assets/4710062/26752109/a3f8554e-4848-11e7-92fd-f036c4e3ba4f.jpg)

**Comment by IvoDerksen** [comment]
Will do!

**Comment by IvoDerksen** [comment]
Hello Jelger,

Here is a folder with some iterations. My preference based on your image would be the third svg.
But let me know I'm curious which one you'll use!

Good going Jelger! Good luck on finishing the app!

[sonarrradarr.zip](https://github.com/athombv/homey-vectors-public/files/1057130/sonarrradarr.zip)

**Comment by jghaanstra** [comment]
Definitely number three, thanks it looks great.

But could I get seperate Radarr and Sonarr icons as well for the drivers?

**Comment by IvoDerksen** [comment]
Ofcourse! I'm almost done and then I'll close the issue with the driver icons inside the folder too!

**Comment by jghaanstra** [comment]
Awesome as always, thanx again!

**Comment by jghaanstra** [comment]
Could you fix me an svg icon for Lidarr Ivo?

https://opencollective-production.s3-us-west-1.amazonaws.com/b20d21f0-31ef-11e8-b30b-796b88a5d246.png
