### ISSUE TITLE
com.neo - new device vectors

### ISSUE THREAD

**Issue by mruiter** [athombv/homey-vectors-public#90]
Hello,

It would be great if i could get vector icons for the new NEO products.

The new 5 in 1 sensor: https://www.robbshop.nl/5-in-1-bewegingssensor-z-wave-plus-neo-coolcam?sqr=neo%20coolcam%20&

The new doorsensor: https://www.robbshop.nl/raam-deursensor-z-wave-plus-met-usb-voeding-neocoolcam?sqr=neo%20coolcam%20raam&

The new siren:  https://www.robbshop.nl/alarm-sirene-2-z-wave-plus-neo-coolcam?sqr=neo%20siren&

Thank YOU !!!

**Comment by IvoDerksen** [comment]
On it!
