### ISSUE TITLE
com.aeotec - ZWA001 and ZWA002 icon request

### ISSUE THREAD

**Issue by Aeotec-ccheng** [athombv/homey-vectors-public#91]
Requesting ZWA001 and ZWA002 icon.

Attached is the SVG we created, but it seems to create a black block. (ZWA001 and ZWA002 look like the same product)

[ZWA001ZWA002.zip](https://github.com/athombv/homey-vectors-public/files/4923256/ZWA001ZWA002.zip)

**Comment by IvoDerksen** [comment]
Will do!

**Comment by Aeotec-ccheng** [comment]
@IvoDerksen Thanks! :)

**Comment by IvoDerksen** [comment]
Hi! To remark on the icon: It had a clipping mask.

I've redone the style to make it open, yet bold.
[icon.zip](https://github.com/athombv/homey-vectors-public/files/4928361/icon.zip)

Enjoy, and happy coding!

**Comment by IvoDerksen** [comment]
I've closed the issue! If you have any remarks let me know, I'll reopen it then.
