### ISSUE TITLE
nl.homewizard request for heatlink and energylink

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [athombv/homey-vectors-public#92]
Hi i would like some svg's for the
Homewizard heatlink
![image](https://user-images.githubusercontent.com/1246691/87770176-f4cef780-c81e-11ea-83f0-01cf55b7c5bc.png)

Homewizard energylink
![image](https://user-images.githubusercontent.com/1246691/87770245-10d29900-c81f-11ea-9554-b516eec17dc1.png)

The only big difference is the color, but perhaps it could be replaces with a temperature icon and a energy bolt icon in the middle

**Comment by ricardovanlaarhoven** [comment]
Perhaps the logo/icon of the app can use some simplification as wel
![image](https://user-images.githubusercontent.com/1246691/87871431-73a76a00-c9b0-11ea-927b-41662659f106.png)
https://github.com/ricardovanlaarhoven/nl.homewizard/blob/master/assets/icon.svg

**Comment by IvoDerksen** [comment]
Good idea!
I've added an icon based on the favicon of their website, to honor and adhere to their style.

Created the heat and energylink as well.

Enjoy your sunday!
