### ISSUE TITLE
Aqara Opple switches

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/homey-vectors-public#93]
Hi, could you please create some nice icons for the following Aqara Opple switches
![image](https://user-images.githubusercontent.com/29612400/87880917-e0912300-c9f5-11ea-92b2-ca0fe7a413b4.png)

![image](https://user-images.githubusercontent.com/29612400/87880925-f9013d80-c9f5-11ea-8120-cf386d250eca.png)

![image](https://user-images.githubusercontent.com/29612400/87880937-0ae2e080-c9f6-11ea-99fd-f5eac7eeb32e.png)

**Comment by IvoDerksen** [comment]
Done before the weekend!

**Comment by IvoDerksen** [comment]
There you go
