### ISSUE TITLE
Some xiaomi-mijia ecosystem devices

### ISSUE THREAD

**Issue by maxinminax** [athombv/homey-vectors-public#94]
Hi, could you please create some nice icons for the following Xiaomi-mijia devices
- Yeelight
![93b12a8a4e736cc97e5cfbc8e96132e2](https://user-images.githubusercontent.com/4716949/89717718-68f65880-d9e3-11ea-88c8-397d25d92f43.png)
![47d1b5e1b5c8eab1b5b5f58d146865f1](https://user-images.githubusercontent.com/4716949/89717734-81667300-d9e3-11ea-801d-e639abf12913.png)
![dc60f1dec051f327cdaebfe7700cb72f](https://user-images.githubusercontent.com/4716949/89717740-8a574480-d9e3-11ea-8afa-ce09f2b17dcb.png)
- Smartmi
![ffab1e2592a3c0600b97821dad87aaa2](https://user-images.githubusercontent.com/4716949/89717760-b4a90200-d9e3-11ea-987a-621057b8e729.png)
![cae22d7f83102a43cc586c40f4b222e8](https://user-images.githubusercontent.com/4716949/89717766-c4284b00-d9e3-11ea-9ad4-5c808be13b20.png)
![d1e5cacdbd8a35f26711f2f2205a2f03](https://user-images.githubusercontent.com/4716949/89717781-dd30fc00-d9e3-11ea-8242-a9e69d846d1f.png)
- Aqara
![bf14fc3d3c2c55c884bd10bdfcd4e882](https://user-images.githubusercontent.com/4716949/89717846-752ee580-d9e4-11ea-8ef9-2701b99f7000.png)
![45d7389c0c6c4302fedf098cc76ea8ae](https://user-images.githubusercontent.com/4716949/89717863-aad3ce80-d9e4-11ea-90af-9993d62f1ba2.png)
- Viomi
![45d7389c0c6c4302fedf098cc76ea8ae](https://user-images.githubusercontent.com/4716949/89717873-c2ab5280-d9e4-11ea-9681-6a4b14397c9a.png)
![e23fbf4d64b2ec99772049a882cb3ad1](https://user-images.githubusercontent.com/4716949/89717886-e1114e00-d9e4-11ea-91eb-ffb7a8d9503f.png)
![e175d7f565b135ce364a2a36f1a70070](https://user-images.githubusercontent.com/4716949/89717893-ef5f6a00-d9e4-11ea-9bca-4fc05f78a51c.png)
![00458dbd2a46116851bdb83fd8939e45](https://user-images.githubusercontent.com/4716949/89717904-0a31de80-d9e5-11ea-8633-e7a38b186b4a.png)
![b9350923679f4135dca33bb499b8581d](https://user-images.githubusercontent.com/4716949/89717910-15850a00-d9e5-11ea-81c5-7465aa4f73a9.png)
![c023f5e244aa204bc5a014393677c23a](https://user-images.githubusercontent.com/4716949/89717919-259ce980-d9e5-11ea-8baa-f09d9b939ff8.png)
![b1b53fc4a8590dba35c11e5bc900561e](https://user-images.githubusercontent.com/4716949/89717928-436a4e80-d9e5-11ea-9ed5-b2ef423ee370.png)
![5f99e2ac41427c63d371d3ca9a90e412](https://user-images.githubusercontent.com/4716949/89717937-4f561080-d9e5-11ea-8266-489bff94d821.png)
![d8b3f129a30819e26a5005bff3e414ab](https://user-images.githubusercontent.com/4716949/89717973-af4cb700-d9e5-11ea-994c-7e9d300f42e6.png)
![8d94b18517519b061d9ba2d2871a5d77](https://user-images.githubusercontent.com/4716949/89717987-d0150c80-d9e5-11ea-857b-dff3a6e145d2.png)
![46d7486c5b723a61e35f24104ef8c9ad](https://user-images.githubusercontent.com/4716949/89718003-efac3500-d9e5-11ea-9d3b-caec719515c1.png)
- Newaytech
![63591872fb7a73fe478d2127ccd70916](https://user-images.githubusercontent.com/4716949/89718004-03f03200-d9e6-11ea-827d-9d6495c6bb8f.png)
![946528e8bec8b8ba39e71ceb6ccc243e](https://user-images.githubusercontent.com/4716949/89718010-11a5b780-d9e6-11ea-9ac7-d88d4cee5fbe.png)

**Comment by IvoDerksen** [comment]
I like how you said 'some' haha.

Yes I'll have a look! Can take a while though!

**Comment by maxinminax** [comment]
Because there are only a part my home's devices. Could call me as xiaomi's fan.
Thanks about the fast reply

**Comment by AdyRock** [comment]
Would it be OK if I steal the svg for the light strip for the SwitchBot app, as I used a stock image for that and I'm sure yours will look a lot nicer. Plus consistency in Homey ;-)
