### ISSUE TITLE
Mold Growth Indicator App- and Device-icon request

### ISSUE THREAD

**Issue by nermt** [athombv/homey-vectors-public#95]
Hi,
I would like to request an app icon and a device icon for my Homey app.

The app creates an virtual sensor device which will indicate the risk of mold growth in an environment using input from existing temperature and relative humidity sensors.

App ID: com.nermt.moldgrowthindicator

**Comment by IvoDerksen** [comment]
Hello! Here you go!
Do you think these represent mold pretty good!

**Comment by nermt** [comment]
Awesome!
Thanks!
