### ISSUE TITLE
rs.muete.homey-buva

### ISSUE THREAD

**Issue by ultimate-tester** [athombv/homey-vectors-public#98]
Aims to provide integration for at least the Q-Stream 2.0 product.

Here's the official app icon from the App Store:
https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/ba/b9/ff/bab9ff88-9c7f-730c-fa63-209067c2e47e/AppIcon-1x_U007emarketing-0-7-0-0-85-220.png/600x600wa.png

Here's the brand logo:
https://www.buva-online.nl/content/files/images/HOME%20banners/BUVA%20logo%20try%20out.png

**Comment by IvoDerksen** [comment]
Thanks for the examples, here you go!
