### ISSUE TITLE
com.husqvarna.automower

### ISSUE THREAD

**Issue by magohl** [athombv/homey-vectors-public#99]
Would really like some help with an icon for the Husqvarna Automower.

Maybe something like this:
https://hqvcdn3.azureedge.net/qs_ver=1222cb473509abcde8ab69c79386dcd2&hcsh=22F66F540A827A289882C9DB8E3532F1/_$$_/media/damroot/husqvarna/garden%20lawnmowers%20and%20ride-on%20mowers/robotic%20lawnmowers/studio/h310-10xx/h310-1051.png?w=1400&ver=20150927T181435

**Comment by IvoDerksen** [comment]
How about this? Front view is not so 'classic automower' as the side view.

**Comment by magohl** [comment]
Looks great, thanks for your help!

**Comment by IvoDerksen** [comment]
Good luck on completion and enjoy your Mower!
